### ISSUE TITLE
اولین ایشیو؟

### ISSUE THREAD

**Issue by Saleh-Mumtaz** [radkesvat/WaterWall#1]
درود مهندس، به سلامتی باشه
انشاالله به زبان سی برنامه پایدارتر و قدرتمندتری بسازید!

**Comment by radkesvat** [comment]
سلام تشکر واقعیتش یه سکته ریز زدم اولین ایشیورو دیدم وقتی هنوز چیزی منتشر نشده 🤣

لطف دارید ؛ امیدوارو به سرنوشت پروژه های قبلی دچار نشه فقط 🤲📿

**Comment by Saleh-Mumtaz** [comment]
ترم یک درسی با عنوان برنامه نویسی پاس کردیم، سی یاد میدادن، همیشه میخواستم بپرسم ازتون برای اینکه با زبان سی پلاس پلاس از اینجور برنامه های شبکه بنویسیم میشه راهنمایی کنید چه منابعی بخونیم؟ کامال یوتیوبی چیزی سراغ دارید؟

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by radkesvat** [comment]
این ۳ تا منبع رو پیشناهاد میکنم البته اگه c بلدید ؛‌ اولی و دومی رو نیاز نیست کامل بخونید در حد رفرنس نگاش کنید

https://beej.us/guide/bgc/

https://beej.us/guide/bgclr/

https://beej.us/guide/bgnet/

چهارمی هم اموزش شبکه هست که از دیدگاه برنامه نویسی نیست کانسپتی هست بیشتر 

https://beej.us/guide/bgnet0/


درکل ؛ برنامه نویسی برای شبکه کار پیچیده ای نیست ؛‌یه مقداری باید علاوه بر زبان برنامه نویسی ؛‌ سیستم عامل رو شناخت و نحوه کارکرد و api هایی که میدن و مفاهیمی مثل nonblocking io  که توی همون کتاب هایی که دادم کامل توضیح داده شده.
