### ISSUE TITLE
مشکل با ورژن بالاتر از 5

### ISSUE THREAD

**Issue by H4m3d84** [radkesvat/WaterWall#10]
دروود و خسته نباشید و تشکر بابت زحمت هایی که میکشید. من یه مشکل عجیب دارم. با نسخه 5 برنامه تانل های پورت به پورت مستقیم و ریورس tcp (بدون tls) کار میکنن. ولی برنامه رو که به ورژن های بالاتر آپدیت میکنم دیگه هیچکدوم از تانل ها کار نمیکنن. آیا جایی از برنامه باید تنظیم خاصی بشه تو ورژن های بالاتر؟
مورد بعدی اینکه تانل ریورس با tls روی هیچکدوم از ورژن ها برای من کار نمیکنه. با چند تا دامنه که تازه خریداری شده تست کردم و تنظیماتم هم مطابق wiki بوده... بنظرتون کجای کارم ایراد داره؟ آی پی سرورها و دامنه ها هم تمیز هستن و روی چند تا سرور تست کردم بنابراین مشکل از این نمیتونه باشه...

**Comment by radkesvat** [comment]
نسخه جدید چند ساعت دیگه منتشر میشه با اونم تست کنید و اطلاع بدید

**Comment by milad84z** [comment]
من هم تا نسخه ۵ تمامی تانل ها رو بدون مشکل اجرا میکردم،ولی نسخه ۶ هیچکدوم کار نکرد،رو چنتا سرور مختلف هم تست کردم

**Comment by H4m3d84** [comment]
دروود و سپاس بابت ورژن جدید🌹. تستش رو انجام دادم. 
در ورژن جدید (ورژن 8) ریورس **بدون tls**، ابتدا ارتباط برقرار شد و وی پی ان پینگ داد اما بعد از چند ثانیه سرور **سمت ایران** پیغام Segmentation fault (core dumped) داد و ارتباط قطع شد!
همچنین در همین ورژن ریورس **با tls** سرور **سمت خارج** دقیقا پس از اجرای تانل همین پیغام یعنی Segmentation fault (core dumped) رو داد و اصلا ارتباطی برقرار نشد که بخوام وی پی ان رو متصل کنم...
ممنون از وقتی که میزارید

**Comment by H4m3d84** [comment]
مشکل دیگه ای که دیدم، تو نسخه 5، ریورس تانل tcp، بعد از گذشت یه مدت (مثلا چند ساعت بعد از اجرا) قطع میشه که دستی باید سرویسش رو روی هر دو سرور ایران و خارج ریستارت کرد تا درست شه. اگر لازمه و میشه از لاگ ها چیزی فهمید بگید که دفعه بعد که دیدم اینجوری شده، لاگش رو براتون بفرستم

**Comment by H4m3d84** [comment]
تست ورژن 9:
با توجه به بررسی هایی که در حالت های مختلف انجام دادم، چیزی که من دستگیرم شده اینه که تانل روی دیتاسنترهای متفاوت رفتارهای مختلفی از خودش نشون میده!
رو دیتاسنتر ایران اولی فقط حالت پورت به پورت مستقیم جواب میده (البته قبلا ubuntu 20 روش نصب بود و همینم کار نمیکرد. بعد که ubuntu ورژن 22 نصب کردم کار کرد). ریورس tcp رو این دیتاسنتر کار نمیکنه و ارتباط بین سرور خارج و ایران برقرار نمیشه و سرور خارج خطای زیر رو میداد:
WARN  connfd=8 connect error: Transport endpoint is not connected:107
2024-05-17 00:15:37.231 DEBUG TcpConnector: received close for FD:8

رو دیتاسنتر ایران دومی علاوه بر پورت به پورت مستقیم، حالت ریورس tcp هم کار میکنه. البته در درازمدت تستش نکردم ولی ظاهرا مشکلی نداره (اگر داشت بعدا اعلام میکنم)
اما حالت ریورس tls همچنان روی سرور خارج خطای 
DEBUG Core: starting workers ...
Segmentation fault (core dumped)
میده و ارتباط اصلا برقرار نمیشه (روی دوتا سرور خارج از دو دیتاسنتر مختلف با آی پی های تمیز تست کردم و هر دو این خطا رو میداد و دقیقا بعد نمایش starting workers خطا نشون میداد و تانل اجرا نمیشد). اما سرور ایران ظاهرا منتظر برقراری ارتباطه...
ببخشید طولانی شد. لازم بود بگید تستهای تکمیلی بگیرم

**Comment by radkesvat** [comment]
ممنون که اطلاع میدین و تست میکنید ؛ طی نسخه هایی که همینطور منتشر میشن مشکلات برطرف خواهند شد
