### ISSUE TITLE
balance-interval

### ISSUE THREAD

**Issue by Kup1ng** [radkesvat/WaterWall#100]
سلام اقای رادکسوت خسته نباشید
ممنون از زحمات شما
میشه بفرمایید برای بالانس اینتروال در روش ریورس ریلیتی + half duplex این پارامتر balance-interval را باید در کدام قسمت قرار بدیم؟
باتشکر

**Comment by radkesvat** [comment]
داخل همون نود tcp listener

**Comment by Kup1ng** [comment]
ممنون
این مثال برای اینتروال ۵ دقیقه ای صحیحه ؟
"balance-interval": 5

**Comment by Kup1ng** [comment]
اینی که برای مثال خدمتتون فرستادم را تست کردم ظاهرا کار نمیکنه

**Comment by radkesvat** [comment]
خیر این یعنی ۵ میلی ثانیه

**Comment by Kup1ng** [comment]
پس برای ۵ دقیقه باید عدد 300000 را بزارم ؟ یا اینکه مقداری وجود داره مثلا m که بنویسم 5m و ۵دقیقه لحاظ بشه؟
ببخشید وقتتونم گرفتم

**Comment by radkesvat** [comment]
خواهش میکنم ؛ فعلا به میلی ثانیه ورودی میگیره که یعنی همون عدد سی صد هزار برای پنچ دقیقه میشه ؛ دیفالت هم یک دقیقه هست

**Comment by Kup1ng** [comment]
خیلی ممنون از راهنمایی شما
