### ISSUE TITLE
آیا راهی هست علاوه بر ترافیک tcpترافیک udp هم عبور داد 

### ISSUE THREAD

**Issue by hatinati2** [radkesvat/WaterWall#101]
سلام مهندس وقت بخیر
خسته نباشید
ممنون از زحمات شما
آیا راهی هست علاوه بر ترافیک tcpترافیک udp هم عبور داد 
اگر بخواهیم هم tcp و هم udp عبور بدیم باید "type": "TcpListener", به چه چیزی تغییر بدیم؟
ممنونم

اگر ممکن هست در حد زیر دیپلم بفرمایید
با تشکر

**Comment by Saleh-Mumtaz** [comment]
درحال گنجاندن wireguard هستن

**Comment by lokidv** [comment]
لطفا وایرگارد هم اضاف کنین

**Comment by hatinati2** [comment]
> درحال گنجاندن wireguard هستن

شاید من منظورم درست بیان نکردم
من نیاز دارم در کنار ترافیک tcp  هسته ی xray سرور، بتوانم ترافیک udp کانفیگ های هیستریا هم تانل کنم
