### ISSUE TITLE
reverse cdn http

### ISSUE THREAD

**Issue by ali6043** [radkesvat/WaterWall#102]
سلام مهندس 
وقت بخیر. 
برای ریورس زدن با پورت http چه تغییراتی باید روی کانفیگ انجام بدیم.من قسمت sslclient و h2client رو حذف کردم ولی جواب نگرفتم.
مشکل دوم اینکه روی پورت 443 اتصال ریورس cdn به هیچ وجه برقرار نمیشه و فقط با پورت های دیگه وصل میشه که سرعتش اصلا جالب نیست.
@radkesvat

**Comment by Saleh-Mumtaz** [comment]
با اسکریپت تانل انجام بدید
