### ISSUE TITLE
متصل میشه ولی کار نمیکنه

### ISSUE THREAD

**Issue by sirdali00** [radkesvat/WaterWall#103]
درور من روش tls tunnel رو انجام دادم همه چی اوکیه حتی پینگ هم میده ولی توی برنامه هایی مثل تلگرام یا اینستاگرام کار نمیکنه
حتی توی مرورگر هم کار نمیکنه
ممنون میشم کمککنید تا مشکلمو حل کنم

**Comment by Saleh-Mumtaz** [comment]
درود با اسکریپت تانل انجام بدید
