### ISSUE TITLE
FATAL File Error: config file "config_name.json" could not be read

### ISSUE THREAD

**Issue by armanrzv** [radkesvat/WaterWall#104]
نسخه 1.25 واتروال.
 این ارور بعد از تست کردن چند تانل به وجود اومد. هروقت ./Waterwall رو میزنم اروری که توی تایتل گذاشتم رو نشون میده حتی برای کانفیگ‌هایی که قبلا تست کردم و کار میکردن ارور نمایش داده میشه.
 فایلی که ذکر شده رو باز میکنم و میبینم که خالی هستش. فایل nano config_name.json باید اصولا خالی باشه دیگه؟ پس چرا اصرار داره که نمیتونه بخونتش و نمیذاره واتروال ران شه.

**Comment by Asfia7** [comment]
فایل کانفیگی که داخل core.json ذکر شده با نام config_name.json هست
باید قسمت _name رو داخل core.json پاک کنید یا اینکه فایل config رو با نام config_name.json بسازید و تنظیمات تانل رو داخل اون پیاده کنید

**Comment by EbadiDev** [comment]
پیشنهاد میکنم داکیومنت رو حتما بخونید : https://radkesvat.github.io/WaterWall-Docs/

**Comment by Saleh-Mumtaz** [comment]
> نسخه 1.25 واتروال. این ارور بعد از تست کردن چند تانل به وجود اومد. هروقت ./Waterwall رو میزنم اروری که توی تایتل گذاشتم رو نشون میده حتی برای کانفیگ‌هایی که قبلا تست کردم و کار میکردن ارور نمایش داده میشه. فایلی که ذکر شده رو باز میکنم و میبینم که خالی هستش. فایل nano config_name.json باید اصولا خالی باشه دیگه؟ پس چرا اصرار داره که نمیتونه بخونتش و نمیذاره واتروال ران شه.

درود اول از همه ایشیو پین شده رو بخون، اموزش نصب اولیه، دوم داکیومنت برنامه رو بخون، که لینکش تو همون ایشیو هست
