### ISSUE TITLE
How to delete the entire Waterwall?

### ISSUE THREAD

**Issue by armanrzv** [radkesvat/WaterWall#105]
ممنون میشم دستور حذف کامل واتروال + تمام فایل‌های جیسون‌ش رو بگید. جایی پیداش نکردم.

**Comment by Saleh-Mumtaz** [comment]
> ممنون میشم دستور حذف کامل واتروال + تمام فایل‌های جیسون‌ش رو بگید. جایی پیداش نکردم.

باید دستی همه رو حذف کنید
