### ISSUE TITLE
اشکال در وصل شدن به سرور ایران

### ISSUE THREAD

**Issue by rezhacker** [radkesvat/WaterWall#106]
سلام. من برای تست روش تانل یک سرور مجازی ایران گرفتم. یک سرور خارج هم از قبل داشتم. برای نصب واتروال 1.25 از روش ریورس ریلیتی با halfduplex از روی راهنما در سرور ایران و خارج انجام دادم. جفت سرور ها هم ابونتو 20 هستن و آپدیت شدند. روی سرور خارج پنل x-ui علیرضا نصب هست. الان یک کانفیگ ساده vmess از نوع tcp زدم روش به راحتی کار کرد.
حالا مشکل من اینجاست که بعد از چند دقیقه دیگه نمیتونم به سرور ایران ssh بزنم. اصلا وصل نمیشه. v2ray وصل میشه کامل هم کار میکنه، سرور ایران هم پینگ میده ولی فقط نمیشه بهش ssh زد. سیستم عامل سرور رو که مجدد نصب میکنم درست میشه. ولی به محض اینکه واتروال رو کانفیگ و اجرا میکنم دوباره همین شکلی میشه. یک حالتی که انگار پورت ssh توی فایروال بسته شده باشه. در حالی که فایروال من کلا خاموشه.
ریموت نشدن به سرور چه ربطی میتونه داشته باشه به واتروال؟
واتروال رو هم به صورت سرویس اجرا کردم هم داخل tmux بازم فرقی نکرد.

**Comment by rezhacker** [comment]
با VNC که به سرور وصل میشم به محضی اینکه سرویس waterwall رو stop میکنم ریموت ssh درست میشه و میتونم وصل بشم!

**Comment by rezhacker** [comment]
به نظر میاد باید یه جایی توی کانفیگ سرور ایران وایت لیست تعریف بشه که پورت ssh رو باز کنه ولی پیدا نکردم چطوری.

**Comment by Saleh-Mumtaz** [comment]
دارید پورتی که تو رنج پورت واتروال هست رو استفاده میکنید، پورت ssh برگردونید به 22 و مراقب باشید رنج پورت واتروال با پورت ssh تداخل نداشته باشه
