### ISSUE TITLE
مشکل در استفاده از ipv6

### ISSUE THREAD

**Issue by AEydi** [radkesvat/WaterWall#107]
برای استفاده از waterwall مشکل داشتم برای همین اول خواستم پورت به پورت دوتا سرور رو به هم وصل کنم
در استفاده از ipv4 مشکلی نداشت ولی ورژن 6 برام کار نکرد
کانفیگ سرور ایران

```
{
    "name": "simple_port_to_port",
    "nodes": [
        {
            "name": "input",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": 2086,
                "nodelay": true
            },
            "next": "output"
        },
        {
            "name": "output",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "2a01:4f9:1e:b17d::1",
                "port": 4444
            }
        }
    ]
}
```

سرور خارج

```
{
    "name": "listen",
    "nodes": [
        {
            "name": "input",
            "type": "TcpListener",
            "settings": {
                "address": "::",
                "port": 4444,
                "nodelay": true
            },
            "next": "output"
        },
        {
            "name": "output",
            "type": "Connector",
            "settings": {
                "nodelay": true,
                "address": "127.0.0.1",
                "port": 2083
            }
        }
    ]
}
```

> 2024-07-07 12:03:17.540 DEBUG TcpListener: Accepted FD:e  [**.**.**.**:2086] <= [**.**.**.**:15560]
> 2024-07-07 12:03:24.924 WARN  connect timeout [[::]:0] <=> [[2a01:4f9:1e:b17d::1]:4444]
> 2024-07-07 12:03:24.924 DEBUG TcpConnector: received close for FD:d 
> 2024-07-07 12:03:24.924 DEBUG PreConnectClient: disconnected, unused: 0 active: 1

هر دو سرور ها ipv6 دارن ولی سرور ایران انگار در شبکه لوکال خودش آی پی خارج رو صدا میزنه

گفتم شاید باگ باشه از PreConnectClient استفاده کنم که با این کار گاها به سرور خارج وصل میشد

> 2024-07-07 11:54:16.516 DEBUG TcpListener: Accepted FD:1e  [[::]:2086] <= [[::ffff:**.**.**.**]:48710]
> 2024-07-07 11:54:16.624 WARN  connect timeout [[::]:0] <=> [[2a01:4f9:1e:b17d::1]:4444]
> 2024-07-07 11:54:16.624 DEBUG TcpConnector: received close for FD:a 
> 2024-07-07 11:54:16.624 DEBUG PreConnectClient: disconnected, unused: 0 active: 1
> 2024-07-07 11:54:16.805 DEBUG TcpConnector: connection succeed FD:1d [[2a10:ed:0:gf4:d5h1:4g3:7e:1]:39140] => [[2a01:4f9:1e:b17d::1]:4444]
> 2024-07-07 11:54:16.805 INFO  PreConnectClient: connected,    unused: 1 active: 1
> 2024-07-07 11:54:17.323 WARN  connect timeout [[::]:0] <=> [[2a01:4f9:1e:b17d::1]:4444]
> 2024-07-07 11:54:17.324 DEBUG TcpConnector: received close for FD:1a 
> 2024-07-07 11:54:17.324 DEBUG PreConnectClient: disconnected, unused: 1 active: 1
> 2024-07-07 11:54:18.123 WARN  connect timeout [[::]:0] <=> [[2a01:4f9:1e:b17d::1]:4444]
> 2024-07-07 11:54:18.123 DEBUG TcpConnector: received close for FD:1b

**Comment by Saleh-Mumtaz** [comment]
https://radkesvat.github.io/WaterWall-Docs/FreeBind
ببینید با خوندن این داکیومنت مشکلتون حل میشه

**Comment by AEydi** [comment]
نه
مشکل از اینجاست
WARN connect timeout [[::]:0] <=> [[2a01:4f9:1e:b17d::1]:4444]
شاید مهندس که کدش رو نوشتن بدونن مشکل از کجا میاد
مگر نه با سرچ کردن خودم چیزی پیدا نکردم

**Comment by Saleh-Mumtaz** [comment]
احتمالا استفاده از ایپی ۶ در حال حاضر فقط روی حالت فری بایند که داکیومنتش گذاشته شده قابل استفاده هست، همچنین محدودیت دیتاسنتر های مختلف روی ایپی ۶ رو هم باید در نظر گرفت.
