### ISSUE TITLE
مشکل ترافیک رو روش reverse tls grpc

### ISSUE THREAD

**Issue by Mostafaiii** [radkesvat/WaterWall#108]
سلام
خسته نباشید
روش Cdn Tunnel رو زدم
 تقریبا اوکی هست ولی یه تست سرع اینترنت انجام دادم خب موقع تست cpu سرور خارج میچسبه به اخر 
این تست رو مستقیم سرور خارج تست بزنی شاید در حد 200 مگابایت حجم میفته ولی
ولی روش reverse tls grpc
رو پنل خارج موقع تست سرعت ک میندازه بالای 700 مگابایت هست ولی تست انجام میدم رو نت ثابت هست ک سرعتش از 12 مگ بیشتر نمیره
حجم هم ک میندازه تو یه تست بالای 10 گیگ میفته رو پنل  موقه تست سرعت کانفیگ رو گوشی

اول فک کردم شاید مشکل از پنل باشه دیگ هم تست کردم مشکل وجود داشت

**Comment by Mostafaiii** [comment]
سات موقع تست گرفتم هم از سرور ایران و سرور خارج 
![Capturssse](https://github.com/radkesvat/WaterWall/assets/154089787/648ad831-5b4d-47f1-bc4c-59d3e758c9dc)
![qaq](https://github.com/radkesvat/WaterWall/assets/154089787/f02a5bf3-bdea-4393-a4b8-faeb1a7db118)

**Comment by Mostafaiii** [comment]
![Capture](https://github.com/radkesvat/WaterWall/assets/154089787/169a243e-0fc4-46ad-8edf-09a5f7fdf386)
![Capture2](https://github.com/radkesvat/WaterWall/assets/154089787/6f2a02fa-3397-4dc2-93dc-d5d2ecb74398)
![Capture3](https://github.com/radkesvat/WaterWall/assets/154089787/a8651902-ee13-496d-8dcf-6aae48c89698)
![photo_2024-07-07_21-59-11](https://github.com/radkesvat/WaterWall/assets/154089787/5951b2bd-6146-48f2-8c22-20595da35c29)

**Comment by radkesvat** [comment]
رو سی دی ان این مشکل هست به خاطر نبود Flow control 

به زودی فیکسش میکنم

**Comment by persian-michael-scott** [comment]
> هنگام تست شات موقع تست گرفتم همزمان از سرور ایران و سرور خارج سبزه سرور ایران هست رو سرور ایران حجم درست هست
> 
> ![Capturssse](https://private-user-images.githubusercontent.com/154089787/346355320-648ad831-5b4d-47f1-bc4c-59d3e758c9dc.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDAxOTgsIm5iZiI6MTcyMDQzOTg5OCwicGF0aCI6Ii8xNTQwODk3ODcvMzQ2MzU1MzIwLTY0OGFkODMxLTViNGQtNDdmMS1iYzRjLTU5ZDNlNzU4YzlkYy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMTU4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTU1MWZlNTgyODA0YTY3ZDExZWY4NTE4NmZlMWQ2MWQ4OTk1NzI0M2VjMGE3ODIzMGYzZGE3NWViNTZlZTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vpRWrHf50ibQH3p3CeSgYTsKNlUWcZB2JdvfgsQ13NQ) ![qaq](https://private-user-images.githubusercontent.com/154089787/346355325-f02a5bf3-bdea-4393-a4b8-faeb1a7db118.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDAxOTgsIm5iZiI6MTcyMDQzOTg5OCwicGF0aCI6Ii8xNTQwODk3ODcvMzQ2MzU1MzI1LWYwMmE1YmYzLWJkZWEtNDM5My1hNGI4LWZhZWIxYTdkYjExOC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMTU4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2I0YzYzNjlkZWU3ZWNkN2IyMDYxZDA1MmY0YzJhYTExOTk5MzZlN2M5OTUyMGE3MTVkMWE3NWRkNTVhZjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TC55knqmM8wLWP4xVG4i91z4nULFf5zD2l16PSibt1M)

منم تست کردم روی نسخه 1.27 اصلا کانکشن برقرار نشد. ولی روی نسخه 1.25 کانکشن برقرار میشه اما سرعت دانلود بسیار پایین هست در حد 3 مگابیت اما آپلود خوبه . در نسخه 1.25 مصرف cpu نامعقولی ندیدم.( با کانفیگ vmess http در نسخه 1.25 اتصالم برقرار نشد اما با تانل های دیگه این کانفیگ مشکلی نداره، با کانفیگ reality این تست هارو کردم)

**Comment by Saleh-Mumtaz** [comment]
درود 
با نسخه جدید تست کنید و در صورت بروز دوباره مشکل ایشیو جدید باز کنید.
