### ISSUE TITLE
ایران اکسس شدن تمام سرورها با کانفیگ waterwall

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#109]
درود وقت بخیر . @radkesvat

کانفیگ reality reverse رو روی چندین سرور از دیتاسنترهای مختلف از جمله امین ، پیشگامان و آسیاتک زده بودیم . با ترافیک های مختلف از کم تا زیاد . همه سرورها به جز یکی ایران اکسس شد امشب . ماکس و halfduplex بود توی کانفیگ . کانفیگ کاربرا هم vless tcp با هدر بود .

پس این تانل هم شناسایی میشه ؟ نمیشه هیچ کاریش کرد؟  چی بزنیم اکسس نشیم ؟ ترافیک زیاد هست . روزی یه ترا

**Comment by radkesvat** [comment]
مواردی که به ذهن من میرسه:

اول اینکه vless لخت به هیچ وجه استفاده نکنید ؛ اینو بار ها گفتم و  حتما با tls استفاده کنید یا اینکه vmess استفاده کنید

نکته دوم اینکه اگه اینقدر ترافیک دارید بهتره ریورس سی دی ان استفاده کنید ؛ من تا جایی که علمشو داشتم تشخیصم اینه که روش ها قابل شناسایی نیست و فیلترینگ ایران هم اصلا دنبال راه های سخت رفتن نیست ؛ ممکنه فقط به خاطر اینکه ترافیک زیادی به یه ایپی خارج که از کلود هم نیست بسته باشه

مقدار concurrency هم داخل نود http2 client زیاد کنید بزارید حداقل 128 یا 256 وقتی کاربر خیلی زیاد هست رو یه سرور 

من خودم و یه عده کمی که میشناسمشون از نزدیک و براشون تونل کردم (فعلا) ایران اکسس نشیدم ؛ همچنین Sni هم یه سایت رندوم ایرانی بزنید اگه روش reality reverse هست ؛‌صرفا اون دیفالتی که من گذاشتم رو استفاده نکنید.

**Comment by Saleh-Mumtaz** [comment]
ریلیتی ریورس رو یا هر تانلی رو، به این صورت اجرا  کنید که کاربرها به ۴۴۳ ایران وصل بشه و خارج هم به ۴۴۳ ایران وصل بشه.

**Comment by Saleh-Mumtaz** [comment]
ببینید شما همه چی رو روی ۴۴۳ اجرا کنید، خیلی اهمیت دارد

**Comment by MD1373** [comment]
ممنون از شما بابت این پروژه قدرتمندی که استارتشو زدید ، جسارتا در مورد روشی که برای جلوگیری از ایران اکسس شدن فرمودید، منم ترافیک سرورام بالاس و reality reverse + half dublex رو هم تست کردم ولی متاسفانه برای من جواب نداد ، چون قطعی داشتم .
 این روش reverse cdn که فرمودید فقط پورت تانل رو بیایم بزاربم روی ۴۴۳ بزاریم؟ چون پورت مربوط به کانفیگ هام که دست کاربره از ۱۰۰۰ شروع میشه و هر سرور جدیدی که تانل میزنم میشه عدد بعدیش

و اینکه متاسفانه کانفیگام vless tcp header هست و الان دیگه نمیتونم عوضشون کنم

متاسفانه هر هفته هم تمامی سرورام رو ایران اکسس میکنن

توی روش waterwall هم reverse cdn رو ندیدم ، ایا برای استفاده ازین روش نیازه که از cdn استفاده کنم؟

**Comment by Saleh-Mumtaz** [comment]
از اسکریپت استفاده کنید روش سی دی ان ریورس رو داره.
