### ISSUE TITLE
Transport endpoint is not connected:107

### ISSUE THREAD

**Issue by amirmozafar** [radkesvat/WaterWall#11]
سلام
روی حالت ریورس مالتی پورت این خطا رو میگیرم اما هرکار کردم متوجه نشدم مشکل از کجاست

WARN  connfd=8 connect error: Transport endpoint is not connected:107 [nio.c:118:nio_connect]
 DEBUG TcpConnector: received close for FD:8

روی این حالت توی کانفیگ سمت خارج، هر دو جایی که باید آدرس دومین وارد کنیم، آدرس دومین خودمونو وارد می کنیم دیگه درسته؟؟؟

**Comment by radkesvat** [comment]
با نسخه جدید تست کنید لطفا
