### ISSUE TITLE
 عدم اجرای تانل ریورس tls

### ISSUE THREAD

**Issue by NIKA5050** [radkesvat/WaterWall#110]
با سلام با روش ریورس و Tls و Http2  روی سرور داخل سرت گرفته میشود و داخل دستورات جایگذاری و ریموت به خارج میشود.. روی خارج هم همین مراحل تکرار و آدرس هاست دامنه جایگذاری و ریموت به ایران میشود ولی در نهایت پنل بالا نمیاید .. در حالی هستش که روش دیگر جواب میدهد الا این روش کجای کار ایراد دارد ؟

**Comment by Saleh-Mumtaz** [comment]
فایل های کانفیگ و کور رو بفرستید لطفا

**Comment by NIKA5050** [comment]
> فایل های کانفیگ و کور رو بفرستید لطفا

core:
{
    "log": {
        "path": "log/",
        "core": {
            "loglevel": "DEBUG",
            "file": "core.log",
            "console": true
        },
        "network": {
            "loglevel": "DEBUG",
            "file": "network.log",
            "console": true
        },
        "dns": {
            "loglevel": "SILENT",
            "file": "dns.log",
            "console": false
        }
    },
    "dns": {},
    "misc": {
        "workers": 0,
        "ram-profile": "server",
        "libs-path": "libs/"
    },
    "configs": [
        "config.json"
    ]
}



iran:

{
    "name": "reverse_tls_h2_multi_iran",
    "nodes": [
        {
            "name": "inbound_users",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": [23,65535],
                "nodelay": true
            },
            "next": "header"
        },
        {
            "name": "header",
            "type": "HeaderClient",
            "settings": {
                "data": "src_context->port"
            },
            "next": "bridge2"
        },
        {
            "name": "bridge2",
            "type": "Bridge",
            "settings": {
                "pair": "bridge1"
            }
        },
        {
            "name": "bridge1",
            "type": "Bridge",
            "settings": {
                "pair": "bridge2"
            }
        },
        {
            "name": "reverse_server",
            "type": "ReverseServer",
            "settings": {},
            "next": "bridge1"
        },
        {
            "name": "pbserver",
            "type": "ProtoBufServer",
            "settings": {},
            "next": "reverse_server"
        },
        {
            "name": "h2server",
            "type": "Http2Server",
            "settings": {},
            "next": "pbserver"
        },
        {
            "name": "sslserver",
            "type": "OpenSSLServer",
            "settings": {
                "cert-file": "/root/Waterwall/cert/fullchain.pem",
                "key-file": "/root/Waterwall/cert/privkey.pem",
                "alpns": [
                    {
                        "value": "h2",
                        "next": "node->next"
                    },
                    {
                        "value": "http/1.1",
                        "next": "node->next"
                    }
                ],
                "fallbackintencedelay": 0
            },
            "next": "h2server"
        },
        {
            "name": "inbound_server_kharej",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": 443,
                "nodelay": true,
                "whitelist": [
                    "IP.KHAREJ/32"
                ]
            },
            "next": "sslserver"
        }
    ]
}


KHAREJ:

{
    "name": "reverse_tls_h2_multi_kharej",
    "nodes": [
        {
            "name": "core_outbound",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "127.0.0.1",
                "port": "dest_context->port"
            }
        },
        {
            "name": "header",
            "type": "HeaderServer",
            "settings": {
                "override": "dest_context->port"
            },
            "next": "core_outbound"
        },
        {
            "name": "bridge1",
            "type": "Bridge",
            "settings": {
                "pair": "bridge2"
            },
            "next": "header"
        },
        {
            "name": "bridge2",
            "type": "Bridge",
            "settings": {
                "pair": "bridge1"
            },
            "next": "reverse_client"
        },
        {
            "name": "reverse_client",
            "type": "ReverseClient",
            "settings": {
                "minimum-unused": 16
            },
            "next": "pbclient"
        },
        {
            "name": "pbclient",
            "type": "ProtoBufClient",
            "settings": {},
            "next": "h2client"
        },
        {
            "name": "h2client",
            "type": "Http2Client",
            "settings": {
                "host": "v11.mydomain.in",
                "port": 443,
                "path": "/",
                "content-type": "application/grpc"
            },
            "next": "sslclient"
        },
        {
            "name": "sslclient",
            "type": "OpenSSLClient",
            "settings": {
                "sni": "v11.mydomain.in",
                "verify": true,
                "alpn": "h2"
            },
            "next": "iran_outbound"
        },
        {
            "name": "iran_outbound",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "IP.IRAN",
                "port": 443
            }
        }
    ]
}

**Comment by Saleh-Mumtaz** [comment]
```
bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/WaterWall-Docs/main/install.sh)
```
از این اسکریپت برای ران کردن استفاده کنید ببینید مشکل حل میشه یا نه

**Comment by NIKA5050** [comment]
> ```
> bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/WaterWall-Docs/main/install.sh)
> ```
> 
> از این اسکریپت برای ران کردن استفاده کنید ببینید مشکل حل میشه یا نه

خیر تست شد با اینم کار نکرد .. 
البته نکته هم بگم خدمتتون این اسکریپت 2 و 3 هم همین مشکل داره خودتون تست کنید.. مابقی هم از جمله شماره 6 مثلا پنل بالا میاد ولی بعد اتصال کلاینت پینگ نداری ..! شما خودت تست کردی بزرگوار ؟!

**Comment by Saleh-Mumtaz** [comment]
مشکل اینه که من خودم بدون اسکریپت تمام روش های داکیومنت رو اجرا کردم کار کرد، اینکه بقیه اجرا میکنن و کار نمیکنه برام تعجب بر انگیزه

**Comment by Saleh-Mumtaz** [comment]
به احتمال زیاد اتصال ایپی خارج به سرور داخل با این روش محدود شده.
