### ISSUE TITLE
crash after 1 minute on centos 8 stream inside docker (ubuntu)

### ISSUE THREAD

**Issue by netsupcloud** [radkesvat/WaterWall#111]
سلام

config_reverse_tls_grpc_multiport_hd_kharej

این کانفیگ رو بصورت cdn که اصلا درست کار نمیکنه و بصورت غیر cdn کار میکنه ولی هر یک دقیقه ریستارت میکنه تو ورژن 1.25 تو 1.27 هم که هر 2 ثانیه انگار ریستارت میکنه

چون مشکل glibc داشت (glibc 2.29 not found) تو centos 8 stream مجبور شدم تو داکر ubuntu ران کنمش ولی مشکل ریستارتش فکر نمیکنم بخاطر داکر باشه تعداد ورکر ها هم 4 و 32 هستن هر تغییری هم میدم دقیقا سر یک دقیقه ریستارت میکنه لاگ کنسول هم چیزی نمیده دقیقا وسط کار این اتفاق میوفته

**Comment by Saleh-Mumtaz** [comment]
در همین مدت ران بودن برنامه یک لاگی مینویسه لطفا اون رو ارسال کنید. ایشیو خالی باز کردن فقط باعث سردرگمی دولوپر میشه.
