### ISSUE TITLE
مشکل افت سرعت در halfduplex tunnel 

### ISSUE THREAD

**Issue by ehsankeyhan** [radkesvat/WaterWall#113]
سلام من از  روش halfduplex tunnel حالت مولتی پورت استفاده کردم ولی گاها افت سرعت روش دارم مثلا اسپید تست رو حالت عدی رو ۶۰ مگ ولی بعد از اتصال میاد رو ۶،۷ مگ ! ورکر هم ۴ و ۳۲ گذاشتم ! رو هر سرور هم فقط ۵۰ تا یوزر !

**Comment by janahnovin** [comment]
من هم این مشکل دارم قطعی لحظه ای هم داره من اول فکر کردم از سرور هست روی چند تا سرور مختلف تست کردم باز مشکل داره استیبل نیست

**Comment by ehsankeyhan** [comment]
من قطعی احساس نکردم ولی این مشکل رو دارم خیلی عالیه‌ ولی یهو یه تایمی پینگش میره بالا

**Comment by ehsankeyhan** [comment]
الان قطعی هم پیدا کردم قطع میشه بعد خودش وصل میشه!

**Comment by Kup1ng** [comment]
بله منم این مشکل را دارم

**Comment by Vatani78** [comment]
منم این مشکل رو تو ریورس ها دارم
حتی تو RTT هم این مشکل بود ولی تنها ورژن بدون مشکل RTT نسخه 5.4 بود که عالیه این ورژنش
امیدوارم نسخه 5.4 رو دقیقا بیاره رو واتروال

**Comment by Izaanaami** [comment]
منم مشکل قطعی لحظه ای دارم

**Comment by Saleh-Mumtaz** [comment]
درحال رفع مشکل هستند. دوستان دقت کنید میخواهید ایشیو باز کنید لطفا فایل لاگ فرستادن فراموش نشود.

**Comment by Kup1ng** [comment]
> درحال رفع مشکل هستند. دوستان دقت کنید میخواهید ایشیو باز کنید لطفا فایل لاگ فرستادن فراموش نشود.

لاگ را میتونم ارسال کنم اما اصلا کجاشو ارسال بکنم چون خیلی طولانیه و تو لاگ هیچ خطایی وجود نداره

**Comment by Saleh-Mumtaz** [comment]
خود فایل رو ضمیمه کنید

**Comment by Saleh-Mumtaz** [comment]
دیگه دولوپر خودش میدونه تو لاگ دنبال چیا بگرده

**Comment by ehsankeyhan** [comment]
[Uploading network.20240710-iran.log…]()
من لاگ سرور خارج و ایران رو گذاشتم!

**Comment by ehsankeyhan** [comment]
[network.20240710-iran.log](https://github.com/user-attachments/files/16169206/network.20240710-iran.log)
[network.20240710-kharej.log](https://github.com/user-attachments/files/16169209/network.20240710-kharej.log)

من لاگ سرور خارج و ایران رو گذاشتم!

**Comment by Izaanaami** [comment]
مشکل به نظر از زیاد کردن تعداد worker هاست. توی سرور خارج و ایران روی صفر گذاشتمشون دوباره و به نظر میاد مشکل حل شده باشه

**Comment by ehsankeyhan** [comment]
کلا از دیروز احساس میکنم اختلال روش کم شده! باز شمام 

> مشکل به نظر از زیاد کردن تعداد worker هاست. توی سرور خارج و ایران روی صفر گذاشتمشون دوباره و به نظر میاد مشکل حل شده باشه

باز فکر میکنم از دیروز اختلال کم شده شمام رو ورکر صفر تست کنید خبر بدید!

**Comment by janahnovin** [comment]
مال من همچنان قطعی لحظه ای داره رو 4 تا سرور ایران مختلف و سرور خارج هم هر 4 تا از یه دیتاسنتره  در صورتی که رو تانل دیگه بدون قطعی کار میکنه .خوبی این روش سرورام هیچکدوم ایران اکسس نشدن هر روش دیگه رفتم هم سرور ایران هم خارج به فنا رفته

**Comment by Kup1ng** [comment]
[network.20240711.log](https://github.com/user-attachments/files/16192592/network.20240711.log)
[network.20240712.log](https://github.com/user-attachments/files/16192593/network.20240712.log)

لاگ دو سرور ایران و خارج

**Comment by Saleh-Mumtaz** [comment]
درود با نسخه جدید امتحان کنید و اگر مشکل پابرجا بود ایشیو رو باز کنید

**Comment by Izaanaami** [comment]
مشکل همچنان پابرجاست. هی قطع میشه اتصال. من همه چی رو تست کردم درست نشد. تا اینکه کلا تانل رو از واتروال سوییچ کردم رو یه تانل دیگه و مشکل حل شد
