### ISSUE TITLE
halfduplex  مشکل پینگ و سرعت

### ISSUE THREAD

**Issue by mkhco** [radkesvat/WaterWall#115]
درود

با روش halfduplex  وقتی یک یا دوتا کاربر استفاده میکنن اوکیه و پینگ و سرعت خوبی میده ولی وقتی کاربرها زیاد بشن پینگ یکی در میون تایم آت هست یا وقتی پینگ میده مقدار بالایی میده و سرعت هم با کاربر بالا پایین هست

**Comment by radkesvat** [comment]
سلام ؛ preconnect هم اضافه کنید ببینید بهتر میشه؟ همچنین نسخه آخر رو تست کنید

**Comment by mkhco** [comment]
ممنونم ، preconnect  رو اضافه کردم بهتر شد ، نسخه اخر بود تست قبلی

داخل نود reverse_client مقدار minimum-unused روی 16 ست شده ، میتونیم کمتر یا بیشتر بزاریم برای بهبود کیفیت ؟ یا یه توضیحی میدید در موردش

**Comment by radkesvat** [comment]
بسته به تعداد کاربر میتونید بیشتر هم بزارید؛‌ این تعداد کانکشن هایی هستن که پیش از اتصال کاربر زده میشه 

نسخه اخر باگ داشت پاک شد دوباره قرار داده شد خیلی زود بعد از اولین انتشار ؛ بهتره یه بار پاک کنید دوباره نصب کنید

**Comment by mkhco** [comment]
هنوز مشکل کرش بعد از یک ساعت هست ، با کاربر تعداد بالا

**Comment by radkesvat** [comment]
کرش؟ برا من هیچوقت کرش نکرده تا الان ؛ چه اروری بهتون میده؟ فایل های کانفیگتون رو بفرستید لطفا

**Comment by netsupcloud** [comment]
> بسته به تعداد کاربر میتونید بیشتر هم بزارید؛‌ این تعداد کانکشن هایی هستن که پیش از اتصال کاربر زده میشه
> 
> نسخه اخر باگ داشت پاک شد دوباره قرار داده شد خیلی زود بعد از اولین انتشار ؛ بهتره یه بار پاک کنید دوباره نصب کنید



یعنی اگر concurrency روی 64 باشه و  minimum-unused رو 64 باشه کلا این کانکشن ها داخل یه کانکشن multiplex  میشن ؟

**Comment by radkesvat** [comment]
بله ولی خوب ترتیب نود ها مهمه ، دقت کنید کدوم اوله کدوم دوم

**Comment by ehsankeyhan** [comment]
من preconnect رو بعد از header به سرور ایران اضافه کردم با آپدیت جدید بعد چند ساعت سرور ایران قطع میشه دوباره باید ران کنم

**Comment by radkesvat** [comment]
قطع میشه یعنی چطور؟ واتروال بسته میشه؟

وقتی قطع شد لاگ فایل شبکه رو ارسال کنید لطفا 

در پوشه log کنار خود واتروال هست

log/network.log
