### ISSUE TITLE
version `GLIBC_2.38' not found 

### ISSUE THREAD

**Issue by Ahmad-f79** [radkesvat/WaterWall#117]
سلام مهندس
آقا اول بذار بگم گل کاشتی واقعا
پروژه جدیدت خیییلی خفنه و پتانسلیش بی‌نظیره بین همه تانل‌هایی که دیدم یا استفاده کردم

مشکل اینه که نسخه جدید روی arm64 این ارورو میده
/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./Waterwall) 

ابونتو 22 آپدیته سرور هتزنر
ی مقدار تلاش کردم دستی glib جدید رو بزیم ولی دیدم داره ترسناک میشه کامند‌ها بیخیال شدم

فقط من با reveres reality half duplex هم مشکل دارم 
هم سرعتش کمه هم نمی‌تونم روی ipv6 رانش کنم
لیسن رو روی :: هم گذاشتم نشد
ممنون میشم فرصت شد با free bind یا v6 رو هم توی دکیومنت بذارید که من از رلیز های اول rtt طرفدار این reveres realityم

**Comment by radkesvat** [comment]
دوباره نصب کنید درست شد این مشکل ؛ فایل توی ریلیز اپدیت شد

**Comment by Ahmad-f79** [comment]
مهندس فایل Waterwall-linux-arm64.zip نیست
بقیه هم مال چهار ساعت پیشن
فایل جدید نمی‌بینم

**Comment by radkesvat** [comment]
عجیبه... دوباره ادش میکنم
