### ISSUE TITLE
مشکل نسخه 1.28 متد cdn

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#121]
درود وقت بخیر @radkesvat 

از نسخه 1.25 زمانی که به 1.28 آپدیت کردم ، سرورهایی که تانل cdn داشتن دچار مشکل شدن . تلگرام هر 2-3 ثانیه یکبار connecting میشه و قطعی و وصلی زیاد داره . زمانی که از نسخه 1.28 داون گرید کردم به 1.25 ، مشکل رفع شد . به نظر میرسه نسخه جدید روی متد cdn مشکل داره . لطفا شما هم روی تلگرام این موضوع رو چک کنید چون connecting میره ، قطع و وصلی های جزیی رو راحت متوجه میشید . 

البته نسخه 1.28 مصرف منابع رو خیلی کمتر کرده بود و امیدوارم که بتونید فقط مشکل cdn رو رفع کنید که ما مصرف منابع کم رو بتونیم حفظ کنیم . تشکر

**Comment by radkesvat** [comment]
مطمعنید؟ من تستش کردم اوکی بود قبل انتشار منتهی کاربرای خودم چون رو این روش نیستن خیلی تستش طولانی نبود؛ نکته مهم اینه که هردوتا سرور به نسخه 1.28 اپدیت بشن هم ایران و هم خارج ؛ بعد تست کنید ببینید بازم مشکل هست یا نه . ممنون

**Comment by lostsoul6** [comment]
بله مهندس جان @radkesvat 

بنده روی 5 سرور این رو داشتم که هم ایران و هم خارج 1.25 بود و مشکلی نداشت . وقتی 1.28 زدیم این مشکل رخ داد و همه کاربران هم گزارش دادن . سرورها روی دیتاسنترهای مختلفی بود . بعد که مشکل گزارش دادن مجدد 1.25 رو زدیم و اوکی شد . لطفا بررسی کنید قطعا مشکلی هست چون روی 1.25 اوکی هست این قضیه میشه نتیجه گرفت مشکل کانفیگ یا دیتاسنتر یا سرور خارج نیست . تشکر

**Comment by radkesvat** [comment]
باشه تستش میکنم دوباره حتما ببینم مشکلی باشه رفع میشه

**Comment by hatinati2** [comment]
با اسکریپت زیر تست کنید

bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/WaterWall-Docs/main/install.sh)
