### ISSUE TITLE
تاخیر دلخواه

### ISSUE THREAD

**Issue by netsupcloud** [radkesvat/WaterWall#123]
سلام مهندس ممکنه تاخیر دستی برای کانکشن مثلا 100 یا 200ms یا مقدار دلخواه ایجاد کرد؟ کاربردش هم جایی هست که برنامه های کلاینت بر اساس تاخیر کانکشن انتخاب میکنن و ما میخوام با ایجاد تاخیر کانکشنی که از این تانل استفاده میکنه رو از اولویت خارج کنیم چون به هر حال هزینه داره تانل زدن به سرور های ایران

@radkesvat

**Comment by radkesvat** [comment]
والا تمام تلاش تا امروز این بود که حتی شده یه میلی ثانیه از این تاخیر کم بشه 🫠

اره میشه ایجاد کرد باید یه نود trojanauthserver بزارید داخل زنجیر ولی خود کانکشن باید از فالبکش رد بشه و پارامتر fallback-intense-delay داره که میتونید هر چند میلی ثانیه تاخیر میخواید ست کنید.

یه راه دیگه اشم اینه که کانکشن هارو یه دور یا دو دور به لوپ بک وصل کنید و ازش دریافت کنید اینجوری تاخیر ایجاد میشه ، برای هردور لوپ بک شاید ۵ تا ۲۰ میلی ثانیه بشه...

**Comment by netsupcloud** [comment]
> والا تمام تلاش تا امروز این بود که حتی شده یه میلی ثانیه از این تاخیر کم بشه 🫠
> 
> اره میشه ایجاد کرد باید یه نود trojanauthserver بزارید داخل زنجیر ولی خود کانکشن باید از فالبکش رد بشه و پارامتر fallback-intense-delay داره که میتونید هر چند میلی ثانیه تاخیر میخواید ست کنید.
> 
> یه راه دیگه اشم اینه که کانکشن هارو یه دور یا دو دور به لوپ بک وصل کنید و ازش دریافت کنید اینجوری تاخیر ایجاد میشه ، برای هردور لوپ بک شاید ۵ تا ۲۰ میلی ثانیه بشه...

البته اگر وبسوکت رو هم اضافه کنید خودش تاخیر ذاتی داره نسبت به grpc. مهندس اینکار واسه شما خیلی ساده تر از منه که خیلی وقته به c کد ننوشتم مخصوصا که برنامه نویسی شبکه انجام ندادم نهایتا کد اپلود به اف تی پی نوشتم و مخفی کردنش از انتی ویروسا
