### ISSUE TITLE
گرفتن پهنای باند

### ISSUE THREAD

**Issue by neon-bartmoss** [radkesvat/WaterWall#124]
سلام

من حتی وقتی پنل رو از کار میندازم و هیچ کاربری متصل نیست هم حدود 2 مگ پهنای باند اشغال شده میبینم در سرور 
ریورس ریلیتی با mux هست
![bandicam 2024-07-13 22-41-22-610](https://github.com/user-attachments/assets/8196bad1-9fd8-4073-8a0e-45e1337be713)
![bandicam 2024-07-13 22-42-01-253](https://github.com/user-attachments/assets/ec5fd5e4-4102-4d5f-bb48-2e6fd82b13bc)

**Comment by netsupcloud** [comment]
@radkesvat 

حرف ایشون رو منم تایید میکنم مهندس وقتی تعداد ورکر سمت سرور رو افزایش میدم مثلا میذارم رو 256 دریافت ورودی میره رو 30 مگابایت دانلود و اپلود هم حدود 7 مگابایت افرایش پیدا میکنه ولی فقط سمت خود سروره و رو سرورهای ایرانی تغییری به اون شدت مشاهده نمیشه

**Comment by radkesvat** [comment]
بستگی به روش داره ؛ البته ۲ مگ زیاده ؛ نمیدونم ۲ مگ برای چند لحظه میمونه یا بیشتر 

در بیشتر روش ها مثلا ریورس ؛ واتروال روی سرور خارج همیشه تلاش میکنه کانکشن پیش از کاربر بزنه و همین یه پهنای باند خیلی ریزی رو باید نشون بده که طبیعیه ؛ همچنین هر کانکشن اگه بیشتر از مثلا ۵۰ ثانیه ازش استفاده نشه ؛ کلوز میشه و دوباره زده میشه

یعنی یه پهنای باند خیلی کم و کلیوبایتی اگه باشه که خوب طبیعیه ولی اینکه ۲ مگ باشه ؛ وقتی پنل خاموش میکنید نباید بیشتر از چند ثانیه اینجوری باشه و باید کاهش پیدا کنه به کیلو بایت و اونم لحظه ای

**Comment by netsupcloud** [comment]
> بستگی به روش داره ؛ البته ۲ مگ زیاده ؛ نمیدونم ۲ مگ برای چند لحظه میمونه یا بیشتر
> 
> در بیشتر روش ها مثلا ریورس ؛ واتروال روی سرور خارج همیشه تلاش میکنه کانکشن پیش از کاربر بزنه و همین یه پهنای باند خیلی ریزی رو باید نشون بده که طبیعیه ؛ همچنین هر کانکشن اگه بیشتر از مثلا ۵۰ ثانیه ازش استفاده نشه ؛ کلوز میشه و دوباره زده میشه
> 
> یعنی یه پهنای باند خیلی کم و کلیوبایتی اگه باشه که خوب طبیعیه ولی اینکه ۲ مگ باشه ؛ وقتی پنل خاموش میکنید نباید بیشتر از چند ثانیه اینجوری باشه و باید کاهش پیدا کنه به کیلو بایت و اونم لحظه ای

پس در حالت عادی سرور با سرعت 5مگ ارسال و دریافت داره کار میکنه
ولی وقتی واتروال رو روشن میکنم minimum-unused ضربدر concurrent میشه و برای همین دریافت 30مگابات بر ثانیه زیاد میشه مثلا 16*256 میشه 4096 و هر کانکشن هم به حرف شما کیلوبایتی بگیره مثلا 10 کیلوبایت میشه 40 مگابایت برثانیه که بنظرم این هم باید مدیریت بشه توسط واتروال چون خودش واسه فیلترینگ ابیوز حساب میشه

**Comment by netsupcloud** [comment]
> بستگی به روش داره ؛ البته ۲ مگ زیاده ؛ نمیدونم ۲ مگ برای چند لحظه میمونه یا بیشتر
> 
> در بیشتر روش ها مثلا ریورس ؛ واتروال روی سرور خارج همیشه تلاش میکنه کانکشن پیش از کاربر بزنه و همین یه پهنای باند خیلی ریزی رو باید نشون بده که طبیعیه ؛ همچنین هر کانکشن اگه بیشتر از مثلا ۵۰ ثانیه ازش استفاده نشه ؛ کلوز میشه و دوباره زده میشه
> 
> یعنی یه پهنای باند خیلی کم و کلیوبایتی اگه باشه که خوب طبیعیه ولی اینکه ۲ مگ باشه ؛ وقتی پنل خاموش میکنید نباید بیشتر از چند ثانیه اینجوری باشه و باید کاهش پیدا کنه به کیلو بایت و اونم لحظه ای

پس در حالت عادی سرور با سرعت 5مگ ارسال و دریافت داره کار میکنه
ولی وقتی واتروال رو روشن میکنم minimum-unused ضربدر workers میشه و برای همین دریافت 30مگابات بر ثانیه زیاد میشه مثلا 16*256 میشه 4096 و هر کانکشن هم به حرف شما کیلوبایتی بگیره مثلا 10 کیلوبایت میشه 40 مگابایت برثانیه که بنظرم این هم باید مدیریت بشه توسط واتروال چون خودش واسه فیلترینگ ابیوز حساب میشه
