### ISSUE TITLE
قابلیت اجرا با Nginx

### ISSUE THREAD

**Issue by Alireza78na** [radkesvat/WaterWall#125]
سلام و خسته نباشید
ایده ای که به ذهنم رسیده اینه که این تانل پشت Nginx و به صورت reverse proxy اجرا بشه.
خوبیش اینه که رفتار سرور خیلی شبیه به وبسایت معمولی میشه ( با راه اندازی سایت یا ریدایرکت ) و به وطور کلی فکر میکنم امنبیتش هم بالاتر میره.
ابته یادمه قبلا گفتید که خود Waterwall این آپشن رو داره که درخواست های غیزمجاز رو به سمت SNI هدایت کنه ، ولی فک میکنم اگه از طریق Nginx و ... باشه خیلی بهتر میشه.
البته با این حالت دیگه مالتی پورت نمیشه استفاده کرد.

**Comment by radkesvat** [comment]
سلام ؛ واتروال با الهام از nginx نوشته شده ؛ ۹۰ درصد چیز ها دقیقا یکسان هستند و قابل تشخیص نیست ؛ هرجفتشون با openssl کار میکنن

اما ؛ نود opensslserver امکان گرفتن فالبک برای تولید error message مناسب داره که ؛ به یه جایی که nginx هست وصلش میکنید ؛ توی تروجان هم این مثالش زده شده و استفاده شده؛ اینجوری اگه واتروال تشخیص بده دیتا رو میده به خود nginx و جوابو از خودش میگیره و میفرسته به کاربر ؛ وقتی که gfw بخواد تشخیص بده و یه سری حملات استفاده کنه و پاسخ رو برسی کنه

**Comment by Alireza78na** [comment]
ممنون از توضیحاتتون.
آیا این اتفاق با کانفیک reverse reality grpc هم اتفاق میوفته؟
چون از نود opensslserver  استفاده نمیکنه ( که خب طبیعی هم هست )

**Comment by radkesvat** [comment]
وقتی از ریلیتی استفاده میکنید کانکشن با خود sni که زدید هند شیک میکنه ؛ اگه اون سایتی که زدید رو nginx باشه پس هند شیک هم مثل nginx هست ؛ اگه یه وب سرور دیگه باشه که خوب همونی که هست میشه و این بهترین حالت ممکن هست و فایروال هیچ راهی نداره که تمایز قایل بشه بین این هند شیک و هند شیک کاربر عادی چون در طول هند شیک اتصال تونل شده به Sni و با خود اون هند شیک انجام میشه

**Comment by NIKA5050** [comment]
> وقتی از ریلیتی استفاده میکنید کانکشن با خود sni که زدید هند شیک میکنه ؛ اگه اون سایتی که زدید رو nginx باشه پس هند شیک هم مثل nginx هست ؛ اگه یه وب سرور دیگه باشه که خوب همونی که هست میشه و این بهترین حالت ممکن هست و فایروال هیچ راهی نداره که تمایز قایل بشه بین این هند شیک و هند شیک کاربر عادی چون در طول هند شیک اتصال تونل شده به Sni و با خود اون هند شیک انجام میشه

درود بر شما ظهر نسخه 1.29 نصب کردم الان دیدم مجدد نوشتید reuploaded فرقی داره مجدد نصب کنیم ؟!

**Comment by Alireza78na** [comment]
> > وقتی از ریلیتی استفاده میکنید کانکشن با خود sni که زدید هند شیک میکنه ؛ اگه اون سایتی که زدید رو nginx باشه پس هند شیک هم مثل nginx هست ؛ اگه یه وب سرور دیگه باشه که خوب همونی که هست میشه و این بهترین حالت ممکن هست و فایروال هیچ راهی نداره که تمایز قایل بشه بین این هند شیک و هند شیک کاربر عادی چون در طول هند شیک اتصال تونل شده به Sni و با خود اون هند شیک انجام میشه
> 
> درود بر شما ظهر نسخه 1.29 نصب کردم الان دیدم مجدد نوشتید reuploaded فرقی داره مجدد نصب کنیم ؟!

حتما تغییراتی داشته که مجدد آپلود شده ، دوباره آپدیت کنید.
