### ISSUE TITLE
مشکل در اجرای Waterwall

### ISSUE THREAD

**Issue by Alireza78na** [radkesvat/WaterWall#127]
یه مشکلی که من از نسخه ی 1.25 به بعد باهاش مواجه میشم اینه که زمان زیادی طول میکشه تا دو سرور بهم متصل بشن.
مثلا بعد از آپدیت هر دو سرور به آخرین نسخه از Waterwall و اجرای اون ( به صورت Service اجرا میشه ) ، با این که همه چی درسته ولی چندین دقیقه طول میکشه تا ارتباط برقرار بشه و کانفیگ پینگ بده و بعد از اون هم باید حدودا 5 دقیقه یا بیشتر صبر کنم تا سرعت اتصال خوب و پایدار بشه.
رو ورژن 1.29 انقد قطع موند که دیگه مجبور شدم برگردم به نسخه ی قبل تا بعدا دوباره تست کنم.
از تونل reverse Reality استفاده میکنم و بخش Workers ها رو هم طبق توصیه ی خودتون دستی تغییر دادم.

**Comment by Alireza78na** [comment]
اینم اضافه کنم که Waterwall دقیقا سر Workers به مشکل میخوره. این قسمت:
2024-07-16 08:24:28.457 DEBUG Core: starting workers ...

روی هر دو سرور اینجوریه.
مقدار Workers رو روی هر دو سرور به مقدار 0 تنظیم کردم و مشکل رفع نشد.

**Comment by hatinati2** [comment]
با اسکریپت زیر تست کنید

bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/WaterWall-Docs/main/install.sh)
