### ISSUE TITLE
فیدبک نسخه 1.29 متد CDN Tunnel

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#128]
درود مهندس @radkesvat 

بنده روی 5 سرور که از دیتاسنترهای مختلف ایران و خارج هستن ، روی همه سرورهای ایران و خارج نسخه 1.29 رو تست کردم . بهتر از قبل شده اما همچنان به صورت رندوم هر 1 الی 5 دقیقه قطع میشه و تلگرام حدود 4-5 ثانیه میره روی کانکتینگ . این مورد روی تلگرام شاید خیلی اذیت نکنه اما توی ویدیوهای اینستاگرام باعث قطع شدن میشه و باید مجدد باز بشه . بنده مجدد به نسخه 1.25 داونگرید کردم . این فعلا پایدار ترین نسخه هست فقط مشکلی که داره مصرف منابع هست .

توی 1.29 مصرف منابع بهتره اما خود تانل قطعی داره . ممنون میشم بیشتر بهینه سازی کنید این قطعی ها رفع بشه . تشکر

**Comment by NIKA5050** [comment]
> درود مهندس @radkesvat
> 
> بنده روی 5 سرور که از دیتاسنترهای مختلف ایران و خارج هستن ، روی همه سرورهای ایران و خارج نسخه 1.29 رو تست کردم . بهتر از قبل شده اما همچنان به صورت رندوم هر 1 الی 5 دقیقه قطع میشه و تلگرام حدود 4-5 ثانیه میره روی کانکتینگ . این مورد روی تلگرام شاید خیلی اذیت نکنه اما توی ویدیوهای اینستاگرام باعث قطع شدن میشه و باید مجدد باز بشه . بنده مجدد به نسخه 1.25 داونگرید کردم . این فعلا پایدار ترین نسخه هست فقط مشکلی که داره مصرف منابع هست .
> 
> توی 1.29 مصرف منابع بهتره اما خود تانل قطعی داره . ممنون میشم بیشتر بهینه سازی کنید این قطعی ها رفع بشه . تشکر

اخرین نسخه re uplod نصب کردید یا همون دیروزیه ؟

**Comment by radkesvat** [comment]
اکی بازم تغییرات میدم ؛ یه روش دیگه فلو کنترل ماکس رو تست میکنم برا نسخه بعد

**Comment by hatinati2** [comment]
با اسکریپت زیر تست کنید

bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/WaterWall-Docs/main/install.sh)

**Comment by lostsoul6** [comment]
@hatinati2 

این اسکریپت تفاوت با آخرین ریلیز چی هست؟

**Comment by netsupcloud** [comment]
> اکی بازم تغییرات میدم ؛ یه روش دیگه فلو کنترل ماکس رو تست میکنم برا نسخه بعد

مهندس این فلوکنترل رو نمیشه در دسترس خودمون قرار بدید بتونیم تو json مدیریت کنیم ؟ و اینکه ظاهرا کانکشن ها لو میرن و ایران اکسس مییشن گاهی دوباره آزاد میشن و از وقتی تانل رو بستم دیگه نشده
- reverse halfduplex grpc cdn tls
- minumum-unused 16
- concurrent 256

ضمن اینکه بین 10 تا سرور لودبالانس شده و هم اصلا کانکشن اصلی نیست و کانکشن های سریعتری هم هست که کلاینت کاربر انتخاب میکنه ظاهرا صرفا به این خاطر که کلودفلر بهشون وصل میشه کافیه برای پراب کردن
از 10 تا سرور موقتا 7 تا ایران اکسس شده بودن و یه مدت بعد دوباره رفع شد. درواقع مثله اینه که دارن میگن ما خودمون شک کردیم همین کافیه پس یکم قطع میکنیم. البته اینم بگم رو پورت 443 رو سرورهای ایران هیچ برنامه ای فعال نیست و همینطور پورت 80 و فالبکی هم فعال نیست و یه کانکشن vmess رو پورت 2080 فقط فعال هست که واتروال ردش میکنه. و اینکه شما مشخص نکردید اون ترافیک زیادی که رو سرور خارج رد و بدل میشه دقیقا چیه و چرا با concurrent زیاد میشه؟

**Comment by netsupcloud** [comment]
> اکی بازم تغییرات میدم ؛ یه روش دیگه فلو کنترل ماکس رو تست میکنم برا نسخه بعد

مهندس این فلوکنترل رو نمیشه در دسترس خودمون قرار بدید بتونیم تو json مدیریت کنیم ؟ و اینکه ظاهرا کانکشن ها لو میرن و ایران اکسس مییشن گاهی دوباره آزاد میشن و از وقتی تانل رو بستم دیگه نشده

reverse halfduplex grpc cdn tls
minumum-unused 16
concurrent 256
workers 256
ضمن اینکه بین 10 تا سرور لودبالانس شده و هم اصلا کانکشن اصلی نیست و کانکشن های سریعتری هم هست که کلاینت کاربر انتخاب میکنه ظاهرا صرفا به این خاطر که کلودفلر بهشون وصل میشه اونم با grpc کافیه برای پراب کردن برای همین من نظرم اینه حتما ws رو اضافه کنید تا بازخوردشو بگیریم.
از 10 تا سرور موقتا 7 تا ایران اکسس شده بودن و یه مدت بعد دوباره رفع شد. درواقع مثله اینه که دارن میگن ما خودمون شک کردیم همین کافیه پس یکم قطع میکنیم یعنی کانکشنی که پترن اونو تشخیص ندن مثلا هالفداپلکس واتروال اونو به اینصورت موقت اختلال میندازن مگر اینکه این ترافیک افزایش پیدا کنه تا بنظرشون عادی بیاد. البته اینم بگم رو پورت 443 رو سرورهای ایران هیچ برنامه ای فعال نیست و همینطور پورت 80 و فالبکی هم فعال نیست و یه کانکشن vmess رو پورت 2080 فقط فعال هست که واتروال ردش میکنه و رو پورت های دیگه هم vmess ها و تروجان های دیگه ای هست که تانل دیگه که از cdn رد میشه اونارو رد میکنه و مشکل ایران اکسسز برای اونا وجود نداره. و اینکه شما مشخص نکردید اون ترافیک زیادی که رو سرور خارج رد و بدل میشه دقیقا چیه و چرا با workers زیاد میشه؟

**Comment by netsupcloud** [comment]
> اکی بازم تغییرات میدم ؛ یه روش دیگه فلو کنترل ماکس رو تست میکنم برا نسخه بعد

> اکی بازم تغییرات میدم ؛ یه روش دیگه فلو کنترل ماکس رو تست میکنم برا نسخه بعد

مهندس این فلوکنترل رو نمیشه در دسترس خودمون قرار بدید بتونیم تو json مدیریت کنیم ؟ و اینکه ظاهرا کانکشن ها لو میرن و ایران اکسس مییشن گاهی دوباره آزاد میشن و از وقتی تانل رو بستم دیگه نشده

reverse halfduplex grpc cdn tls
minumum-unused 16
concurrent 256
workers 256
ضمن اینکه بین ده تا سرور لودبالانس شده و هم اصلا کانکشن اصلی نیست و کانکشن های سریعتری هم هست که کلاینت کاربر انتخاب میکنه ظاهرا صرفا به این خاطر که کلودفلر بهشون وصل میشه اونم با [جی آر پی سی](url) کافیه برای پراب کردن برای همین من نظرم اینه حتما [وبسوکت ](url)رو اضافه کنید تا بازخوردشو بگیریم.
از ده تا سرور موقتا هفت تا ایران اکسس شده بودن و یه مدت بعد دوباره رفع شد. درواقع مثله اینه که دارن میگن ما خودمون شک کردیم همین کافیه پس یکم قطع میکنیم یعنی کانکشنی که پترن اونو تشخیص ندن مثلا [هالفداپلکس واتروال](url) اونو به اینصورت موقت اختلال میندازن مگر اینکه این ترافیک افزایش پیدا کنه تا بنظرشون عادی بیاد. البته اینم بگم رو پورت 443 رو سرورهای ایران هیچ برنامه ای فعال نیست و همینطور پورت 80 و فالبکی هم فعال نیست و یه کانکشن [ویمس ](url)رو پورت 2080 فقط فعال هست که واتروال ردش میکنه و رو پورت های دیگه هم [ویمس ](url)ها و [تروجان ](url)های دیگه ای هست که تانل دیگه که از [سی دی ان](url) رد میشه اونارو رد میکنه و مشکل ایران اکسسز برای اونا وجود نداره. و اینکه شما مشخص نکردید اون ترافیک زیادی که رو سرور خارج رد و بدل میشه دقیقا چیه و چرا با [ورکرز ](url)زیاد میشه؟

**Comment by lostsoul6** [comment]
@netsupcloud 

منم الان نگاه کردم ۵۰۰ مگابیت ترافیک روی سرور خارجم هست . تانل رو قطع کردم ولی بازم ترافیک هست . چی هست قضیه؟

**Comment by netsupcloud** [comment]
> @netsupcloud
> 
> منم الان نگاه کردم ۵۰۰ مگابیت ترافیک روی سرور خارجم هست . تانل رو قطع کردم ولی بازم ترافیک هست . چی هست قضیه؟

مورد خاصی نیست کانکشن اماده میشه قبل از ارسال ترافیک تا سرعت بالاتر بره که خودشون مصرف دارن هر کانکشن در حد 10 کیلوبایت در ثانیه و تعداد ورکر ضربدر minimum-unused باعث میشه زیاد بشه این ترافیک ولی خب مطمعن نیستم ولی تعداد ورکر رابطه مستقیم داره با این مصرف minimum-unused رو البته تست نکردم ولی همینه ظاهرا خودشون البته هنوز تایید نکردن @radkesvat
