### ISSUE TITLE
error directory start watterwall

### ISSUE THREAD

**Issue by aminsapa** [radkesvat/WaterWall#129]
سلام و خسته نباشید @radkesvat 
 موقع استارت واتروال این ارور رو در سرور ایران 
-bash: ./Waterwall: Is a directory
و این ارور رو در سرور خارج دارم مشکل از چیه
-bash: ./Waterwall: Permission denied

**Comment by Saleh-Mumtaz** [comment]
ایشیو پین شده رو بخونید.
در صفحه ایشیو ها هست.
