### ISSUE TITLE
مشکل مربوط به کانفیگ Vless خالی

### ISSUE THREAD

**Issue by MD1373** [radkesvat/WaterWall#130]
همونطور که توی صفحه اول مربوط به waterwall اشاره فرمودید که به هیچ عنوان از کانفیگ Vless خالی استفاده نکنیم

متاسفانه کانفیگ رو با Vless - TCP Header ساختم و این کانفیگ ها الان در حال استفاده هستن و دسترسی ازین بابت وجود نداره ، هیچ کدوم از کاربرها هم از لینک سابسکریپشن استفاده نکردن و همشون با کانفیگ مستقیم متصل شدن ، قبلا بنده از vmess هم استفاده میکردم ولی متاسفانه با توجه به رمزنگاری بودن vmess منابع زیادی مصرف میکرد و اکثرا به خاطر لود بالای CPU در مواقعی که کانکشن زیادی برقرار بود سیستم هنگ میکرد.

با توجه به موردی که عرض کردم آیا روشی هست که بشه از تانل امن و پرسرعتی که اختلال کمتری داشته باشه استفاده کرد؟

مورد بعدی اینکه در حال حاظر بنده دارم از پنل مرزبان استفاده میکنم

یه سرور مرکزی با پورت 443
یه نود ایران با پورت 1010
یه نود خارج با پورت 2010 

دارم

**Comment by radkesvat** [comment]
کانفیگ باید در گوشی کاربر تغییر کنه و داخل پنل مثلا xui

واتروال اینجا نقشی نداره چون فقط تونل هست، تا جایی که من سوادم میرسه هر روشی تونلی هم استفاده کنید مشکل کانفیگ  vless لخت رو حل نمی کنه

**Comment by MD1373** [comment]
> کانفیگ باید در گوشی کاربر تغییر کنه و داخل پنل مثلا xui
> 
> واتروال اینجا نقشی نداره چون فقط تونل هست، تا جایی که من سوادم میرسه هر روشی تونلی هم استفاده کنید مشکل کانفیگ vless لخت رو حل نمی کنه

الان من بخوام پنل جدید راه اندازی کنم ، یوزرام بالاس کدوم روش رو شما پیشنهاد میدید؟
و اینکه اگر از پنل مرزبان استفاده کنم ، آیا روی سرور مرکزی نیازه تغییراتی انجام بدم؟
مثلا فایل core.jsom‌ کجا قرار میگیره ؟ روی سرور ایران ، روی سرور خارج ، یا روی سرور مرکزی؟
