### ISSUE TITLE
مشکل با متد CDN

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#131]
درود مهندس وقت بخیر @radkesvat 

امروز یکی از تانل ها که با CDN کلادفلر بود قطع شد . وقتی با cmd دامنه رو پینگ میگیرم آی پی فیلترینگ برمیگرده :

```
C:\Users\MY SYSTEM>ping ir4fast.tomamto13.lol

Pinging ir4fast.tomamto13.lol [10.10.34.34] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
```
یعنی دامنه فیلتر شده ؟ تا جایی که خاطرم هست گفته بودید در متد cdn دامنه فیلتر نمیشه . 
چی کار کنیم دامنه رو نزنن ؟

**Comment by lostsoul6** [comment]
درود @radkesvat 

توی داکیومنت ها روش cdn یه مثال مالتی پورت گذاشتید . دقیقا کانفیگش همون هست . فکر کنم ریورس هست چون اسم کانفیگ رو این زدید : config_reverse_tls_grpc_multiport_kharej

بله دامنه فقط برای تانل بوده . سه تا a record داشته دامنه و هر رکورد برای تانل یک سرور بوده . مجموعا سه تا سرور با این دامنه تانل شده بوده .

**Comment by radkesvat** [comment]
به نظرم یه ir رو تست کنید ببینید اون فیلتر میشه ؛ بعد این دامنه شاید دستی بلاک بشه ... کانفیگتون پابلیک نشده؟

**Comment by lostsoul6** [comment]
درود مهندس @radkesvat 

دامنه تانل با کانفیگ فرق داره . امکان پابلیک شدن نداره
