### ISSUE TITLE
دریافت warn

### ISSUE THREAD

**Issue by arashdostar** [radkesvat/WaterWall#132]
سلام وقت بخیر من با روش halfduplex  و perconnect  روی سرور ایران کار میکنم، در سرور خارج مدام ارور و warn زیر رو میگیرم. علت چیه؟ مهمه؟
ERROR RealityClient: verifyMessage failed
WARN  connfd=17 connect error: Transport endpoint is not connected:107

**Comment by radkesvat** [comment]
مهم نیست ؛ تا وقتی اتصال برقراره اهمیتی نداره ؛ منم این وارنینگو میگیرم و رو نسخه های قبلی واتروال هم زدم تست کردم ببینم شاید باگ باشه ولی روی اونا هم بود ؛ شاید این تلاش gfw برای تشخیص ریلیتی باشه که امضا match نیست ؛ شایدم یه باگ توی کد باشه که خیلی مهم نیست فعلا...

**Comment by arashdostar** [comment]
خیلی ممنون، بله وصله فعلا و داره خوب کار میکنه
فقط یک سوال دیگه در قسمت ورکر ها وقتی جفت سرور ها روی ۰ هستن کانکت هست ولی پینگ بالاس و وقتی همه روی ۴ ۱۶ یا ۴ ۳۲ تنظیم میکنم یا کانکت نمیشن یا باز پینگ بالاست، الان روی ۱۶ ۶۴ تنظیم کردم و اوکی هستش پینگ خوبه و قطعی نداره، مشکلی نداره از بابت خاصی حالا مثلا بسته شدن یا ...؟
