### ISSUE TITLE
شیر کردن مباحثی که یاد میگیرید

### ISSUE THREAD

**Issue by lambdaxyzt** [radkesvat/WaterWall#134]
سلام خوب هستین ؟ پروژتون خیلی باحاله ... میخواستم اگر لطف کنید تمام مباحثی که میخونید رو شیر کنید یا منابعی که میخونید رو به اشتراک بگذارید مثل همین یاد گرفتن tun device ... ما هم بتونیم یاد بگیریم ولی بخاطر اینکه توی بحث برنامه نویسیش نیستم نمیدونم از کجا باید شروع کرد و خط رو طی کرد

**Comment by Saleh-Mumtaz** [comment]
درود این جور مسائل رو در بخش دیسکاشن مطرح کنید
