### ISSUE TITLE
فیدبک برای متد CDN

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#137]
درود مهندس وقت بخیر @radkesvat 

مهندس جان بعد از نسخه 1.25 چند نسخه ارائه شده با متد CDN قابل استفاده نیست . ورژن های بعد از 1.25 روی متد CDN دچار قطعی زیاد هستن . روی خود نسخه 1.25 شرایط بهتره اما هر ساعت مشکل میخوره و باید سرور خارج رو ریبوت کنیم تا اوکی بشه . منابع سرور خارج رو خیلی درگیر میکنه و مصرف شبکه سرور هم به صورت عجیبی بالا هست .

چی کار میتونم کنم که این قطعی و اختلال متد CDN که هر ساعت پیش میاد رفع بشه ؟ من حدود 250 کاربر روی سرور دارم . داخل سرور ایران تعداد ورکر رو 2 گذاشتم و داخل سرور خارج تعداد ورکر رو 16 گذاشتم . آیا اگر 0 بزارم بهتره ؟ یا مثلا ببرم بالا تر ؟

بعد چیزی که متوجه شدم اینه که سرور ایران منابعش خیلی درگیر نیست ولی سرور خارج منابع وحشتاک درگیره . یعنی مثلا من رم 8 گذاشتم خارج رو با 4 هسته سی پی یو ، بازم پر میشه زود . وقتی ریبوت میکنم مدتی اوکی میشه ولی باز بعد یه ساعت پر میشه منابع .

این متد cdn خیلی خوبه . ای کاش میشد این مشکلاتش رو فیکس کرد که بتونیم استفاده کنیم . نمیتونید همین ورژن 1.25 رو بدون تغییرات زیاد که باعث خراب شدن متد cdn بشه ، فقط مصرف منابعش رو بهینه سازی کنید ؟ چون تغییراتی که بعد از ورژن 1.25 دادید مثلا روی ورژن 1.30 باعث شده متد cdn قابل استفاده نباشه . تانل یا خیلی سخت برقرار میشه یا اگرم بشه بعد چند دقیقه از کار میوفته روی نسخه های بعد از 1.25 .

تشکر

**Comment by radkesvat** [comment]
خیلی عجیبه که روی 1.30 مشکل دارید ولی روی بغیه ندارید....

من اینو تست کردم روی 1.30 کار میکرد همه چی ؛ تلگرام هم اصلا دچار قطع شدن نمیشد... 


حالا به جز واتروال ؛ با پروژه gost هم میتونید همین نوع تانل ریورس cdn رو بزنید ؛ اونو تست کنید حتما شاید کامل مشکلتون رو حل کرد ؛ همچنین پروژه chisel

با این دوتا دقیقا میتونید همین روش reverse cdn رو بزنید

**Comment by lostsoul6** [comment]
@radkesvat 

ممنون مجدد ۱.۳۰ رو چک میکنم . مهندس برای ۲۵۰ کاربر ، ورکر روی ایران و خارج چند بزاریم؟ شما نسخه ۱.۳۰ متد cdn رو با چند کاربر تست کردید؟

کانفیگ ما همون کانفیگ مالتی پورت هست که خودتون توی بخش cdn گذاشتید . دقیقا همون رو کپی کردیم . تشکر

**Comment by radkesvat** [comment]
روی سرور خارج  ۸ برابر ایران بزارید کافیه

بعد اینکه اول همیشه سرور ایران رو اجرا کنید ؛ بعد خارج رو اجرا کنید

این ترتیب رو رعایت کنید برای روش ریورس cdn

**Comment by lostsoul6** [comment]
ممنون الانم همین کار رو میکنم @radkesvat 

شما میتونید کانفیگی که تست کردید اوکی بود رو به اشتراک بزارید ؟ شاید من اشتباهی میکنم . اگر مقدور بود برام ارسال کنید ایران و خارجی که خودتون با نسخه ۱.۳۰ تست کردید اوکی بود

**Comment by rasoolkhalifa** [comment]
Hey , Thanks for the hard work.

I tried the CDN method but no matter how hard I tried its just does not work. I mean I can see that both servers connect through my log but the configs do not work.

used both multi port and single port ways.
created a sub domain in CF that point to Iran's IP and used the Proxied tick.
Added the CF IP ranges in the config
Used X-ui as a panel on the Kharej server
Used proxy method in inbounds to connect them to Iran's sub domain


Cant get the inbounds to work though! no ping gRPC , WS , TCP nope

Maybe I'm missing something?
