### ISSUE TITLE
مشکل دسترسی به دستگاه‌های دیگر در شبکه با استفاده از ریورس تانل Reality

### ISSUE THREAD

**Issue by khazaee** [radkesvat/WaterWall#138]
سلام مهندس عزیز،

ممنون بابت پروژه بسیار کارآمدتان. واقعاً باید به شما خسته نباشید گفت. این پروژه عالی است و خیلی هم خوب کار می‌کند. اما من یک مشکل با این پروژه دارم که البته برای استفاده به عنوان فیلترشکن نیست. من از پروژه شما به عنوان یک ریورس تانل برای شبکه خصوصی خودم استفاده می‌کنم که پشت NAT قرار دارد و آی‌پی پابلیک ندارد، به همین دلیل دسترسی مستقیم به آن امکان‌پذیر نیست. تنها راه برای دسترسی به شبکه خودم استفاده از ریورس تانل‌ها است.

تانل کلودفلر در ایران فیلتر است و به همین خاطر من از ریورس تانل Reality شما استفاده می‌کنم که به درستی هم اجرا می‌شود، اما یک سری مشکلاتی وجود دارد که با دانش محدود خودم نتوانستم آن‌ها را حل کنم.

وقتی ریورس تانل را برقرار می‌کنم، با یک دستگاه اوبونتو در شبکه خانگی خودم که یک وب سرویس روی آن وجود دارد، دسترسی من به درستی برقرار است. اما مشکل از آنجا شروع می‌شود که من یک وب سرویس دیگر هم در شبکه خانگی‌ام بر روی یک دستگاه دیگر دارم که آن هم اوبونتو است و در همان رنج آی‌پی اوبونتویی که تانل را برقرار کرده، قرار دارد. من تنظیمات آی‌پی فوروارد و پورت فوروارد را هم به درستی انجام داده‌ام، اما نمی‌دانم چرا این تانل فقط تا دستگاهی که تانل را اجرا کرده دسترسی می‌دهد و به سرویس‌های دیگر روی دستگاه‌های دیگر شبکه دسترسی نمی‌دهد.

از شما خواهشمندم راهنمایی بفرمایید که اگر بخواهیم از این ریورس تانل برای دسترسی به پروتکل‌هایی مثل RDP، HTTP، HTTPS و SSH روی دستگاه‌های دیگر در رنج دستگاه برقرار کننده تانل استفاده کنیم، چه باید کرد؟

با تشکر فراوان.

**Comment by radkesvat** [comment]
سلام، احتمالا روش مالتی پورت تونل کردید، روش مالتی پورت تمام بازه ای که به عنوان ورودی هست رو تونل میکنه و این باعث میشه برنام های دیگه ای که رو اون پورت ها هستن ترافیک دریافت نکنن

لطفا اینجو چک کنید و بگید مشکل همین بود یا نه

**Comment by khazaee** [comment]
بله مهدس عزیز در کانفیگ ها از مالتی پورت استفاده شده است من کانفیگ های د.و طرف را ارسال میکنم ممنون میشم که محبت بفرمایید این کانفیگ ها را برای هر طرف نسبت به این سناریو برای چندین پورت به صورت مثال در اینجا جوری کانفیگ کنید که دسترسی چندین پورت باز شود و در نهایت این پورت ها به آی پی های دیگر داخل شبکه هم دسترسی داشته باشند به گونه ای که یک پورت هم بر روی دستگاهی که تانل را برقرار کرده دسترسی داشته باشد. ممنون از رسیدگی شما.

کانفیگ سرور ایرانی :
{
    "name": "reverse_reality_server_multiport",
    "nodes": [
        {
            "name": "users_inbound",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": [443,65535],
                "nodelay": true
            },
            "next": "header"
        },
        {
            "name": "header",
            "type": "HeaderClient",
            "settings": {
                "data": "src_context->port"
            },
            "next": "bridge2"
        },
        {
            "name": "bridge2",
            "type": "Bridge",
            "settings": {
                "pair": "bridge1"
            }
        },
        {
            "name": "bridge1",
            "type": "Bridge",
            "settings": {
                "pair": "bridge2"
            }
        },
        {
            "name": "reverse_server",
            "type": "ReverseServer",
            "settings": {},
            "next": "bridge1"
        },
        {
            "name": "reality_server",
            "type": "RealityServer",
            "settings": {
                "destination": "reality_dest",
                "password": "12345"
            },
            "next": "reverse_server"
        },
        {
            "name": "kharej_inbound",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": 443,
                "nodelay": true,
                "whitelist": [
                    "0.0.0.0/0"
                ]
            },
            "next": "reality_server"
        },
        {
            "name": "reality_dest",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "web.eitaa.com",
                "port": 443
            }
        }
    ]
}


کانفیگ در شبکه خانگی :

{
    "name": "reverse_reality_client_multiport",
    "nodes": [
        {
            "name": "outbound_to_core",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "127.0.0.1",
                "port": "dest_context->port"
            }
        },
        {
            "name": "header",
            "type": "HeaderServer",
            "settings": {
                "override": "dest_context->port"
            },
            "next": "outbound_to_core"
        },
        {
            "name": "bridge1",
            "type": "Bridge",
            "settings": {
                "pair": "bridge2"
            },
            "next": "header"
        },
        {
            "name": "bridge2",
            "type": "Bridge",
            "settings": {
                "pair": "bridge1"
            },
            "next": "reverse_client"
        },
        {
            "name": "reverse_client",
            "type": "ReverseClient",
            "settings": {
                "minimum-unused": 16
            },
            "next": "reality_client"
        },
        {
            "name": "reality_client",
            "type": "RealityClient",
            "settings": {
                "sni": "web.eitaa.com",
                "password": "12345"
            },
            "next": "outbound_to_iran"
        },
        {
            "name": "outbound_to_iran",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "188.***.***.***",
                "port": 443
            }
        }
    ]
}

**Comment by khazaee** [comment]
من خیلی با کانفیگ سر و کله زدم به هیچ ترتیبی نشد که من مالتی پورت جدا راه اندازی کنم نمیدونم شاید بیشتر باید کار کنم روی کانفیگ ها ولی در 48 ساعت گذشته 30 ساعت دارم با این کانفیگ ها کار میکنم که واقعا گردن درد شدم. مهندس اگر شدنی نیست اعلام کنید اگر هم شدنی است یک کانفیگ شسته رفته برای سرور و کلاینت بزارید چون بنظر من خیلی مهم است.

**Comment by hatinati2** [comment]
سلام 
با اسکریپت زیر تست کنید

bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/WaterWall-Docs/main/install.sh)

**Comment by khazaee** [comment]
> سلام با اسکریپت زیر تست کنید
> 
> bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/WaterWall-Docs/main/install.sh)

نه متاسفانه با این اسکریپت هم تست کردم نشد.
