### ISSUE TITLE
1.30 crash

### ISSUE THREAD

**Issue by aliafshany** [radkesvat/WaterWall#139]
سلام
من از نسخه آخری که در این لحظه وجود داره دارم استفاده میکنم.
تانل مورد استفادم HalfDuplex با پیکربندی Reverse Reality با mux هست.
تا همین یکم پیش همه چی خوب بود و من ترافیک خیلی زیادی رو هم میگرفتم اما از چند دقیقه پیش نسخه روی سرور ایران بعد از چند ثانیه کرش میکنه!
اتصال هم برقرار میشه ولی بعد از چند ثانیه از کار میفته
مشکل از چه چیزی میتونه باشه؟

![CleanShot 2024-07-22 at 14 40 29@2x](https://github.com/user-attachments/assets/f0edb984-3685-4ff7-936d-f96a28223048)

**Comment by aliafshany** [comment]
آپدیت:
هیچ ایده ای ندارم که چرا اینطور شد, ولی بعد از نیم ساعت دوباره ران کردم و حل شد
مساله اینه که چرا در وهله اول باید اینطوری شه اصلا

**Comment by mory** [comment]
برای من روی سرور خارج خیلی کرش میکنه و مینویسه killed،  هیچ نکته ای از لاگ مشخص نیست.
