### ISSUE TITLE
گزارش ورژن ۰.۹۴

### ISSUE THREAD

**Issue by Ferixy** [radkesvat/WaterWall#14]
سلام اولا دم دولوپر گرم. چندماهه داره پشت سر هم نان استاپ رو پروژه کار میکنه.
تانل تی ال اس کار میکنه بدون مشکل (مثل ورژن ۰.۹۲) ولی با اپدیت جدید هم هنوز tls h2 مشکل داره و سرور ایران بعد چندثانیه قطع میکنه مینویسه core dumped 
پینگ هم توی ورژن قبلی هم جدید فوق العده بالاست و آپلود صفر هست.
ریورس یا مستقیم رو فعلا تست نکردم

**Comment by radkesvat** [comment]
سلام ممنون ؛ برسی میکنم

**Comment by Ferixy** [comment]
تلگرامتونو چک کنید

**Comment by radkesvat** [comment]
لطفا تو همین گیتهاب درمورد پروژه حرف بزنیم که اگه کسی مشکل مشابه داشت ببینه و استفاده کنه

**Comment by radkesvat** [comment]
با نسخه جدید هم تست کنید

**Comment by Ferixy** [comment]
سلام اگر بخواید میتونم تنظیمات رو دوباره همینجا براتون بفرستم. ولی از همون template خودتون برای تانل tls h2 استفاده کردم فقط دامین خودمو جای گذاری کردم و چیز بخصوصی رو تغییر ندادم.
تانلم tls h2 مستقیم بود یعنی کانکشن از ایران به خارج باز میشد. از grpc استفاده میشد چون داخل تمپلیت خودتونم استفاده شده. دامنه م پشت پروکسی کلودفلیر بوده.
ممنون بابت ریلیز جدید. صبح حدودای ۴ وقتی کسی از سرور استفاده نمیکنه تستش میکنم فیدبک میدم همینجا.
درضمن مشکل پینگ خیلی بالا و اپلود صفر با عوض کردن دیتاسنتر بهتر شد. دیتاسنتر هایی که آپلینک آسیاتک یا مخابرات دارن اصلا پیشنهاد نمیدم. مخابرات پینگو بی نهایت میکنه آپلودم منفجر میکنه از طرف دیگه پکت لاست هم ایجاد میکنه. روی آسیاتک فقط پکت لاس وجود داره که فکر کنم ربطی به فایروال نداره فقط شبکه شون الان تو شرایط افتضاحیه. الان دارم از یک دیتاسنتر با آپلینک جدا استفاده میکنم داره خوب کار میده. پینگ بین ۷۰۰ تا ۱۲۰۰ هست و پکت لاس شاید کلا ۳ بار از بعد از ظهر که دیتاسنتر عوض کردم به چشمم اومده. یک موضوع دیگه هم بگم که بنده برنامه رو بعنوان سرویس ران کردم و کرون جاب هم ست کردم هم یکساعت یکبار ریستارت میشه تانل هم سمت ایران هم خارج. تانل خیلی استیبل هست اصلا به همچین چیزی نیاز نداره ولی داشتنش بد نیست.

درضمن اگر امکانش هست یک آپشن authentication مثلا با پسورد ایجاد کنید که هر کسی نتونه به تانل وصل بشه و هندشیک رخ بده . تکنیسین دیتاسنتر هم sni و هم ایپی که سرور ایران داره بهش وصل میشه رو میتونه ببینه و خود تکنیسین میتونه یک سرور bait ستاپ کنه که دقیقا به همون آیپی و sni وصل بشه و ببینه اگر هندشیک رخ میده آیپی رو فیلتر کته.

**Comment by radkesvat** [comment]
دیتا سنتر ها تا جایی که من میدونم چنین کاری نمیکنن ؛ همه اونایی که فروش سرور تونل رو ممنوع کرده بودن الان پشیمان هستن از این که رقبا 
دارن حسابی پول درمیارن و دنبال این هستن که خودشون هم پلن های یک به یک ارایه بدن 

ول درکل پروتکل ها اضافه میشن و این حالت هم الان با trojan auth میتونید داشته باشید ولی خوب پروتکل عوض میشه ؛ اونوقت باید کلاینت هم واتروال باشه با کانفیگ مخصوص این نوع احراز
