### ISSUE TITLE
اتصال به پورت لوکال

### ISSUE THREAD

**Issue by iMat1n** [radkesvat/WaterWall#143]
با عرض سلام و خسته نباشید خدمت شما و تشکر از زحماتتون
یه سوالی داشتم ممنون میشم راهنمایی کنید حقیقتا خودم به نتیجه نرسیدم و چیزی داخل داکیومنت دستگیرم نشد

من یه پروکسی ساکس 5 روی لوکالم دارم که میخوام ترافیک خروجیم رو بفرستم روی اون، و این ساکس از طریق نرم افزار دیگه ای لیسن شده
چه تغییراتی توی نود زیر باید انجام بدم تا بتونم این کار رو انجام بدم؟
```json
{
  "name": "my-connector",
  "type": "Connector",
  "settings": {
    "nodelay": true,
    "address":"dest_context->address",
    "port": "dest_context->port"
    }
}
```

اگه فرض رو بر این بگیریم که ساکس من روی پورت 2080 باشه این رو تست کردم و به نتیجه نرسیدم:
```json
{
  "name": "my-connector",
  "type": "TcpConnector",
  "settings": {
    "nodelay": true,
    "address":"127.0.0.1",
    "port": 2080
    }
}
```

ممنون میشم راهنمایی کنید

**Comment by radkesvat** [comment]
دقیق متوجه نشدم منظورتونو ...

**Comment by iMat1n** [comment]
@radkesvat 
سلام مجدد
ببینید من قصد دارم ترافیک خروجی واتروال از یک پورت ساکس ۵ لوکال رد بشه
مثلا من روی پورت ۲۰۸۰ سرورم یک سرویس وارپ دارم و میخوام ترافیک واتروال از وارپ رد بشه 
ممنون میشم راهنمایی کنید توی نمونه تروجان که گذاشتین این مورد به چه شکل انجام میشه ممنون
