### ISSUE TITLE
دو تانل HalfDuplex Reverse realityبه طور همزمان 

### ISSUE THREAD

**Issue by EMMeiS** [radkesvat/WaterWall#148]
سلام وقت بخیر
آیا امکانش هست همزمان دوتا تانل  HalfDuplex Reverse reality رو اجرا کرد؟
منظورم اینه که میشه یکی با ipv4 باشه و اون یکی با ipv6؟
اصلا امکانش  استفاده از ipv6 در این نوع تانل ممکنه؟

**Comment by radkesvat** [comment]
بله ایپی 6 کاملا ساپورت میشه ؛ به جای ادرس ipv4 ادرس ipv6 وارد کنید یا پشت دامنه بزارید

**Comment by EMMeiS** [comment]
مرسی متوجه شدم
فقط جواب سوال اول رو نگرفتم
آیا امکان اجرای همزمان ممکنه؟

**Comment by radkesvat** [comment]
بله میتونید مشکلی نداره ؛ توی فایل core.json شما میتونید تک به تک فایل های config رو اضافه کنید و واتروال همشون رو اجرا میکنه ؛ توی هرکودوم یه روش داشته باشید ؛ یا حتی می تونید نود های چند تا روش رو توی یه فایل json هم قرار بدید. یا حتی واتروال رو چند بار اجرا کنید هربار با فایل های مختلف ؛ راه زیاده...

**Comment by EMMeiS** [comment]
اگر امکانش بود لطفا یه نمونه فایل config بزارید برای این روش با آیپی های ورژن 6 
شخصا چندبار امتحان کردم به مشکل خوردم و متوجه نشدم که مشکل از کجاست واقعا!

**Comment by EMMeiS** [comment]
سلامی دوباره
من سعی کردم با ipv6 این تانل رو اجرا کنم اما به مشکل میخورم
امکانش هست یه نمونه فایل config.json با ipv6 قرار بدین هم برای سرور ایران و هم برای سرور خارج؟
