### ISSUE TITLE
Reverse Reality Tunnel with ipv6

### ISSUE THREAD

**Issue by AEydi** [radkesvat/WaterWall#152]
امکانش هست یک مثال با ipv6 برای Reverse Reality Tunnel قرار بدین
چندباری که تست کردم وصل نشده
مخصوصا whitelist رو چطور قرار بدیم

> {
>       "name": "kharej_inbound",
>       "type": "TcpListener",
>       "settings": {
>         "address": "0.0.0.0",
>         "port": 443,
>         "nodelay": true,
>         **"whitelist": ["2.2.2.2/32"]**
>       },
>       "next": "reality_server"
>     },

**Comment by sasadii21** [comment]
منم زدم نشد
