### ISSUE TITLE
ران نموندن واتروال

### ISSUE THREAD

**Issue by mmdh-ir** [radkesvat/WaterWall#154]
سلام و عرض ادب خدمت شما مهندس
پوزش میخوام من با استفاده از ip 6 to 4 و لوکال با واتروال تانل میکنم 
و با screen و nohup واتروال رو اجرا میکنم ولی بعد یه مدت تانل قطع میشه screen -ls یا jobs -l که میزنم میبینم خالیه و مجدد از نو باید اسکریپتو ران کنم و ران نمیمونه میشه راهنماییم کنید؟

**Comment by smj1234** [comment]
سرویس بساز اجرا کن

**Comment by mmdh-ir** [comment]
> سرویس بساز اجرا کن

چی؟!

**Comment by hatinati2** [comment]
سلام 
از اسکریپت داخل doc  استفاده کنید

https://radkesvat.github.io/WaterWall-Docs/docs/scripts
