### ISSUE TITLE
مشکل فوق‌العاده مهم ورژن ۰.۹۶ + فیدبک

### ISSUE THREAD

**Issue by Ferixy** [radkesvat/WaterWall#16]
سلام دوباره و خسته نباشید به دولوپر. تبریک میگم به همه دوستان.

خب بریم سر مسئله اصلی. ورژن جدید tls h2 ش هنوز مشکل داره. چه بدون کلودفلیر چه با کلودفلیر.
تانل هارو وقتی ران کردم متوجه یه چیز عجیب شدم. سرور ایران اصلا با سرور خارج صحبت نمیکنه و ارتباطی باهم ندارن ولی سرور ایران بجای اینکه ارور بده که endpoint در دسترس نیست یجوری رفتار میکرد که انگار به یه سرور وصل شده و داره اطلاعات هم جابجا می‌کنه!!!!!!! من تانل خارج هم قطع کردم و تانل ایران یه جوری رفتار میکرد انگار داره با یه سرور حرف میزنه و هندشیک هم رخ میداد بدون مشکل. این مورد هم پشت سی دی ان هم بدون سی دی ان رخ داد و چندباری هم چک کردم. حتی هردو سرور ایران و خارجم رو عوض کردم ولی داستان همون بود.
برگشتم به ورژن ۰.۹۴ و خواستم تانل بزنم روی سرور اولم که دیدم اصلا همه چی ترکیده! دیدم آیپی هردو سرور خارجم که روشون ورژن جدیدو تست کردم فیلتر شده و حتی با سایت check host هم وریفای کردم این داستان رو. لیتر لیتر عرق سرد ریختم ولی خداروشکر آیپی بکاپ و تمیز داشتم.
سرور اولم بدون مشکل به تانل قبلی برگشته و داره میکنه. سرور دومم هیچجوره با اینکه آیپی تمیزه (دوتا آیپی تمیزو تست کردم برای مطمئن شدن) و تنظیمات پنل ، تانل ، کانفیگ و دامنه/دی‌ان‌اس درست هستن کار نمیده با تانل ورژن ۰.۹۴ و نمیدونم چرا درصورتی که قبل از اینکه ۰.۹۶ رو تست کنم بدون مشکل بود.
لاگ رو که داخل ترمینال میدیدم دیدم که این دوتا ارتباطشون برقرار میشه و باهم حرف میزنن. برای تست سرور خارج رو قطع کردم و دیدم که ایران ارور داد که اندپوینت reachable نیست که یعنی باهم واقعاً داشتن حرف میزنن‌. دقیقا نزدیک ۲ ساعت بدون شوخی با تانل ور رفتم. ریستارت کردم ، دامین عوض کردم ، از تنظیمات پنلم و کانفیگم مطمئن شدم ، برنامه تانلو دوباره دانلود کردم رو سرور ، از اول کانفیگ رو انجام دادم و از درست بودن سرتیفیکت مطمئن شدم اما هیچی که هیچی. اونطور که بنظر میاد سرورا باهم حرف میزنن ولی دیتا جابجا نمیشه؟!؟!
در هرحال من نمیتونستم سرور رو اونقدر برای تایم زیادی فلج نگه دارم برای همین مجبور شدم تانل RTT بزنم که خداروشکر داره خوب کار میکنه.

ممنون واقعا که وقت میذارید.❤️❤️❤️

**Comment by Ferixy** [comment]
> لطفا یکمی کنتراست رو کم کنید 😅

کنتراست کدوم بخش؟

**Comment by Hamed-F** [comment]
> > لطفا یکمی کنتراست رو کم کنید 😅
> 
> کنتراست کدوم بخش؟

فکر میکنم متن رو میگه که با تاکید نوشتی :) مثل این ها (!!!!!!!) (؟!؟!)
