### ISSUE TITLE
یک سیستم اطلاع رسانی هنگام قطع شدن ارتباط میتونه کارامد باشه

### ISSUE THREAD

**Issue by mory** [radkesvat/WaterWall#163]
سلام، خدا قوت
اطلاع رسانی از طریق ایمیل یا ربات تلگرام یا حتی تغییر یک متغیر ساده در سرور که از روش های دیگه بتونیم شناساییش کنیم به نظر من کارامده چون بعد از کرش کردن سیستم خیلی دیر متوجه میشیم گاهی
خودمون بصورت جدا میتونیم درست کنیم ولی روی خودش سوار باشه جذاب تره

**Comment by neon-bartmoss** [comment]
از uptime kuma استفاده کن
تنظیمش کن که به پنلت از داخل تانل پینگ http بده 
داخل خودش انواع سیستم اطلاع رسانی و نوتیفیکیشن هم داره

**Comment by mory** [comment]
ممنون بابت پیشنهاد ولی نیازی نیست واقعا یک اسکریپت ساده مثل این کارو در میاره بخوبی :
