### ISSUE TITLE
محدود کردن تعداد آی پی کاربران

### ISSUE THREAD

**Issue by elegance666** [radkesvat/WaterWall#164]
به نظر با این روش دیگه امکان محدود کردن تعداد کاربران یک اکانت وجود نداره، چرا که سرور ایران پنل نداره، درسته؟

**Comment by netsupcloud** [comment]
آقا این تانله نه پنل که بخوای کاربر محدود کنی این دوتا سرور رو وصل میکنه به هم نه یوزر
