### ISSUE TITLE
HTTP Obfuscation issue in WaterWall-HalfDuplex

### ISSUE THREAD

**Issue by mai-develop** [radkesvat/WaterWall#167]
سلام وقت عالی بخیر

تو سیستم عامل اندروید برای عملکرد مناسب WhatsApp نیاز هست HTTP Obfuscation فعال باشه. اما زمانی که فعال می کنم کانفیگ تو اپ v2rayNG عملکرد مناسبی نداره ولی تو Hiddify مشکلی نداره. و زمانی که HTTP Obfuscation غیر فعاله مشکلی جز WhatsApp (اندروید) وجود نداره. (نتایج تست برای سرور رسپینا بود.)
روی سرور پیشگامان هم تست کردم با HTTP Obfuscation فعال، فقط دایرکت instagram مشکل داره با HTTP Obfuscation غیرفعال هم دایرکت instagram و هم WhatsApp.
ممنون میشم راهنمایی کنین ❤

Tunnel : WaterWall - HalfDuplex
Core version : v1.32 (also tested on v1.25)
Xray version : 1.8.23
Panel : 3X-UI v2.3.13 - (also tested on other versions)
v2rayNG version : v1.8.35 - (also tested on other versions)
Config : vless / TCP / no-TLS

_____________________________Android________________________________

Http Obfuscation : OFF / Android

✘ WhatsApp

✔︎ V2rayNG 
✔︎  Hiddify 

Http Obfuscation : ON / Android

✔︎ WhatsApp 

✘ V2rayNG 
✔︎  Hiddify

_____________________________iOS________________________________

Http Obfuscation : OFF / iOS

✔︎ WhatsApp 

✔︎ Shadowrocket 
✔︎ Streisand 
✔︎ FoXray 
✔︎ V2Box 
✔︎ NapsternetV

Http Obfuscation : ON / iOS

✔︎ WhatsApp 

✔︎ Shadowrocket 
✔︎ Streisand 
✔︎ FoXray 
✘ V2Box 
✘ NapsternetV

_____________________________________________________________

**Comment by Saleh-Mumtaz** [comment]
درود این مورد خارج از حیطه مشکلات مربوط به واتروال هست.
