### ISSUE TITLE
اشکال ورژن 1.32

### ISSUE THREAD

**Issue by rezhacker** [radkesvat/WaterWall#168]
سلام. من داشتم ورژن جدید رو تست میکردم. حالت Reset Tunnel
کار میکنه ولی این خطاها رو توی سرور خارج بهم لاگ میده:
WARN  TcpManipulator: dropped an ipv6 packet, length is too short for TCP header

ERROR RawDevice: write failed, ring is full

علت این خطاها چیه؟

**Comment by radkesvat** [comment]
اینا خطا نیستن، کاملا طبیعیه و درستش هم همینه، سیستم عامل خودش به سری پکت ها میفرسته به tun که دایل فنی اش اینه.

مشکلی نیست

**Comment by rezhacker** [comment]
ممنون
