### ISSUE TITLE
reset tunnel 

### ISSUE THREAD

**Issue by smj1234** [radkesvat/WaterWall#169]
سلام 
تک پورت انجام دادم پینگ از 10.0.0.2 دارن هر دوتا سررو اما وقتی  میخام اطلاعات منتقل کنم نمیشه - با مثلا پورتو جایگزین میکنم تو کانفیگ EoF  میده ( بگم که در کنارش سه تا تونل ریورس دیگه تو همین ایران و خارج دارم) - فایروالم خاموش بود

دستی خواشتم اط یه پوزت دیگه فورواد کنم رو پورت تونل بازم نشد

حالا نمیدونم این مشکل تک پورته یا ممکنه بخاطر چیز دیگه ای باشه

**Comment by radkesvat** [comment]
سلام حتما یجا اشتباه کردین چون داکیومنت رو باد اینکه نوشتم کامل از رودامیومنت تستش کردم و کارکرد، به نظرم یه بار ایپیتیبل رو روی هردوتا سرور ریست کنید و بعد اجرا کنید

**Comment by smj1234** [comment]
سلام ارتیاط تانل ها برقراره ( البته نمیدونم حالا وقتی از 10.0.0.2 پینگ سرور محالفو میده و ایپی رو هم فوروارد میکنه رمزنگاری و تغییر پاکت رو میده یا نه )

اما زمانی که میخام از اون تک پورت استفاده کنم مشکل داره - تماما مصل داکیومنه فقط جای [23,65535] اومدم یه تک پورت برای مثلا 30281 گذاشتم  - مابقی تانل ها هم فعال بودن و درواقع واتروال خطا نداشت - مشکل از مسیریابی هست به احتمال زیاد

البته Failtoban هم فعاله رو سرور !

**Comment by smj1234** [comment]
اینم بگم که چند ت اایپی دارند هر دوتا سرور ایران و خارج

**Comment by smj1234** [comment]
حل شد :  👍 
مشکل بابت محدودیت ایپی داخلی از سمت پنل سنایی بود
