### ISSUE TITLE
فیلتز شدن سرور خارج با ریست تانل 

### ISSUE THREAD

**Issue by smj1234** [radkesvat/WaterWall#179]
![ScreenShot_20240830094621](https://github.com/user-attachments/assets/5d6de312-4954-40ac-8291-936af808002b)

یه چیز عجیبی که اخیرا رخ داده روی این سرورم ( کلا فیلتر نیست تمیز بوده سرور) اینه که به شکل رندوم یدفعه فیلتر میشه و بعد رفع فیلتر  برای یه مدت و دوباره همینطوری رندوم بعضیا فیلتر میکنن

رو بعضی اپراتور ها وصلم و رو بعضی قطع (گرچه باید بگم که مشکل خیلی زیادی روی تانل ایجاد نشده ظاهرا)

این مشکل برای شما رو اون سرور تستون ایجاد نشده ؟ این رو چجوری میشه رفع کرد اصلا راه حلی داره ؟؟ ممکن هست به خاطر خطای فایروال باشه که اینجوری تضخیص میده ؟؟؟

**Comment by Saleh-Mumtaz** [comment]
درود این مورد ارتباطی با واتروال نداره، برای بنده هم قبلا که اصلا واتروال نبود این مورد پیش اومده بود، گاهی یکیشون جواب نمیداد بعدا هرچهارتا کار پینگ میگرفتن.
