### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by The-Binary-0-1** [radkesvat/WaterWall#18]
سلام وقت بخیر
سرور سمت خارج هر چند ساعت متوقف میشه. این خطا رو میده.     
کانفیگ ریورس ریالیتی هست
Segmentation fault (core dumped)
داخل core همram  ، server رو به client تغییر دادم و worker رو 1 گذاشتم ولی بازم تغییری نکرد.

**Comment by engAmirEng** [comment]
سلام
ورژن؟

**Comment by The-Binary-0-1** [comment]
> سلام ورژن؟

سلام ۰.۹۶

**Comment by radkesvat** [comment]
نسخه جدید هم تست کنید احتمالا دیگه کرش نکنه

**Comment by The-Binary-0-1** [comment]
اوکی. ممنون. گذاشتم تست... اطلاع میدم.

**Comment by The-Binary-0-1** [comment]
دوست عزیز متاسفانه بازم کرش کرد. مدت زمان بیشتری دوام آورد نسبت به نسخه قبل.

**Comment by radkesvat** [comment]
فکر کنم مشکلش رو فهمیدم ؛ نسخه جدید هم به زودی میاد

**Comment by H4m3d84** [comment]
> فکر کنم مشکلش رو فهمیدم ؛ نسخه جدید هم به زودی میاد

تشکر. ظاهرا مشکل ریورس ریلیتی حل شده. از صبح ک برای تست گذاشتمش دیگه قطع نشده...

**Comment by The-Binary-0-1** [comment]
آقا تشکر. مشکل ظاهرا حل شده و از دیروز تا حالا استیبل هست. دمت گرم

**Comment by Saleh-Mumtaz** [comment]
> آقا تشکر. مشکل ظاهرا حل شده و از دیروز تا حالا استیبل هست. دمت گرم

درود فراوان
اگر مشکل حل شده لطفا ایشیو رو ببندید
