### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by AliKh-A** [radkesvat/WaterWall#180]
روی سرور ایران وقتی برنامه رو ران میکنم و به درستی وصل میشه و کانکت میشه بعد از یکی دو ساعت که کار میکنه به صورت اتوماتیک برنامه Killed میشه و وقتی میخوایم دوباره برنامه رو اجرا کنیم خطای اشغال بودن پورت 443 رو میده البته که مشکل اصلی اشغال بودن پورت نیست بلکه از کار افتادن یک دفعه برنامه هست برای من
این باگه یا مشکل خاصی از سرور هست؟ حتی سرور هم یه بار به طور کامل عوض کردم ولی باز این مشکل وجود داره و چند ساعت بیشتر کار نمیکنه
از روش reverse reality استفاده میکنم

**Comment by Saleh-Mumtaz** [comment]
درود ایشیو های قبلی رو بخونید. الان راه حل رو بخاطر ندارم اگرنه حتما همینجا مطرح میکردم.
