### ISSUE TITLE
بررسی ورژن 0.96 ریورس ریلیتی

### ISSUE THREAD

**Issue by H4m3d84** [radkesvat/WaterWall#19]
با سلام. ریورس ریلیتی رو چک کردم. تونل راه اندازی ک میشه همه چیز خوبه اما بعد از گذشت چند دقیقه تا یک ساعت، تونل از کار میافته. دوباره باید از سمت خارج تونل رو ریست کنی تا دوباره فعال شه. نمیدونم مشکل چیه ممنون میشم راهنمایی کنید...
البته من تنها خودم به این سرور متصلم و اینکه وسط کار به سرور دیگه ای وصل شدم. آیا بیکار بودن تونل باعث نمیشه کلا از کار بیافته؟ این مورد به ذهنم رسید گفتم شاید کمکی کنه. ممنون

**Comment by radkesvat** [comment]
نسخه جدید هم اگه توسنتید؛‌ تست کنید و نتیجه رو بگید

**Comment by H4m3d84** [comment]
دروود. اتفاقا همین امروز صبح ورژن جدید رو برای ریورس ریلیتی تست کردم. رو حالتی ک گفته بودید mux هم فعال میشه اصلا جواب نگرفتم. رو حالت اولی که بدون mux هستش بازم بدون مشکل ارتباط برقرار شد اما بعد از یکی دو ساعت از کار افتاد. یعنی وی پی ان رو ک روشن میکنم ارتباطی وجود نداره و پینگ نمیده. اما دقیقا بعد از اینکه از سمت سرور خارج تونل رو ریست کردم ارتباط برگشت....

**Comment by H4m3d84** [comment]
دوباره بعد 20 دقیقه قطع شد... اگر لاگی چیزی لازمه بگید بفرستم

**Comment by radkesvat** [comment]
🤔🤔🤔 

با ماکس اصلا وصل نشد؟ 

نه فعلا لاگی نیاز نیست همبن فیدبک کافیه

**Comment by H4m3d84** [comment]
با ماکس مجدد تست میکنم میگم خدمتتون. چون دیدم وصل نشد سریع رفتم رو روش قبلی. یه بار دیگه تستش کنم میگم

**Comment by H4m3d84** [comment]
اینبار ک تست کردم با mux هم جواب داد فقط با چند ثانیه تاخیر ارتباط برقرار شد (دفعه پیش بهش فرصت ندادم. تا کار نکرد رفتم رو روش قبلی) 
رو حالت سرویس ران کردمش ببینم مثل روش ریورس ریلیتی بدون ماکس بعد از گذشت یه مدت قطع میشه یا نه...

**Comment by H4m3d84** [comment]
ریورس ریلیتی با ماکس هم دقیقا مثل بدون ماکس بعد از چند دقیقه از کار افتاد...
