### ISSUE TITLE
راه ارتیاط با جناب رادکسوت 

### ISSUE THREAD

**Issue by smj1234** [radkesvat/WaterWall#194]
سلام 
دوستان اگر کسی پل ارتیاطی با ایشان دارد که پساخ گو باشند معرفی کند ممنون میشم
در رابطه با اجرای یک پروژه جدید میباشد - سوالی در مورد این پروژه نیست

**Comment by radkesvat** [comment]
من متاسفانه نمیتونم کلا فعالیتی کنم به شخصه چون فورس هستم ؛ ولی درکل در حد مشاوره اگه کمکی از دستم برمیاد در خدمتم

در تلگرام به این ایدی پیام بدید 

@speqtre
