### ISSUE TITLE
تاریخ انتشار

### ISSUE THREAD

**Issue by ZarinNegah** [radkesvat/WaterWall#2]
سلام
خوبین مهندس جان؟
تاریخ انتشار سیستم جدید کی می باشد؟
به صبرانه منتظریم

**Comment by radkesvat** [comment]
سلام ؛‌پیشبینی میکنم از الان حدود ۳ روز دیگه باهاش میشه تونل رو انجام داد (تونل معکوس کلود با قابلیت ریکانکت بدون قطعی)

هم اکنون مستقیمش داره کار میکنه خداروشکر و یکمی جزییاتش مونده که انجام میشه

**Comment by ZarinNegah** [comment]
خداروشکر
بی صبرانه منتظریم

**Comment by danyalfa79** [comment]
سلام مهندس جان ارادت
اینکه اکثر IP های کلودفلر محدود شدن و داستان دارن سر این مورد، اذیتی برای این متد ایجاد نمیکنه؟
و اینکه کاش هم قابلیت دایرکت هم ریورس رو توی کد قرار بدید که یوزر بتونه خودش انتخاب کنه

**Comment by NIKA5050** [comment]
درود بر استاد و خدا قوت .. صرفا خواستیم یه عرض ادبی کرده باشیم تشکر بابت همه زحمات و تلاش های شما :)
بیصبرانه منتظر آپدیت های شما هستیم

**Comment by NIKA5050** [comment]
> سلام ؛‌پیشبینی میکنم از الان حدود ۳ روز دیگه باهاش میشه تونل رو انجام داد (تونل معکوس کلود با قابلیت ریکانکت بدون قطعی)
> 
> هم اکنون مستقیمش داره کار میکنه خداروشکر و یکمی جزییاتش مونده که انجام میشه

درود بر استاد و خدا قوت .. صرفا خواستیم یه عرض ادبی کرده باشیم تشکر بابت همه زحمات و تلاش های شما :)
بیصبرانه منتظر آپدیت های شما هستیم

**Comment by radkesvat** [comment]
سلام من خونه تکونی رو توی این ۳ روز پیشبنی نکرده بودم و یکمی هم مریض شدم ولی مطمعن باشید در اسرع وقت نسخه تونل اش منتشر میشه 😅

**Comment by Saleh-Mumtaz** [comment]
تفریح روزانه من اینه میام تو صفحه waterwall ببینم مهندس علیرضا کامیت جدید انجام داده یا نه

**Comment by radkesvat** [comment]
نسخه اولیه امروز منتشر خواهد شد بالاخره ؛ همونطور که قول دادم فقط ۳ روز طول کشید :)
