### ISSUE TITLE
فیدبک من نسبت به ورژن ۰.۹۸

### ISSUE THREAD

**Issue by Ferixy** [radkesvat/WaterWall#22]
سلام دوباره به dev عزیز

مطمئنم مشکل از منه و از هسته نیست اما کلا خواستم اینو یه گوشه بذارم که document بشه.
آپدیت جدید رو امروز صبح نصب کردم رو سرور هام و دوباره آیپی خارج فیلتر شد.
بعد از ران کردن تانل به ۵ دقیقه هم نکشید که فیلتر بشه سرورم  ]]]]:

ایندفعه برعکس نسخه قبلی که سرور ایران طوری رفتار میکرد انگار داره با سرور خارج حرف میزنه ، ایندفعه واقعاً اتصال داشتن باهم چون به محضی که تانل سرور خارجو قطع کردم سرور ایران ارور داد.
در طول همون ۵ دقیقه ای هم که طول کشید سرور فیلتر بشه اطلاعاتی رد و بدل نمیشد و یوزر نمیتونست از کانفیگ استفاده کنه.
این سرورمم هم مجبور شدم روش از rtt استفاده کنم. فعلا وضعیت همین میمونه تا فردا که وقت کنم دوباره رو هردو جفت سرورام نسخه ۰.۹۴ رو نصب کنم...

باز هم خیلی ممنون ازتون. میدونم پیام من میتونه رو مخ یا ناامید کننده باشه ولی قصدم فقط کمک به توسعه این پروژه هست.

**Comment by radkesvat** [comment]
چه روش تونلی بوده؟

**Comment by radkesvat** [comment]
بعد از کجا معلوم شاید مشکل واقعا از هسته باشه 😅

باید برسی کنیم ببینم چی شده دقیقا ؛ کلا تو ۵ دقیقه فیلتر شدن هم خیلی عجیبه

**Comment by Ferixy** [comment]
[CONF.txt](https://github.com/radkesvat/WaterWall/files/15448873/CONF.txt)
تانل tls h1 مستقیم بدون استفاده از سی دی ان

**Comment by Ferixy** [comment]
سلام. آپدیت جدید باگ فیکسی درباره مشکل من داشته؟ یا فعلا به همون ۰.۹۴ بچسبم؟ واقعاً دیگه آیپی تمیز ندارم اگر فیلتر بشم

**Comment by radkesvat** [comment]
ریورس ها بخصوص ریورس ریلیتی رو تست کنید ؛ درمورد فیلتر شدن یا نشدن ورژن ها فرقی نثبت به هم ندارن چه 0.94 و 0.96 و یا حتی نسخه اخر...

نسخه اخر باگ ها روش فیکس شدن که کرش نکنه

**Comment by Ferixy** [comment]
سلام اپدیت جدیدو ۵۰ بار با حالت های مختلف از قبیل دایرکت ایچ وان و ایچ دو ، ریورس ایچ ران کردم با پورت و ایپی های مختلف. اطلاعات به پنل نمیرسه که اینترنت یوزر بتونه کار کنه

**Comment by Ferixy** [comment]
احسا میکنم عقب مونده هستم

**Comment by Ferixy** [comment]
از ساعت ۱۲ داشتم باهاش ور مبرفتم. الان ۴:۳۰ هست.

**Comment by radkesvat** [comment]
نه ؛ یکمی داکیومنت ها سریع از روی مسایل رد شد خودم هم حس میکنم کامل توضیح ندادم 

میام تل با هم چک میکنیم فردا (بعد از مدت ها 🤣)

**Comment by H4m3d84** [comment]
من ریورس ریلیتی رو تست کردم درست شده. یک روز هستش که روشنه و داره جواب میده. بنظرم یک بار از اول انجام بده شاید یه جایی سوتی دادی (مثلا رو یکی از سرورهات ورژن آخر رو ریختی، رو اون یکی سرور نه!)

**Comment by NIKA5050** [comment]
> [CONF.txt](https://github.com/radkesvat/WaterWall/files/15448873/CONF.txt) تانل tls h1 مستقیم بدون استفاده از سی دی ان

میشه فایل core هم بزارید ؟

**Comment by Ferixy** [comment]
> > [CONF.txt](https://github.com/radkesvat/WaterWall/files/15448873/CONF.txt) تانل tls h1 مستقیم بدون استفاده از سی دی ان
> 
> میشه فایل core هم بزارید ؟

دقیقا همون template اصلی هست فقط اسم فایل کانفیگ عوض شده

**Comment by Ferixy** [comment]
> من ریورس ریلیتی رو تست کردم درست شده. یک روز هستش که روشنه و داره جواب میده. بنظرم یک بار از اول انجام بده شاید یه جایی سوتی دادی (مثلا رو یکی از سرورهات ورژن آخر رو ریختی، رو اون یکی سرور نه!)

من ریورس ریلیتی رو اصلا تست نکردم. ریورس h2 و دایرکت h1 و h2 رو تست کردم. مشکلی که شما گفتید هم غیر ممکنه رخ بده چون هسته رو چندبار پاک کردم و دوباره دانلود کردم

**Comment by Saleh-Mumtaz** [comment]
> > من ریورس ریلیتی رو تست کردم درست شده. یک روز هستش که روشنه و داره جواب میده. بنظرم یک بار از اول انجام بده شاید یه جایی سوتی دادی (مثلا رو یکی از سرورهات ورژن آخر رو ریختی، رو اون یکی سرور نه!)
> 
> من ریورس ریلیتی رو اصلا تست نکردم. ریورس h2 و دایرکت h1 و h2 رو تست کردم. مشکلی که شما گفتید هم غیر ممکنه رخ بده چون هسته رو چندبار پاک کردم و دوباره دانلود کردم

درود بزرگوار، در روزهای آتی نسخه جدید برنامه قرار خواهد گرفت، اگر مسئله ای نیست ایشیو رو در حالت بسته شده قرار بدم.
