### ISSUE TITLE
قطع شدن تانل

### ISSUE THREAD

**Issue by Vatani78** [radkesvat/WaterWall#23]
درود
ریورس و ریلیتی ریوس رو تست کردم همه چی اوکی بود ولی بعد از چند دقیقه تانل قطع میشه.
تی ال اس تانل هم متاسفانه برای من کار نکرد.

**Comment by radkesvat** [comment]
باگ ریورس حل شده احتمال خیلی زیاد روی نسخه ای که به زودی میزارم

**Comment by Saleh-Mumtaz** [comment]
> باگ ریورس حل شده احتمال خیلی زیاد روی نسخه ای که به زودی میزارم

درود بر مهندس عزیز
اجرای RTT به وسیله واتروال رو گذاشتید،  RTCF رو چگونه با واتروال اجرا کنیم؟ ایا این امکان در واتروال ایمپلمنت شده ؟

**Comment by radkesvat** [comment]
بله اونم میشه وقت کنم داکیومنت میزارم، فعلا با چند نفر از دوستان که بهتره اسمشو نیارم وبرای امنیت خودشون و من که واقعا دمشون گرم، شدیدا مشغول تست هستیم که باگ های تونل زود تر رفع بشن

**Comment by nika1367** [comment]
> بله اونم میشه وقت کنم داکیومنت میزارم، فعلا با چند نفر از دوستان که بهتره اسمشو نیارم وبرای امنیت خودشون و من که واقعا دمشون گرم، شدیدا مشغول تست هستیم که باگ های تونل زود تر رفع بشن

شرمنده چطور میشه waterwall سرویس تعریف کرد بعد ریبوت سرور ران بشه .. چنتا کرونجاب و local تعریف کردم نشد میشه راهنمایی بفرمایید

**Comment by Saleh-Mumtaz** [comment]
> درود ریورس و ریلیتی ریوس رو تست کردم همه چی اوکی بود ولی بعد از چند دقیقه تانل قطع میشه. تی ال اس تانل هم متاسفانه برای من کار نکرد.

درود بزرگوار
روی نسخه جدیو تانل ریورس پایدار شده اگر مشکل شما هم حل شده ایشیو رو لطفا ببندید.
