### ISSUE TITLE
اشکال در ورژن 99 بتا

### ISSUE THREAD

**Issue by rezhacker** [radkesvat/WaterWall#24]
سلام من از حالت trojan direct استفاده میکنم
بعد از چند دقیقه استفاده خطای زیر نمایش داده میشه پشت سر هم

2024-05-28 07:49:55.319 ERROR 0038795BFF7E0000:error:0A000119:SSL routines:tls_get_more_records:decryption failed or bad record mac:../openssl-source-src/ssl/record/methods/tls_common.c:859:
0038795BFF7E0000:error:0A000139:SSL routines::record layer failure:../openssl-source-src/ssl/record/rec_layer_s3.c:692:

البته ارتباط قطع نمیشه ولی این خطا باعث بالا رفتن مصرف سی پی یو و رم میشه.

**Comment by radkesvat** [comment]
نه این مشکلی نداره، طبیعیه و جای نگرانی نیست، دلیلی بر افزایش cpu هم اصلا نیست خیالتون راحت


اگه مثلا ۱۰۰۰ بار پشت سر هم اینو نوشت، اونوقت معنیش اینه یکی داره اتک دیداس میزنه به سرورتون ولی عموما همچین چیزی پیش نمیاد

**Comment by rezhacker** [comment]
درسته. احتمالا اتک ddos میزنن. من میتونم به جای پورت 443 یک پورت دیگه استفاده کنم تا این اتفاق پیش نیاد؟

**Comment by radkesvat** [comment]
اره ولی پیشناهاد نمیکنم

ابن باید برسی بشه راه های مختلفی هست مثلا وقتی دارید دیداس میشید شبکه رو مانیتور کنید ببینید کدوم ایپی داره به سمتتون ترافیک سنگین میفرسته، اگه بانت نت سنگینی نباشه میتونید دستی ایپی هاشو بلاک کنید با ایپی تیبل یا ufw, اگرم کلا میخواید خلاص شید میتونید داخل فایروال پورت۴۴۳ رو تنطیم کنید که فقط از ایران بهش وصل شد... یا راه های دیگه که زیادن ولی خوب من خودم باشم اولی رو میزنم.

**Comment by rezhacker** [comment]
ممنون از راهنمایی شما
