### ISSUE TITLE
اجرای برنامه بعد ریبوت

### ISSUE THREAD

**Issue by nika1367** [radkesvat/WaterWall#25]
دوستان سلام چند سرویس و کرونجاب تعریف کردم که بعد ریبوت واتروال ران بشه ولی موفقیت آمیز نبوده لطفا بفرمایید برای بعد ریبوت سرور چه دستوری اجرا کردید با تشکر

**Comment by EbadiDev** [comment]
به عنوان سرویس اجراش کن کاری که من کردم :
فایل باینری Waterwall من در مسیر /root قرار داره
یه فایل bash script درست کردم که اون رو به عنوان سرویس اجرا کنم ( مستقیم نتونستم خوده waterwall رو اجرا کنم به عنوان سرویس )
water.sh : 
```bash
#!/bin/bash
WATERWALL_PATH="/root/Waterwall" # مسیر فایل


if [ ! -x "$WATERWALL_PATH" ]; then
    echo "Error: $WATERWALL_PATH does not exist or is not executable."
    exit 1
fi

$WATERWALL_PATH

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    echo "Error: Waterwall program exited with code $EXIT_CODE."
    exit $EXIT_CODE
fi

echo "Waterwall program executed successfully."
```
دادن همه دسترسی ها : 
```bash 
chmod +x /root/water.sh 
```
ساخت سرویس : 

```bash
vim /usr/lib/systemd/system/water.service
```

```bash
[Unit]
Description=watter_wall
After=network.target
Wants=network.target

[Service]
Type=simple
WorkingDirectory=/root/
ExecStart=/root/water.sh 
Restart=always
RestartSec=86400  
LimitNOFILE=infinity
StandardOutput=null
StandardError=null

[Install]
WantedBy=multi-user.target
```
اجرای سرویس : 
```bash
systemctl daemon-reload && systemctl enable water && systemctl restart water && systemctl status water
```

ریستارت سرویس هر 12 ساعت : 
```bash
crontab -e
```

```
0 */12 * * * /bin/systemctl restart water
```

**Comment by H4m3d84** [comment]
خودش رو هم میشه به عنوان سرویس اجرا کرد. چطوری برای شما نشده؟ برای من ک جواب داد

**Comment by Saleh-Mumtaz** [comment]
> دوستان سلام چند سرویس و کرونجاب تعریف کردم که بعد ریبوت واتروال ران بشه ولی موفقیت آمیز نبوده لطفا بفرمایید برای بعد ریبوت سرور چه دستوری اجرا کردید با تشکر

درود بر شما دوست عزیز
اگر پاسخ سوالتون رو گرفتید لطفا ایشیو رو ببندید، نحوه سرویس اجرا کردن واتروال مثل RTT هست
