### ISSUE TITLE
فیدبک نسخه 0.99  و گزارش مشکلاتی در برخی دیتاسنترها

### ISSUE THREAD

**Issue by Gholamreza29** [radkesvat/WaterWall#26]
با سلام و خسته نباشید
بدون حرف اضافه سریعا میرم سراغ فیدبک خودم که فقط یک یوزر خودم تنها بودم
من ریلیتی ریورس رو چک کردم برای مدت زمان حدودی نصف روز
با دیتاسنتر هاست ایران شبکه زیرساخت اوکی بود از نظر سرعت و همه چیز 
اما با دیتاسنتر امین اگرچه وصل میشه اما اصلا سرعت خوبی نداشت این درحالیه که با استفاده از ریورسی که داخل خود پنل هست و روش ریلیتی بدون مشکل و با سرعت خوب وصل میشه جالبه که اگر کانفیگ رو عوض میکردم و یک کانفیگ tls دار برای ریورس پنل به پنل استفاده میکردم دیگه اصلا وصل نمیشد. ممکنه شباهت هایی بین ریلتی شما و کانفیگ tls دار باشه که باعث میشه یا وصل نشه یا کند باشه که بنظر جای بررسی داره. اینا رو  نوشتم شاید بدرد کسی بخوره و اگر مشکل مشابهی داشت شاید با عوض کردن دیتاسنتر اوکی بشه.
و در نهایت یه سوال روش ریورس  شما در حال حاظر چه مزیت هایی نسبت به ریورس خود پنل داره؟

**Comment by radkesvat** [comment]
مزیت خاصی نداره شاید فقط cpu کمتر مصرف کنه، کلا اینارو دارم برای سرگرمی درست میکنم و اگه ایده به ذهنم رسید بعدا روش اضافه کنم

**Comment by Saleh-Mumtaz** [comment]
> مزیت خاصی نداره شاید فقط cpu کمتر مصرف کنه، کلا اینارو دارم برای سرگرمی درست میکنم و اگه ایده به ذهنم رسید بعدا روش اضافه کنم

 مهندس واقعا بی مزیت نیست، نصب پنل روی سرورها میتونه مختل بشه همونطور که در ابراروان دیده بودیم، همچنین نصب پنل باعث میشه موضوع دور زدن فیلترینگ واضح بشه برای ارائه دهنده، واتروال رو میشه اسمش رو عوض کرد و چندین روش برای ریورس داره، به نظر من مهمترینش RTCF خواهد بود.
