### ISSUE TITLE
مشکل در Reverse tls

### ISSUE THREAD

**Issue by NIKA5050** [radkesvat/WaterWall#27]
سلام خدمت عزیزان..
اول خدمتتون بگن دامنه و سرور مجازیم کاملا تمیز می باشد.
طبق داکیومنت اقدام کردم اول روی سرور خارجم سرت گرفتم و دو فایل key و chain به سرور ایران انتقال دادم و ادرس دو فایل رو داخل سرور ایرانم تو فایل کانفیگ وارد کردم  /root/cert/****/privkey.pem 
و آدرس سرور خارج جای 2.2.2.2 وارد کردم..

روی سرور خارج هم قسمت mydomain را ساب دامین که براش سرت گرفتم وارد کردم و جای 1.1.1.1 سرور ایران وارد کردم و چیزه دیگه هم نبود ست کنم و از طریق مالتی پورت اقدام کردم ولی پنل بالا نمیاد ؟! دوستان لطفا اگه فایل کانفینگ این متد دارن قرار بدند چون من روی روش پورت تو پورت جواب گرفتم ولی روی ریورس نه چه نوع ساده چه tls
2024-05-30 22:45:08.513 WARN  reverseServer: no peer left, waiting tid: 0
2024-05-30 22:45:08.534 DEBUG TcpListener: Accepted FD:e  [**.**.**.**:443] <= [**.**.**.**:55258]
2024-05-30 22:45:08.534 WARN  reverseServer: no peer left, waiting tid: 1
2024-05-30 22:45:13.347 DEBUG TcpListener: received close for FD:11
2024-05-30 22:45:13.415 DEBUG TcpListener: Accepted FD:11  [**.**.**.**:2362] <= [**.**.**.**:22715]
2024-05-30 22:45:13.415 WARN  reverseServer: no peer left, waiting tid: 0

**Comment by radkesvat** [comment]
فایل کانفیگ سرور ایران و خرج هم قراربدین و میتونید توش دامنه و ایپی رو فرضی بزارید.

این لاگی که فرستاید از سرور ایران هست که میگه سرور خارج هنوز بهش ارتباط نگرفته، دقت کنید ایپی سرور خارج رو باید در کانفیگ فایل سرور ایران بخش whitelist بزارید

**Comment by NIKA5050** [comment]
> فایل کانفیگ سرور ایران و خرج هم قراربدین و میتونید توش دامنه و ایپی رو فرضی بزارید.
> 
> این لاگی که فرستاید از سرور ایران هست که میگه سرور خارج هنوز بهش ارتباط نگرفته، دقت کنید ایپی سرور خارج رو باید در کانفیگ فایل سرور ایران بخش whitelist بزارید

درود بر شما 
ایپی ایران رو پشت ساب دامین گذاشتم داخل کلاد و با گزینه xui روی سرور خارج برای این ساب دامین سرت گرفتم و انتقال دادم روی سرور ایران..
پورت پنل هم 2083 گزاشتم ..
این هم فایل سرور ایران و خارج 
[conf-ir.json.txt](https://github.com/radkesvat/WaterWall/files/15505916/conf-ir.json.txt)
[conf-kh.json.txt](https://github.com/radkesvat/WaterWall/files/15505917/conf-kh.json.txt)

**Comment by radkesvat** [comment]
اگه اومدین اتصال سرور خارج به ایران رو از کلود عبور دادین ؛ در فایل سرور ایران باید ایپی های کلود فلیرو وایت لیست کنید ؛ کانفیگش اینجوری میشه


داخل کانفیگ فایل سرور ایران این تغییرو باید بدید در آخرین نود:
```
   {
            "name": "inbound_server_kharej",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": 443,
                "nodelay": true,
                "whitlelist": [
                    "173.245.48.0/20",
                    "103.21.244.0/22",
                    "103.22.200.0/22",
                    "103.31.4.0/22",
                    "141.101.64.0/18",
                    "108.162.192.0/18",
                    "190.93.240.0/20",
                    "188.114.96.0/20",
                    "197.234.240.0/22",
                    "198.41.128.0/17",
                    "162.158.0.0/15",
                    "104.16.0.0/13",
                    "104.24.0.0/14",
                    "172.64.0.0/13",
                    "131.0.72.0/22"
                ]
            },
            "next": "sslserver"
        }
```

**Comment by radkesvat** [comment]
[conf-ir.json.txt](https://github.com/user-attachments/files/15513254/conf-ir.json.txt)

**Comment by radkesvat** [comment]
در فایل کانفیگ سرور خارج هم فقط دامنه وارد کنید ؛ ایپی سرور ایران رو دستی وارد نکنید اگه میخواید از کلود رد بشه

**Comment by radkesvat** [comment]
اگه از تو پروکسی رد نکردید پس این نیازی نیست ؛ ایپی خود سرور خارج رو whitelist کنید

**Comment by NIKA5050** [comment]
> اگه از تو پروکسی رد نکردید پس این نیازی نیست ؛ ایپی خود سرور خارج رو whitelist کنید

استاد همین کار کردم نمیش باز ..
من ایپی ایرانمو روی کلاد بردم و براش ساب دامین گذاشتم .. بعد هم روی سرورخارجم برای این ساب دامین سرت گرفتم که انتقالش دادم روی سرور ایرانم در روت.. ولی باز اجرا میکنم اینو میگه

**Comment by Saleh-Mumtaz** [comment]
> > اگه از تو پروکسی رد نکردید پس این نیازی نیست ؛ ایپی خود سرور خارج رو whitelist کنید
> 
> استاد همین کار کردم نمیش باز .. من ایپی ایرانمو روی کلاد بردم و براش ساب دامین گذاشتم .. بعد هم روی سرورخارجم برای این ساب دامین سرت گرفتم که انتقالش دادم روی سرور ایرانم در روت.. ولی باز اجرا میکنم اینو میگه

من حدس میزنم شما سرور خارجتون ایپیش مناسب Reverse TLS نیست، به این معنا که یک دیتاسنتر معروف هست و ایپیش برای اتصال به سرور داخلی مسدود شده، البته این فقط در صورتی درسته که کانفیگ شما بدون ایراد باشه.
تجربه من از ‌RTT این بود که روی دیتاسنترهای بامداد و شهریار آروان ایپی های Aeza برای این روش کار نمیکردند ولی روی دیتاسنتر های سیمین و فروغ بدون مشکل بود، البته این تجربه مال چندین ماه پیش هست.
