### ISSUE TITLE
گوش کردن اکس ری به پورت با آیپی ورژن ۶

### ISSUE THREAD

**Issue by Ferixy** [radkesvat/WaterWall#29]
سلام من بلاخره فهمیدم چرا ارتباط تانل برقرار میشه ولی کانفیگ یوزر کار نمیکنه. بخاطر این هست که اکس ری به دلایلی برای من داره به آیپی ۶ بجای وی ۴ گوش میده. من کانفیگ خارج رو ادیت کردم که بجای "address": "127.0.0.1", از "address": "::1", استفاده کنه اما چه با براکت و چه بدون براکت اطلاعات به اکس ری نمیرسه.
من سرورم آیپی وی ۶ نداره اما هتزنر برای همه سروراش یدونه آیپی وی ۶ Link-Local میذاره. خودتونم الان کامند ip a رو توی سرور هتزنرتون که وی ۶ نداره بزنید میتونید به این موضوع پی ببرید. 
این اتفاق بعد از عوض کردن آیپی پرایمری سرورم رخ داد که نشون میده vm manager هتزنر یه جایی رو دست زده که اینطوریه. من الان به تاتل چطوری بفهمونم که اطلاعات رو به لوکال هاست وی ۶ برسونه?

ممنونم.
![photo_2024-06-03_01-59-23](https://github.com/radkesvat/WaterWall/assets/77561374/06c532d7-e72e-471a-8866-697d30f3e5ee)

**Comment by Ferixy** [comment]
عجیبه من توی rtt آدرس لوکال هاست رو 127.0.0.1 میزنم اطلاعات به هسته میرسه...

**Comment by Ferixy** [comment]
کسی نیست کمک کنه؟

**Comment by radkesvat** [comment]
سلام من که سرکارم😫

باید بیام اپدیت بعدی رو تموم کنم بعد دیباگ کنیم، من دفعه قبل که کانفیگت رو چک کردم پورت ها درست نبود، به جز این باید ایپی ها و چک کنی و لاگ رو برسی کنی، تو لاگ جزییات خوبی میزاره

**Comment by radkesvat** [comment]
فعلا هم سعی کن از ایپی ۶ استفاده نکنی چون چک نکردم درست کار میکنه یا نه

**Comment by Ferixy** [comment]
> سلام من که سرکارم😫
> 
> باید بیام اپدیت بعدی رو تموم کنم بعد دیباگ کنیم، من دفعه قبل که کانفیگت رو چک کردم پورت ها درست نبود، به جز این باید ایپی ها و چک کنی و لاگ رو برسی کنی، تو لاگ جزییات خوبی میزاره 

میدونم. واقعا شخمیه سرکار رفتن. درکت میکمم. و اینو بدون قدردان همه کارایی که میکنی هستم و هستیم.

اون قضیه پورت ها هم من همیشه رعایت میکردم و حواسم بوده فقط اون باری که فرستادم برات دقیقا عین داکیومنت پیش رفتم و اون هم به دلایلی شاید بخاطر اشتباه تایپی داشت از همه طرف پورت ۴۴۳ استفاده میکرد برای همین فکر کردم تو اپدیت جدی مثل rtt یکاری کردی که‌پورت تکراری بشه استفاده.

دست خودمم نیست که اکس ری داره از وی ۶ استفاده میکنه. سرورم اصلا وی ۶ نداره و اکس ری هم تنظیمات بخصوصی برای این نداره. همونطور که گفتم وقتی داخل پنل هتزنر آیپی سرورو چنج کردم این مشکل برای هردو سرورام پیش اومد ]: 

هنوز دارم از rtt استفاده میکنم خیلی قطعی داره ولی یکم محدودیتاشو سعی کردم کمتر کنم.
اول از همه سیپیو سرور خارجمو dedicated کردم. بعد لیمیت های لینوکس که برای پراسس ها میذاره رو کلا برداشتم که همون بدونه thread رتت بدبخت یکم ازادانه تر بتونه کار کنه. کانکشن ایج هم ۱۸۰۰ کردم. فعلا داره **به زور** کار میکنه برام. خواستم HAPROXY هم استفاده کنم ولی مثل اینکه مشکل داره با رتت(اونطور که داخل گیتهاب رتت خوندم)


من آماده ارائه هر کمک یا همکاری سر این باگ waterwall که اطلاعات رو نمیتونه به اکس ری برسونه هستم...

**Comment by Ferixy** [comment]
چرا ایشیو رو میبندید وقتی باگ هنوز فیکس نشده?

**Comment by Saleh-Mumtaz** [comment]
> چرا ایشیو رو میبندید وقتی باگ هنوز فیکس نشده?

مهندس میخواست کلا کلین اپ کنه همه این ها پاک بشن، من ایشیو هارو بستم که بمونن، بعد از اینکه ورژن جدید منتشر شد چک کنید ببینید باز هم مشکل هست یا نه که اگر بود دوباره باز بشه
