### ISSUE TITLE
نصب

### ISSUE THREAD

**Issue by xmohammad1** [radkesvat/WaterWall#31]
سلام وقت بخیر
برای نصب هسته چطوری باید پیش برم؟ فقط پروژه رو کلون کنم داخل سرور یا چی

**Comment by H4m3d84** [comment]
با wget دانلودش کن روی سرور بعد unzipش کن بعدم با chmod +x بهش قابلیت اجرایی بده:

wget https://github.com/radkesvat/WaterWall/releases/download/v0.99/Waterwall-linux-64.zip
apt install unzip
unzip Waterwall-linux-64.zip
chmod +x Waterwall
