### ISSUE TITLE
Reality Reverse Tunnel

### ISSUE THREAD

**Issue by xmohammad1** [radkesvat/WaterWall#32]
سلام وقت بخیر خسته نباشید
من با این روش Reality Reverse Tunnel تانل زدم ولی پینگ زیاد ثبات نداره مثلا از 400 تا 1300 اینا جا به جا میشه میخواستم ببینم چطوری میشه بهترش کرد یا روش دیگه ام وجود داره که ممکنه بهتر از این کار کنه؟
و اینکه sni رو www.speedtest.net گذاشتم ایا این میتونه تاثیر گذار باشه؟

**Comment by radkesvat** [comment]
این مشکل احتمال زیاد بعد از اضافه شدن halfduplex حل میشه (در نسخه بعد)

**Comment by xmohammad1** [comment]
اگه میششه زودتر منتشر کنید بقیه روش های تانل داره خیلی محدود میشه

**Comment by NIKA5050** [comment]
> اگه میششه زودتر منتشر کنید بقیه روش های تانل داره خیلی محدود میشه با سپاس

با سپاس از استاد و XMOHAMMAD بابت نکات خوب ..
