### ISSUE TITLE
استفاده از چندین سرور داخلی

### ISSUE THREAD

**Issue by swifast** [radkesvat/WaterWall#33]
سلام خسته نباشید ممنونم از تمام زحماتتون و پروژه‌هایی که این مدت ارائه دادید واقعاً بدون اونها امکان استفاده از نت نبود.
میشه لطفاً طریقه وصل کردن 2 یا 3 سرور ایران به یک سرور خارج رو در روش Reality Reverse Tunnel توضیح بدید؟

**Comment by radkesvat** [comment]
وصل کردن چند سرور ایران به خارج خیلی ساده هست ؛ کافیه کانفیگ فایل سرور خارج که json هست را چند بار کپی کنید برای هر سرور خارج یک بار ؛ کل node هارو برای هر سرور خارج کپی کنید ؛ اگه متوجه نشدید داکیومنت خواهم کرد اینارو

**Comment by swifast** [comment]
خیلی ممنونم، بعد توی نودهای سرورهای دوم اسم‌ نودها تکراری باشه (مثل سرور اول باشه) مشکلی پیش نمیاد؟ یا باید اسم جدید بزنیم؟

**Comment by radkesvat** [comment]
بهتون ارور میده node map اگه اسمشو تکراری باشه ؛ بهتره اخر اسمشون اینجوری مثلا 

> _server_1

یا یه همچین چیزی اضافه کنید که خوانا تر هم بشه
