### ISSUE TITLE
question about local ipv6

### ISSUE THREAD

**Issue by xmohammad1** [radkesvat/WaterWall#34]
سلام وقت بخیر
 ایا میشه بجای ای پی اصلی سرور با ipv6 لوکال هم تانل رو برقرار کرد؟

**Comment by radkesvat** [comment]
تست نکردم ولی فکر نمیکنم مشکلی باشه

**Comment by radkesvat** [comment]
اها یادم رفت بگم ؛ در حال حاظر ایپی 6 ساپورتش غیر فعال شده چون تست نکرده بودم کلا disable کردم ؛ قول نمیدم تو این نسخه ولی در نسخه های بعد حتما فعالش میکنم
