### ISSUE TITLE
آیا پینگ در waterwall  رفع شده ؟ برخلاف روش ریورس؟

### ISSUE THREAD

**Issue by mohama226** [radkesvat/WaterWall#35]
سلام وقت بخیر
در این سناریو water wall دیگه پینگ مشکل نوسان نداره ؟ و قطع و وصلی های ناشی از بالا رفتن پینگ که در روش ریورس بود مشکلش رفع شده ؟ 

باتشکر

**Comment by radkesvat** [comment]
مشکل پرفورمنس یا ترد نداره ولی هنوز کد نویسی اش کامل تموم نشده ؛ نسخه بعد میشه حالت ایده الش ولی الانم کار میکنه منتهی پینگ ممکنه بازی کنه و این طبیعیه؛
