### ISSUE TITLE
آموزش نصب اولیه

### ISSUE THREAD

**Issue by hatinati2** [radkesvat/WaterWall#36]
سلام وقت بخیر
با تشکر از شما 
به نظرم خیلی ها هنوز کامند های نصب اولیه پروژه روی سرور بلد نیستن فکر کنم این آموزش به دردشان بخورد
کامند اول
wget https://github.com/radkesvat/WaterWall/releases/download/vx.x/Waterwall-linux-64.zip

کامند دوم
apt install unzip && unzip Waterwall-linux-64.zip

کامند سوم
chmod +rwx Waterwall

سپس طبق آموزش های بخش wikiبه آدرس   ((https://radkesvat.github.io/WaterWall-Docs/)) کانفیگ و اجرا

**Comment by Saleh-Mumtaz** [comment]
درود فراوان، دادن دسترسی های مورد نیاز رو هم یادتون نره
chmod +rwx Waterwall

**Comment by Saleh-Mumtaz** [comment]
```bash
bash <(curl -Ls https://raw.githubusercontent.com/xmohammad1/Waterwall-RRT/main/setup.sh)```
اسکریپت آقای محمد برای راه اندازه RTT به وسیله واتروال

**Comment by Saleh-Mumtaz** [comment]
https://youtu.be/fKvn9g7oOXg?si=Wh2D-ArHXKfnkiDA

**Comment by hiva005** [comment]
سلام وقت بخر
در روشReverse Tls و Http2 قسمت header جی باید وارد کنیم

**Comment by hatinati2** [comment]
> سلام وقت بخر در روشReverse Tls و Http2 قسمت header جی باید وارد کنیم و برای سرور ایران و خارج باید سرتیفیکیت جدا گرفت؟

در قسمت ویکی پروژه توضیحات کامل هر مدل تانل وجود دارد

https://github.com/radkesvat/WaterWall/wiki

**Comment by Zaxel-Test** [comment]
دوستان HalfDuplex فیکس شده کامل ؟
بعد راهی هست بعد از ریست شدن یا به هر دلیلی ./Waterwall استاپ شده خودش ران بشه 
مثال سرور من هر شب ریست میشه راهی هست اتوماتیک بعد ریستارت استارت بشه ؟

**Comment by Saleh-Mumtaz** [comment]
به صورت سرویس اجرا کنید

**Comment by Saleh-Mumtaz** [comment]
```
cd /etc/systemd/system
```
```
vi waterwall.service
```

```
[Unit]
WaterWall

[Service]
Type=idle
User=root
WorkingDirectory=/root
ExecStart=/root/Waterwall
Restart=always

[Install]
WantedBy=multi-user.target
```
```
sudo systemctl daemon-reload
```
```
sudo systemctl start waterwall.service
```
```
sudo systemctl enable waterwall.service
```
چک کردن وضعیت
```
sudo systemctl status waterwall.service
```
توقف و غیرفعال کردن
```
sudo systemctl stop waterwall.service
```
```
sudo systemctl disable waterwall.service
```

**Comment by Saleh-Mumtaz** [comment]
https://github.com/radkesvat/WaterWall-Docs/ مخزن حاوی اموزش های ویکی

**Comment by Saleh-Mumtaz** [comment]
```
https://github.com/persian-michael-scott/Waterwall-RRT/blob/main/RRT_MUX.sh
```
اسکریپت دیگری از اقای پرشین مایکل اسکات
