### ISSUE TITLE
TLS Tunnel (http2 , mux , grpc)

### ISSUE THREAD

**Issue by xmohammad1** [radkesvat/WaterWall#37]
سلام وقت بخیر خوبین؟
من در مورد کانفیگ این یکم سوال داشتم
https://github.com/radkesvat/WaterWall/wiki/7-%E2%80%90-http2-,-mux-,-grpc#%D8%A7%D8%B9%D9%85%D8%A7%D9%84-%D8%B1%D9%88%DB%8C-tls-tunnel
ایا میتونه این روش مولتی پورت ام باشه؟
ما لازمه دامنمون رو هم تو قسمت کانفیگ بنویسیم؟ اگه اره کدوم قسمت دقیقا و اینکه دامنه ای که ای پی سرور ایران روش هستو باید بنویسیم یا دامنه سرور خارج 
و اینکه بجای SSL هایی که certbot میگیره میشه از openssl ام استفاده کرد؟ مثلا به این صورت بگیریم
openssl req -newkey rsa:2048 -nodes -keyout "privkey.pem" -x509 -days 365 -out "fullchain.pem" -subj "/CN=$DOMAIN"
و یا مثلا از cert هایی که از داخل کلودفلر میگیریم میتونیم  استفاده کنیم؟

**Comment by radkesvat** [comment]
جواب هردوش بله هست ؛ برای مولتی پورت باید header node هم اضافه کنید جاش هم مهمه که بعد سوکت باشه

**Comment by xmohammad1** [comment]
امکانش هست یه کانفیگ مولتی پورت قرار بدید چون داخل اموزش نبود , ممنون
