### ISSUE TITLE
reverse reality tunnel

### ISSUE THREAD

**Issue by falloffsudo21** [radkesvat/WaterWall#38]
من از روش reality reverse tunnel طبق داكيومنت رفتم جلو ولي سمت خارج اين ارور رو كرفتم

![IMG_0658](https://github.com/radkesvat/WaterWall/assets/171876872/df7a8dda-2dc0-40f8-8caf-792fb93feae2)

**Comment by xmohammad1** [comment]
اسکریپت منو تست کنید

**Comment by xmohammad1** [comment]
```
bash <(curl -Ls https://raw.githubusercontent.com/xmohammad1/Waterwall-RRT/main/setup.sh)
```

**Comment by radkesvat** [comment]
توی فایل json پورت رو داخل کوتیشن نزارید 

غلط:
> port : "443"

درست:

> port : 443

**Comment by Saleh-Mumtaz** [comment]
> من از روش reality reverse tunnel طبق داكيومنت رفتم جلو ولي سمت خارج اين ارور رو كرفتم
> 
> ![IMG_0658](https://private-user-images.githubusercontent.com/171876872/337039308-df7a8dda-2dc0-40f8-8caf-792fb93feae2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTY2MDUsIm5iZiI6MTcxNzg1NjMwNSwicGF0aCI6Ii8xNzE4NzY4NzIvMzM3MDM5MzA4LWRmN2E4ZGRhLTJkYzAtNDBmOC04Y2FmLTc5MmZiOTNmZWFlMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTQxODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVkY2JiZTcxYzYzMmZiZGI5NTdlYjk3Y2M4NjQ2OThkNTZkZDQyNDU0YWY4MmVhMThhOWRhZjU1MGUxYTY1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lXDjstR9yAESEVwGebVaG2sIT541nZJgZWLkwbj68-s)

درود بر شما، اگر مشکل شما حل شده لطفا ایشیو رو ببندید

**Comment by NIKA5050** [comment]
> اسکریپت منو تست کنید

اقا محمد تونستید بروزرسانی های خود را ادامه بدید و متدهای دیگرهم پیاده کنید من همچنان با روش  ریورس Tls و Http2 مشکل دارم نتونستم راش بندازم رو مخم رفته .. با تشکر

**Comment by Saleh-Mumtaz** [comment]
> > اسکریپت منو تست کنید
> 
> اقا محمد تونستید بروزرسانی های خود را ادامه بدید و متدهای دیگرهم پیاده کنید من همچنان با روش ریورس Tls و Http2 مشکل دارم نتونستم راش بندازم رو مخم رفته .. با تشکر

این ایشیو رو میبندم، اما ایشیو شما باز هست در اونجا کمی بیشتر جزئیات بفرستید.
