### ISSUE TITLE
Load balancing

### ISSUE THREAD

**Issue by xmohammad1** [radkesvat/WaterWall#39]
سلام وقت بخیر 
من میخواستم با haproxy یه شبکه لود بالانس بسازم که مثلا دو یا سه نوع تانل همزمان داشته باشم   ، بعد براش تعیین کنم اگه تانل دایرکت به مشکل خورد داده ها ارسال بشه به ریورس 
بنظرتون همچین چیزی امکان پذیره؟ اگه امکانش هست یه مثال کوچیک از کانفیگ کردنش برام بزارید برای مولتی پورت ام میخوام فعلا دوتا تانلی که در نظر دارم یکی reality direct tunnel و یکی reality reverse tunnel

**Comment by radkesvat** [comment]
سلام والا من نمیدونم این رو 

الان بیشتر وقتم درگیر فکر و رسوندن اپدیت اخر این پروژه هست که خیلی دیر شده ؛ اگه چیزی دستگیرم شد یا سوال دیگه ای داشتین بگین حتما کمک میکنم
