### ISSUE TITLE
خطای Unable to locate package

### ISSUE THREAD

**Issue by nika1367** [radkesvat/WaterWall#4]
سلام و خسته نباشید خدمت شما. هنگام نصب پکیج در اوبونتو با خطای زیر رو به رو میشوم. نسخه 20 و 22 همه دستورات آپدیت هم اجرا کردم ولی بازم این ارور میده E: Unable to locate package

**Comment by radkesvat** [comment]
نصب چی ؟ هنوز اکسریپت نصب نداره این پروژه ؛ اگه منظورتون پروژه قبلی هست باید 
apt-get install unzip

اینو نصب کنید ؛ شاید ریپازیتوری سرورتون دامنه هاش درست نیستن 


> nano /etc/apt/sources.list

**Comment by nika1367** [comment]
> ریپازیتوری سرورتون دامنه هاش درست نیستن

استاد چک کردم ریپازیتوری سرور اوکی بودن دستور آپگرید هم دادم میخوام تست بتا این واتروال انجام بدم ران کنم .. ولی بعد این دستور apt-get install unzip پیام E: Unable to locate package میده ..

**Comment by radkesvat** [comment]
برای واتروال خروجی رو باید از release دانلود کنید بعد

>wget https://github.com/radkesvat/WaterWall/releases/download/v0.2/Waterwall-linux-64.zip

> unzip Waterwall-linux-64.zip

> chmod +x Waterwall

> ./Waterwall

اما این تا اجرای برنامه بود؛ باید فایل کانفیگ رو درست کنید که دارم براش wiki مینویسم
