### ISSUE TITLE
مشکل در سرعت

### ISSUE THREAD

**Issue by mah981** [radkesvat/WaterWall#42]
سلام من از روش Reality Reverse Tunnel l استفاده کردم سرعت با speedtest  ولی بعضی از مواقع انگار بسته drop میشه مصلا چند نفر بهم گفتم توی اینستا فیلما تیکه تیکه باز میشه روش بهتر که پیشنهاد میکنید کدوم هست؟

**Comment by radkesvat** [comment]
داکیومنت قرار داده شد ؛ با halfduplex تست کنید و نسخه آخر
