### ISSUE TITLE
half dublex

### ISSUE THREAD

**Issue by xmohammad1** [radkesvat/WaterWall#44]
سلام وقت بخیر
این تانل ریورس ریلیتی با ماکس تو اموزش هالف دوپلکس یه قسمتی میگین:
 "صرف نظر از اینکه سرور ایران یا خارج چند هسته دارن در سرور خارج تعداد ورکر هارو همیشه 4 برابر تعداد ورکر های سرور ایران قرار میدم ؛ عددشو دستی وارد میکنم"
میخواستم ببینم این عددی که فرمدودید رو کجا باید وارد کنیم من یکم گیج شدم

**Comment by radkesvat** [comment]
فایل core.json میتونید تعداد workers هارو وارد کنید؛‌ داکیومنتش توی ویکی هست

**Comment by xmohammad1** [comment]
تشکر
