### ISSUE TITLE
Waterwall + Harproxy

### ISSUE THREAD

**Issue by xmohammad1** [radkesvat/WaterWall#45]
سلام خسته نباشید , ممنون بابت اپدیت هاتون
من میخواستم تانل هاتون رو با haproxy ترکیب کنم قبلش یه سوالی داشتم
میشه مثلا به Waterwall گفت به پورت 6070 گوش کن بعد بیای با haproxy پورت هایی که لازم داری رو bind کنی بعد بفرستی سمت پورت waterwall
یه مثال از کانفیگ haproxy مینویسم 
```
frontend frontend_2052
    bind *:2052
    default_backend backend_2052

backend backend_2052
    server server1 127.0.0.1:6070 check send-proxy
    server server2 127.0.0.1:8080 check backup send-proxy
````
دلیل استفاده از haproxy ام داشتن چدین نوع تانل به صورت همزمان هست که مثلا اگه روش اتصال مستقیم دچار مشکل شد به روش ریورس رجوع بشه یا بلعکس , حالا اینو میشه تو تعداد روش ها خیلی گسرتش داد ولی ایده اصلی به این شکل هست
ایا همچین چیزی امکان پذیره یا خیر؟ که ترافیک بیاد رو haproxy بعد هدف گذاری بشه سمت Waterwall

**Comment by xmohammad1** [comment]
برای این موردی که گفتم مثلا xray داخل کانفیگاش یه جایی هست میشه تایین کرد accept proxy protocol روی حالت true باشه یه همچین چیزی روی waterwall ام هست؟

**Comment by radkesvat** [comment]
به طور کلی نباید مشکلی باشه ؛ اگه روی بغیه تونل ها کار میکنه روی واتروال هم نباید مشکلی ایجاد کنه منتهی روش هایی که نیازمند اینه که ایپی سرور خارج رو واتروال ببینه ؛ باید یا مثلا توی کانفیگ واتروال ایپی خارج رو 127.0.0.1 بگید یا بهتر هست اصلا برای ورودی سرور خارج پورت جدا بزارید که نیاز به چک ایپی هم نباشه
