### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by MoeinNS** [radkesvat/WaterWall#46]
سلام دیشب با این اسکریپت دوستمون تانل رو برقرار کردم رو یه پنلی که تعداد کاربر بالایی داشت و حدود 200 مگ بر ثانیه پهنا مصرف میشد
بعد از اجرای تانل هم نوسانات پهنای باند و هم نوسانات پينگ شدیدی مشاهده شد طوری که مثلا از تلگرام میرفتی اینستا حدود 5 تا 10 ثانیه طول می‌کشید تا ریلود بشه و پهنای باند که توی تانل قبل 200 بود شده بود 40 50 مگ و همین هم با نوسان شدید بود
طبیعیه یا مشکل از اسکریپت بود
bash <(curl -Ls https://raw.githubusercontent.com/xmohammad1/Waterwall-RRT/main/setup.sh)

بازم مرسی بابت زحماتت مهندس خیلی وقته پیگیر کاراتم

**Comment by MoeinNS** [comment]
این اسکریپت هم تازه گذاشتن که مربوط به نسخه 1.06 شماست تستش میکنم اطلاع میدم
bash <(curl -Ls https://raw.githubusercontent.com/xmohammad1/Waterwall-RRT/main/RRT_MUX.sh)

اینم آدرس گیت‌هاب ایشون

https://github.com/xmohammad1/Waterwall-RRT?tab=readme-ov-file

**Comment by xmohammad1** [comment]
اسکریپت صرفا بر حسب دیتایی که داخل wiki خود پروژه نوشته شده تانل رو بر قرار میکنه
شما خودت میتونی به صورت دستی ام تانل بزنی

**Comment by Saleh-Mumtaz** [comment]
درود،
با نسخه جدید تست کنید اگر مشکل بربرار بود با لاگ دوباره ایشیو باز کنید.
