### ISSUE TITLE
تجربه  استفاده از نسخه ۱.۰۶ و پروتکل تانل هاف داپلکس و گزارش یک باگ 

### ISSUE THREAD

**Issue by RezaKardoost** [radkesvat/WaterWall#47]
اول از همه ممنون بخاطر این همه وقتی که برای این پروژه صرف میکنید  و با این کار کمک بزرگی به اینترنت آزاد در ایران میکنید.
من از دیشب پروتکل HalfDuplex رو طبق توضیحات خودتون پیاده سازی کردم و خیلی خوب کار کرد. تا اینکه همین یک ساعت پیش تصمیم گرفتم سرور ایران خودم به پلن بالاتر (تعداد هسته از ۱ به ۲) ارتقا بدم. با این کار عملکرد تانل بدتر شد. یعنی داخل v2rayng که latency میگرفتم از هر ۱۰ بار فقط یک بار بهم عدد میداد و بقیه faild میشد. خیلی واسم عجیب بود که فقط با زیاد شدن تعداد هسته سرور ایران، عملکرد بدتر شد. 
اومدم طبق گفته های شما مقدار worker در سرور خارج رو ۸ برابر مقدار هسته های سرور ایران گذاشتم بازم درست نشد.
یک بار دیگه تصمیم گرفتم مقدار worker در سرور ایران رو از ۰ به ۱ تغییر بدم و این بار با کمال تعجب تانل دوباره مثل قبل درست شد!!!!
انگار با اضافه کردن هسته ، واتروال تعداد ورکرها رو افزایش داده بود (مقدارش روی سرور ایران ۰ بود) و همین امر باعث شده بود تانلم به مشکل بخوره و وقتی خودم دستی مقدار ورکر رو داخل سرور ایران ۱ میزارم همه چیز اوکی میشه.

**Comment by NIKA5050** [comment]
> اول از همه ممنون بخاطر این همه وقتی که برای این پروژه صرف میکنید و با این کار کمک بزرگی به اینترنت آزاد در ایران میکنید. من از دیشب پروتکل HalfDuplex رو طبق توضیحات خودتون پیاده سازی کردم و خیلی خوب کار کرد. تا اینکه همین یک ساعت پیش تصمیم گرفتم سرور ایران خودم به پلن بالاتر (تعداد هسته از ۱ به ۲) ارتقا بدم. با این کار عملکرد تانل بدتر شد. یعنی داخل v2rayng که latency میگرفتم از هر ۱۰ بار فقط یک بار بهم عدد میداد و بقیه faild میشد. خیلی واسم عجیب بود که فقط با زیاد شدن تعداد هسته سرور ایران، عملکرد بدتر شد. اومدم طبق گفته های شما مقدار worker در سرور خارج رو ۸ برابر مقدار هسته های سرور ایران گذاشتم بازم درست نشد. یک بار دیگه تصمیم گرفتم مقدار worker در سرور ایران رو از ۰ به ۱ تغییر بدم و این بار با کمال تعجب تانل دوباره مثل قبل درست شد!!!! انگار با اضافه کردن هسته ، واتروال تعداد ورکرها رو افزایش داده بود (مقدارش روی سرور ایران ۰ بود) و همین امر باعث شده بود تانلم به مشکل بخوره و وقتی خودم دستی مقدار ورکر رو داخل سرور ایران ۱ میزارم همه چیز اوکی میشه.

سلام .. مسیریابی ویرایش worker ها میفرمایید روی سرور که ماهم ادیت بزنیم تست کنیم مرسی

**Comment by radkesvat** [comment]
اره اینو منم دیشب متوجه شدم، سرور ایران مالتی ترد بشه مشکل میخوره، حتما فیکس میشه

**Comment by Saleh-Mumtaz** [comment]
مهندس الان برای نتیجه گیری، رابطه بین تعداد هسته ها و ورکر ها چیه؟ تو سرور ایران هرچند هسته که داره یک بذاریم یا هر عددی گذاشتیم تو خارج ۸ برابر بذاریم؟

**Comment by Saleh-Mumtaz** [comment]
در نسخه جدید حل شد اما هنوز رابطه تعداد ورکر ها و تعداد هسته های سرور به طور دقیق گفته نشده
