### ISSUE TITLE
اختلال در اتصال

### ISSUE THREAD

**Issue by neon-bartmoss** [radkesvat/WaterWall#49]
سلام و ممنون بابت پروژه خوبتان

من تونل رو به صورت  ریورس ریلیتی با ماکس اجرا کردم 

خیلی نوسان داره

هر چند ثانیه قطع و وصل میشه و هندشیک بالا و پایین میره 
سرور ایران آسیا تک و خارج هتزنر هست
من sni رو هم عوض کردم و ورکر های خارج هم روی16 گذاشتم        
همین sni با پروژه RTT روی همین سرور ها درست جواب میده

**Comment by Saleh-Mumtaz** [comment]
https://raw.githubusercontent.com/xmohammad1/Waterwall-RRT/main/RRT_MUX.sh
از این اسکریپت استفاده کنید ببینید چطور هست

**Comment by Saleh-Mumtaz** [comment]
HalfDuplex رو پیاده کردن که بنظر خوب هست، همچنین ایشیو های دیگرو هم بخونید اطلاعات خوبی اضافه میکنن

**Comment by Saleh-Mumtaz** [comment]
https://github.com/radkesvat/WaterWall/issues/47#issue-2356929786
این پیام دوست عزیز رو بخونید نکته مهمی داره

**Comment by Ferixy** [comment]
> ```
> bash <(curl -Ls https://raw.githubusercontent.com/xmohammad1/Waterwall-RRT/main/RRT_MUX.sh)
> ```
> 
> از این اسکریپت استفاده کنید ببینید چطور هست

از اسکریپته استفاده کردی اخر?

**Comment by neon-bartmoss** [comment]
از این استفاده نکردم ولی دیدمش     کانفیگی که اسکریپت میسازه مثل مال خودمه 
الان چند ساعتی هست دارم کار میکنم باهاش خیلی خوبه   فقط همون هندشیک هست بعضی وقتا نوسان داره 
در استفاده واقعی مشکل خاصی نمیبینم 
عملکردش تقریبا مثل RTT هست

**Comment by xmohammad1** [comment]
کلا هر تانل ریورسی من تا الان تست کردم پرش هندشیک داره یکم

**Comment by Saleh-Mumtaz** [comment]
اما با RRT من پرش هندشیک نداشتم مدت طولانی هم استفاده کردم.

**Comment by xmohammad1** [comment]
> اما با RRT من پرش هندشیک نداشتم مدت طولانی هم استفاده کردم.

جالبه شاید به دیتاسنتر ایران فرق داره
چون من چه رتهول چه بقیه روش های ریورس همه واسم پرش هندشیک داره تا حدودی مثلا دو سه تا 300 میده بعد یکی 700 میده

**Comment by neon-bartmoss** [comment]
این که پرش نیست    طبیعیه 
من ۲۰ تا ۳۰۰ دادم ۲ یا ۳ تا ۳۰۰۰ تا ۵۰۰۰ بعد  دوباره ۳۰۰

**Comment by Saleh-Mumtaz** [comment]
> > اما با RRT من پرش هندشیک نداشتم مدت طولانی هم استفاده کردم.
> 
> جالبه شاید به دیتاسنتر ایران فرق داره چون من چه رتهول چه بقیه روش های ریورس همه واسم پرش هندشیک داره تا حدودی مثلا دو سه تا 300 میده بعد یکی 700 میده

من غیر آروان هیچ دیتاسنتر دیگه ای تست نکردم، RRT برای دیتاسنتر های معروف روی سیمین و فروغ کار میداد و روی شهریار و بامداد کار نمیداد. RTCF هم همینطور. در ایران فکر کنم بهترین سرورهارو همین ابراروان داره لیکن من حسابمو بستم.

**Comment by radkesvat** [comment]
فعلا یه باگ که هست اینه که نباید در سرور ایران workers بیشتر از ۱ باشه ؛ تو نسخه بعد حل میشه و شاید مشکلتون به این علت باشه

**Comment by xmohammad1** [comment]
> فعلا یه باگ که هست اینه که نباید در سرور ایران workers بیشتر از ۱ باشه ؛ تو نسخه بعد حل میشه و شاید مشکلتون به این علت باشه

با توجه به اپدیت جدید , امکانش هست سرور خارج خودش چک کنه چندتا workers لازم داره و تنظیم بشه؟ چون یکم داخل اسکریپت ممکنه گیج کننده بشه واسه کاربرا , الان دو حالت کلی میشه گذاشت یا عدد هارو از خود کاربر سوال کنه یا مثلا دوتا عدد پیش فرض بزاریم مثلا ایرانو بزاریم 2 یا 1 بعد خارجم 8 برابرشو بزاریم

**Comment by nika1367** [comment]
> > فعلا یه باگ که هست اینه که نباید در سرور ایران workers بیشتر از ۱ باشه ؛ تو نسخه بعد حل میشه و شاید مشکلتون به این علت باشه
> 
> با توجه به اپدیت جدید , امکانش هست سرور خارج خودش از طریق core چک کنه چندتا workers لازم داره و تنظیم بشه؟ چون یکم داخل اسکریپت ممکنه گیج کننده بشه واسه کاربرا , الان دو حالت کلی تو ذهمنه که میشه گذاشت یا عدد هارو از خود کاربر سوال کنه یا مثلا دوتا عدد پیش فرض بزاریم مثلا ایرانو بزاریم 2 یا 1 بعد خارجم 8 برابرشو بزاریم

تو اسکریپت بنظرم آپدیت بدی از کاربر بپرسه بهتره چند هسته داره تا پیش فرض ست کنی دوست عزیز..

**Comment by radkesvat** [comment]
چک کردن فعلا ممکن نیست متاسفانه... مالتی تردینگ توی این داستان خیلی سخته فعلا تنها راه همینه که اگه سرور ایران بیشتر از ۱ ورکر بود ؛ تعداد ورکر های سرور خارج محاسبه بشه و ضرب در ۸ بشه

این فقط برای تونل های ریورس هست ؛ برای مستقیم این مطرح نیست 


این مشکل قابل حل هستا ولی کد نویسیش به حدی سخته که سمتش نمیرم فعلا چون میدونم درست کنم ۱ ماه درگیر دیباگش هستیم؛ توی halfduplex این رو حل کردم و ۲ هفته فقط طول کشید کدش اماده شه ۹۰۰ خط شد درصورتی که این نبود ۱۰۰ خط هم نمیشد

**Comment by radkesvat** [comment]
این مشکل در 1.18 حل شد

**Comment by xmohammad1** [comment]
با تشکر فراوان
