### ISSUE TITLE
استفاده از رنج پورت

### ISSUE THREAD

**Issue by navid4132** [radkesvat/WaterWall#5]
سلام و عرض خسته نباشید
پیشاپیش بابت زحماتی که در جهت دسترسی به اینترنت آزاد میکشین تشکر میکنم.
من در حال حاضر از RTT و لودبالانس اسرکیپت شما با کمی تغییرات کوچیک به صورت مولتی پورت استفاده میکنم . با توجه به اینکه بعضیها مثل من از قدیم با پنل هایی مثل کافکا و رنج پورت های متفاوت کار کردن ، آیا این روش تانلینگ مثل RTT این امکان را میده که از رنج پورت استفاده کنیم و توانایی تعداد یوزر بالا را مثل RTT داره؟

**Comment by radkesvat** [comment]
بله کاملا پشتیبانی شده حتی با overlapping

**Comment by navid4132** [comment]
عالیه
پس بیصبرانه منتظر داکیومنت شما هستم
