### ISSUE TITLE
مشکل وصل نشدن

### ISSUE THREAD

**Issue by mah981** [radkesvat/WaterWall#51]
سلام وقت بخیر من از HalfDuplex در openvpn استفاده کردم اینجوریه که وصل میشه بعد چند ثانیه کلا دیگه کار نمیکنه این روش فقط روی v2ray جواب میده ؟ ولی از reverse استفاده کردم اوکی بود همچی 
سوال بعدیم اینه تعداد cpu با عداد worker برابر ؟ اونجا که گفتین ۸ برابر یعنی سرور خارجم ۸ core  باید باشه ؟

**Comment by radkesvat** [comment]
نه نیاز نیست ۸ هسته باشه، اوپن پی دی ان هم باید کار کنه فقط مال v2ray نیست

**Comment by Ferixy** [comment]
سلام اس ان ای سحاب کثیف شده از اس ان ای دیگری استفاده کنید

**Comment by nika1367** [comment]
> سلام اس ان ای سحاب کثیف شده از اس ان ای دیگری استفاده کنید

سلام از کجا میفهمید که کثیف شده ؟ و از کجا ورفای شده پیدا میکنید ؟

**Comment by Saleh-Mumtaz** [comment]
با ازمون و خطا فکر میکنم مشخص بشه، از zula.ir یا امثالش استفاده کنید. دامنه هایی که به شکل زیر باشن فکر کنم جواب هستن.
![Screenshot_20240623_174231_Chrome](https://github.com/radkesvat/WaterWall/assets/83896125/1922d844-eaab-4d73-85fb-6cad38ba9f2d)

**Comment by nika1367** [comment]
> با ازمون و خطا فکر میکنم مشخص بشه، از zula.ir یا امثالش استفاده کنید. دامنه هایی که به شکل زیر باشن فکر کنم جواب هستن. ![Screenshot_20240623_174231_Chrome](https://private-user-images.githubusercontent.com/83896125/342070770-1922d844-eaab-4d73-85fb-6cad38ba9f2d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDExMTUsIm5iZiI6MTcxOTIwMDgxNSwicGF0aCI6Ii84Mzg5NjEyNS8zNDIwNzA3NzAtMTkyMmQ4NDQtZWFhYi00ZDczLTg1ZmItNmNhZDM4YmE5ZjJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTgxYWRlNDZkMTVhZTEzNDcyOTNkZTc1ZjMyYmI4NWEzYTNlMGIxYTgxNWU5N2UyMmE2YzM4YTA2MThjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-EILuAfx3bgUmsRlak-CK_aHXRzZAJcq4IN6rHFhysY)

جسارتا با چه اسکنری این اطلاعات استخراج میکنید ؟

**Comment by Saleh-Mumtaz** [comment]
اسکنر نیست سایت های معروف با گوشی میرم اون بالا تنظیمات سایت رو میزنم گواهی امنیتی رو چک میکنم

**Comment by nika1367** [comment]
> اسکنر نیست سایت های معروف با گوشی میرم اون بالا تنظیمات سایت رو میزنم گواهی امنیتی رو چک میکنم

فقط tls چک میکنید ؟ 1.2 باشه یا حتما 1.3

**Comment by Saleh-Mumtaz** [comment]
tls 1.3 بهتر هست

**Comment by Saleh-Mumtaz** [comment]
ببخشید دیر متوجه منظورتون شدم، خیر فقط ‌tls چک نمیکنم، سایت هایی که از aes 128 gcm و x25519 استفاده میکنن انتخاب و تستشون میکنم که ایا جواب میدن یا خیر. tls 1.3 هم جز همین فاکتورهاست باید داشته باشن.
