### ISSUE TITLE
Waterwall doesn't free the used ports?

### ISSUE THREAD

**Issue by Saleh-Mumtaz** [radkesvat/WaterWall#53]
![image](https://github.com/radkesvat/WaterWall/assets/83896125/b36d5ecd-b178-4f26-92c2-f38df8ff0bbc)

**Comment by radkesvat** [comment]
ایپی تیبل با ری استارت ؛ ریست میشه با این دستور هم همینطور

```
iptables -t nat -F
iptables -t nat -X

```

اگه با واتروال مالتی پورت تونل کنید خودش در شروع و پایان ایپی تیبل رو ریست میکنه ؛ ولی اگه یجوری kill اش کنید که نتونه ریست کنیه ؛ باید خودتون دستی ریست کنید اگه روش دیگه ای میخواید بزنید


برای روش هایی که مالتی پورت نیستن ایپیتیل رو ریست نمیکنه چون شاید کاربر بخواد رول های خودشو داشته باشه

**Comment by Saleh-Mumtaz** [comment]
```
تک پورت بود و با دستورات بالا ریست نشد بازم.
ری استارت هم تاثیری نداشت

```
من میگم شاید سیستم اون دفعه باگ برداشته، حالا اگر دوباره مشاهده شد ایشیو رو دوباره باز میکنم.

**Comment by Saleh-Mumtaz** [comment]
@radkesvat 
![image](https://github.com/radkesvat/WaterWall/assets/83896125/a373007c-94a4-41b0-9f90-22121917f73b)

**Comment by radkesvat** [comment]
همم نمیدونم دقیق متوجه نشدم ؛ اگه میخواید سناریو رو به صورت simplified بگید من تکرارش کنم ببینم مشکل میخورم یا نه

**Comment by Saleh-Mumtaz** [comment]
ریلیتی رو روی پورت ۴۴۳ اجرا کنید، سپس واتروال رو قطع کنید و دوباره روش دیگری اجرا کنید با پورت ۴۴۳، برنامه خطا میده که پورت ۴۴۳ مشغول هست

**Comment by Saleh-Mumtaz** [comment]
![image](https://github.com/radkesvat/WaterWall/assets/83896125/0ab874f2-055a-46cb-9358-dc8af3267823)

**Comment by Saleh-Mumtaz** [comment]
![Screenshot_20240625_104327_YouTube](https://github.com/radkesvat/WaterWall/assets/83896125/22c98032-3144-461c-806f-15252c5a3ab6)

**Comment by Saleh-Mumtaz** [comment]
در RRT نه تنها روی ۴۴۳ تونل رو انجام میدادیم که کانفیگ در پنل خارج هم روی ۴۴۳ بود و روی واتروال هم نباید مشکلی پیش بیاد

**Comment by radkesvat** [comment]
Rtt میشد چون مولتی پورت اجرا شده


واتروال هم مولتی پورت اجرا کنید میشه 
و علاوه بر این واتروال  می تونه سینگل پورت هم این قابلیتو پیاده کنه ولی خوب توی کانفیگ باید این رو تعیین کنید با ip whitelist یا سایر فیلتر ها که مثالش توی ویکی گفته شده هم توی tls tunnel هم reverse cdn که وابسته به روش نیست درکل
