### ISSUE TITLE
فیلتر شدن دامنه

### ISSUE THREAD

**Issue by aliChavoshi** [radkesvat/WaterWall#58]
دوست عزیز با روش Tls  نگران فیلتر شدن دامنه نباشیم ؟

**Comment by Saleh-Mumtaz** [comment]
هیچ چیزی صد در صدی نیست، بنابراین خیر مطمئن نباشید

**Comment by aliChavoshi** [comment]
ممنون

**Comment by aliChavoshi** [comment]
چقدر احتمال میدین بشه ؟ من قبلا از 4to6  استفاده میکردم

**Comment by aliChavoshi** [comment]
نسبت به هم مقایسه کنید . مثلا قبلی بدتر از این بوده

**Comment by Saleh-Mumtaz** [comment]
پروژه نوپا هست، شما تست کنید ببینید نسبت به اون چطور بوده، اگر تجربتون رو اینجا به اشتراک بگذارید که چه بهتر
