### ISSUE TITLE
نود UDP

### ISSUE THREAD

**Issue by karimi12** [radkesvat/WaterWall#59]
این روش نود UDP  یا QUIC , http3  ندارد؟
معمولا UDP سرعت بالاتری دارد.

**Comment by radkesvat** [comment]
udp داره 

مثلا میتونید از tcp عبور بدیدش با اضافه کردن چیزی مثل grpc که سایز پکت ها رو نگه داره (protobuf client/server)

لی هنوز ترنسپورت های مخصوص udp مثل quic نداره؛ رو udp خیلی نمیشه حساب کرد راحت میبندنش اگه بخوان

**Comment by karimi12** [comment]
حرفت صحیح اما در حال حاضر UDP  کیفیت و سرعت خوبی داره 
ویژگی UDP  این که بررسیش توسط سیستم فیلترینگ خیلی سخت چون فرستنده اصلا براش مهم نیست گیرنده وضعیتش چی هست این باعث می شه نشه به سادگی بررسیش کرد و گزینشی بستش برای همین مجبورن همه اش به یکبار ببندن و یا باز کنن و محدودیت یا اختلا روش خیلی معنی نداره چون فقط به سیستم های فیلترینگ فشار میاره

**Comment by ali6043** [comment]
میشه با کانفیگ ریالیتی h2 اونو تانل کرد؟یعنی tcplistener UdpListener  بنویسیم کافیه؟

**Comment by karimi12** [comment]
اره اینم می شه 
اما اینجا  داری یکبار همه چیز می کنی H2 بعدش ارسال می کنی این خودش یه سرباری داره من بیشتر منظورم UDP  خالص بود
