### ISSUE TITLE
tls 

### ISSUE THREAD

**Issue by NIKA5050** [radkesvat/WaterWall#6]
وقت بخیر طبق بند داکیومنت tls بنده ایپی سرور ایران رو روی یه دامنه خریداری شده ست کردم و درخواست سرتیفکیت دادم ولی وقتی دامنه خودمو جایگزین میکنم این پیام میده: Waiting for verification... و نمیسازه فایلو در ادامه مابقی لاگ:
Challenge failed for domain my.domain.com
http-01 challenge for my.domain.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: my.domain.com
   Type:   connection
   Detail: 1xx.1xx.1xx.1xx: Fetching
   http://my.domain.com/.well-known/acme-challenge/i82opF3bAuh8E2WP_rFLoF                                                                                                                                                             fSwzFaoM:
   Timeout after connect (your server may be slow or overloaded)

اما روی سرور خارج راحت میسازه ولی چون طبق راهنما شما فرمودید ایپی که پشت دامنه انداختید براش سرتیفیکت بگیرید که در اینجا ایپی داخل ایران هستش..چرا نمیسازه ؟

**Comment by radkesvat** [comment]
مهم نیست اصلا، روی سرور خارج بسازید و اون دوتا فایل رو بیارید ایران، منم نگفتم حتما رو سرور ایران ساخته بشه
