### ISSUE TITLE
مالتی پورت

### ISSUE THREAD

**Issue by Mstrman4** [radkesvat/WaterWall#60]
سلام تو حالت مالتی پورت فقط میشه دوتا پورت اد کرد ؟؟

![photo_2024-06-25_09-22-49](https://github.com/radkesvat/WaterWall/assets/88909029/abcea60d-ea84-40b1-80b9-b634c37fc515)
![photo_2024-06-25_09-23-24](https://github.com/radkesvat/WaterWall/assets/88909029/8ab3d501-ced1-4219-b461-35452284587d)
 

تو اون قسمت  ایران بیشتر از دوتا پورت ارور میده 

توی قسمت خارج هم باید اینجا که خط زدم بزاریم پورت هارو یا نه ؟؟

ممنون میشم کمک کنید❤️

**Comment by Saleh-Mumtaz** [comment]
اون دوتا پورت نیست، رنج پورت هست.

**Comment by Mstrman4** [comment]
> اون دوتا پورت نیست، رنج پورت هست.

بله رفتم دیدم اوکی شد ممنونم . فقط پینگش خیلی بالاس 700 و اینکه وسط اینستاگرام یکمی گیر میکنه
