### ISSUE TITLE
Running WaterWall on ArvanCloud Containers

### ISSUE THREAD

**Issue by Saleh-Mumtaz** [radkesvat/WaterWall#61]
سلام مهندس،
ایا بنظرت امکانش هست نسخه داکر منتشر بشه و روی کانتینر های ابراروان اجرا کنیم؟ یا نیاز به یه وب پنل داره؟ ریورس پنل به پنل، تست کردم، منابع بسیار زیادی هنگام اجراش میکشه، برنامه شما حس میکنم بسیار بهینه تر برای تانل ریورس، البته نتیجه گیری من هست. نه کد ریورس پنل رو خونم و نه کد واتروال رو، فقط از روی تجربه میگم.
یک چیز دیگر که در ذهنم بود، بعد از بلوغ کافی برنامه، Integrating waterwall into x-ui
Reverse powered by WaterWall

**Comment by radkesvat** [comment]
میشه رو کانتینر ران کرد کاری نداره اصلا

فعلا باید طبق مسیر پیش بریم و مسیر طولانی هست ؛ هر مرحله که انجام بشه داکیومنتش رو میزارم و اموزش ران کردن رو کانینتر ام اپدیت بعدی میزارم  (اگه یادم نره 😁)

**Comment by Saleh-Mumtaz** [comment]
بسیار عالی
 پس این ایشیو رو باز میذارم و نسخه بعدی که منتشر شد تگ میکنم

**Comment by Saleh-Mumtaz** [comment]
@radkesvat 
Reminder✌️

**Comment by Saleh-Mumtaz** [comment]
@radkesvat 
مهندس این شیوه جدید سازماندهی داکیومنت ها واقعا عالی، هرچی میگذره بهتر و بهتر عمل میکنی ماشاالله 
اگر در توانم میبود دونیت میکردم اما دانشجوئم و توان مالیم محدودِ

**Comment by radkesvat** [comment]
حتما ، در حال باز نویسی دایکومنت ها هستم و فردا همزمان با اپدیت اینم مینوسم، اگه یادم رفت یاد اوردی کنید🙏

**Comment by Saleh-Mumtaz** [comment]
صد حیف که در کمک کردن در کد زنیش ناتوانم،
 ولی مهندس تو یک ایشیو دیگه هم گفتم یک جوری بهمون یاد بده چطوری کانفیگ ها رو بچینیم تا خودمون هر طور لازمه تغییر بدیم
الان دقت کن همه ازت همش کانفیگ مثال میخوان فلان حالت چطوری بنویسیم
انگار به جای ماهی ماهی گیری یادمون بده
وگرنه با توجه به پتانسیل واتروال باید صدتا صفحه ویکی درست کنی تا همه رو پوشش بده
