### ISSUE TITLE
try_write failed, enqueue!

### ISSUE THREAD

**Issue by RezaKardoost** [radkesvat/WaterWall#62]
> 2024-06-25 18:23:47.573 DEBUG TcpConnector: connection succeed FD:45 [127.0.0.1:16442] => [127.0.0.1:443]
> 2024-06-25 18:23:47.774 DEBUG TcpListener: Accepted FD:46  [[2001:470:1f12:e1f:601e:68f7:d755:0]:179] <= [[2001:470:1f12:e1f::2]:38194]
> 2024-06-25 18:23:47.775 DEBUG TcpConnector: connection succeed FD:47 [127.0.0.1:16444] => [127.0.0.1:443]
> 2024-06-25 18:23:47.813 DEBUG TcpListener: Accepted FD:48  [[2001:470:1f12:e1f:801d:47f6:d755:0]:179] <= [[2001:470:1f12:e1f::2]:38210]
> 2024-06-25 18:23:47.813 DEBUG TcpConnector: connection succeed FD:49 [127.0.0.1:16460] => [127.0.0.1:443]
> 2024-06-25 18:23:48.050 DEBUG TcpListener: received close for FD:46
> 2024-06-25 18:23:48.050 DEBUG TcpConnector: sent close for FD:47
> 2024-06-25 18:23:48.142 DEBUG TcpListener: received close for FD:48
> 2024-06-25 18:23:48.142 DEBUG TcpConnector: sent close for FD:49
> 2024-06-25 18:23:48.464 DEBUG try_write failed, enqueue!
> 2024-06-25 18:23:54.729 DEBUG TcpListener: Accepted FD:46  [[2001:470:1f12:e1f:601e:68f7:d755:0]:179] <= [[2001:470:1f12:e1f::2]:38222]
> 2024-06-25 18:23:54.729 DEBUG TcpConnector: connection succeed FD:47 [127.0.0.1:18120] => [127.0.0.1:443]
> 2024-06-25 18:23:57.978 DEBUG TcpListener: Accepted FD:48  [[2001:470:1f12:e1f:801d:47f6:d755:0]:179] <= [[2001:470:1f12:e1f::2]:51984]
> 2024-06-25 18:23:57.978 DEBUG TcpConnector: connection succeed FD:49 [127.0.0.1:18136] => [127.0.0.1:443]
> 2024-06-25 18:24:01.454 DEBUG TcpListener: received close for FD:42
> 2024-06-25 18:24:01.454 DEBUG TcpConnector: sent close for FD:43
> 

من تا امروز از روش reverse reality with half duplex استفاده میکردم و واقعا عملکردش خیلی نسبت به نسخه اول بهتر شده.
امروز تصمیم گرفتم bgp4 رو تست کنم. سرعتش خوبه اما هر چند ثانیه یک بار که ازش ترافیک میگشم، ارور try_write failed, enqueue! میده و همون لحظه مثلا اگر داخل اینستا باشم یهو پست ها برای چند ثانیه لود نمیشن و گاهی باید ریفرش کنم. بخشی از لاگ های دیباگ رو که این ارور رو داده فرستادم. در ضمن من bgp4 رو هم با ipv4 و هم با ipv6 local تست کردم و در هر دو صورت این ارور رو گرفتم

**Comment by radkesvat** [comment]
سلام این ارور نیست کاملا طبیعیه که پیش بیاد ، یه سرور سرعت ارسال و دریافت بالایی داره عموما حداقل ۱ گیگ پورت دارن ولی کلاینت ها نه، سرعت کلاینت ها روی نت ایران میتونه خیلی کم باشه، وقتی سرور ببینه کلاینت نمیتونه دیتا رو دریافت کنه باید صبر کنه و به اصطلاح ارسال رو متوقف کنه تا کلاینت بتونه قبلیا رو بگیره، درکل این لاگ طبیعیه و بستگی به سرعت دریافت کلاینت داره که چند بار باگ بنویسه
