### ISSUE TITLE
تونل IPv6

### ISSUE THREAD

**Issue by Edizam** [radkesvat/WaterWall#63]
ممنون بابت زحماتی که برای دسترسی به اینترنت آزاد می کشی.

سرورهای مجازی هتزنر IPv6 با ساب نت /64 میده که 18میلیارد میلیارد آی پی میشه. برفرض اینکه سرور ایران هم یک یا تعدادی IPv6 داشته باشه:
آیا با واتروال امکانش هست که ترافیک تونل رو بین آیپی های ورژن 6 پخش کنیم؟ ولی کلاینت ها و پنل روی آیپی ورژن 4 کار کنه.

**Comment by radkesvat** [comment]
تو اپدیت های بعدی اضافه میشه

**Comment by arash0921** [comment]
عالی

**Comment by radkesvat** [comment]
این هنوز اضافه نشده فعلا open بمونه

**Comment by Saleh-Mumtaz** [comment]
با وجود اینکه توییتم راجب واتروال ۳ هزارتا ویو خورد و جناب اقاپور اموزشش تو یوتیوب ۳۶۰۰ تا ویو خورده، و استارهای پروژه ۷۸ تا بیشتر شدن، اما ایشیو ها اکثرا درخواست فیچر هستن، یا راهنمایی برای کانفیگ های پیچیده تر.
چه کردی مهندس. انتظار داشتم حداقل ۳۰ تا ایشیو باگ باز بشه.
بخاطر اینه که تسلطت روی c خیلی بالاتر از nim هست؟ واقعا کارت حرف نداره

**Comment by radkesvat** [comment]
نه من هرچی بلدم از nim یاد گرفتم ؛ منتهی اونجا یکمی محیط سخت تر بود سر اینکه ابزار هاش هنوز جای بهتر شدن دارن و حل کردن باگ به خاطر abstraction ای که ایجاد کرده بود واقعا سخت بود هرچی نسخه میدادیم حل نمیشد ؛ با c نوشتن دیگه لایه ای ایجاد نکرد و ابزار های بیشتری داره که با کمک اونا مشکلات رو میشه زود تر حل کرد

**Comment by Saleh-Mumtaz** [comment]
مهندس اینطوری فایده نداره هربار برای هر روش باید خودت کانفیگ مثال بزنی.
بنظرت ممکن هست طرز نوشتن کانفیگ رو اموزش بدی تا هرکی خودش‌ کانفیگ دلخواهش رو بنویسه؟ الان صفحه ویکی انقدر زیاد شده ریورس رفته تو show more
من خودم یچیزایی دستگیرم شد ولی لاجیک یکسری چیزاش برام نامفهوم هست

**Comment by Edizam** [comment]
@radkesvat 
بهت تبریک بگم با این سطح از مهارت و تشکر کنم بابت زحمات بی منتت.
داکیومنت free bind خوندم.
البته من عملکرد سیستم فیلترینگ نمی دونم و خودم هم باهاش سروکله نزدم. و ببخشید اگه سوالام واضح یا غلطه.

1. میشه پورت هایی که IPv6ها با هم ارتباط دارن قابل تنظیم باشه مثلا رو پورت خاص یا یه تعداد پورت مشخص که توسط کاربر مشخص بشه؟
2. آیا اگه سرور ایران چند IPv6 داشته باشه میشه همزمان از تعدادی از او آیپی ها استفاده کرد؟
3. آیا هافدابلکس میشه به این صورت اجرا کرد که IP1 سرور ایران به IP1 سرور خارج ریکوئست بده و IP2 سرور خارج، ریسپانس رو به IP2یاIP1 سرور ایران برگردونه؟

**Comment by radkesvat** [comment]
سلام ممنون؛

اینایی که گفتین شدنی هستند ولی باید node های بیشتری مثل router اضافه بشن در آینده
