### ISSUE TITLE
tls

### ISSUE THREAD

**Issue by Zaxel-Test** [radkesvat/WaterWall#65]
سلام وقت بخیر
با تشکر از تمامی زحمات شما 
ببخشید یه سوال داشتم شاید جای مناسبی برای سوال من نباشم ولی خیلی برام مهم شده به یه جواب برسم
من مثلا یه تانل ساده آیپی تیبل ایجاد کردم از ایران به خارج تا اینجا همه چی اوکیه 
میخواستم بدونم راهی هست مثلا کانفیگی که به کاربر دادم موقعی که روی آیپی ایران من میزنه وصل بشه اتصال همون کاربر به ایران tls روش بشه سوار کرد ؟
مثال برنامه نپستر قسمت ssh یه بخش داره که ssh+tls یعنی آیپی میزاری مستقیم یه tls مثلا discord.com بهش میدی 
میخوام بدونم راهی هست بدون اینکه کاربر کاری کنه بشه tls سوار کرد روی سرور ایران 
امیدوارم منظورمو فهمیده باشید
بازم معذرت میخوام اگه جای سوالم بد بوده 
با تشکر از زحمات شما

**Comment by radkesvat** [comment]
باید کانفیگی که به کاربردادید مثلا از vless ساده به vless tls تغییر بدید ؛ ssh هم همینطوری روش tls سوار میشه ؛ سمت کلاینت باید دامنه وارد بشه و سمت سرور هم باید tls باشه ؛ برای اینکه فقط تا ایران این اتفاق بیفته می تونید پنل رو بیارید روی سرور ایران بزارید و با اوت باند به خارج وصلش کنید

**Comment by Zaxel-Test** [comment]
تشکر از لطف شما بابت پاسخگویی
یه سوال از این روش هایی که گفتید نمیتونم استفاده کنم 
اگه از روش Reverse TLS استفاده کنم چی به این حرکتی که گفتم میرسم ؟

**Comment by Zaxel-Test** [comment]
تشکر از لطف شما بابت پاسخگویی
یه سوال از این روش هایی که گفتید نمیتونم استفاده کنم
اگه از روش Reverse TLS استفاده کنم چی به این حرکتی که گفتم میرسم ؟

**Comment by radkesvat** [comment]
نه کلا تونل تمام کاری که میکنه بین سرور ایران و خارجه ؛‌ بین کاربر و سرور ایران نیست

همچنین اگه کانفیگی مثل vless رو بدون tls رد کنید  حتی به سرور تونل ؛ ایرانسل ا اختلال شدید میندازه و بلاک هم ممکنه بکنه ؛ کانفیگ vmess نیاز به رمزنگاری نداره چون رمزنگاری اش داخلی هست و ایرانسل هم فعلا کاریش نداره؛ شاید این مشکلتون رو حل کنه


به کاربرهاتون سابسکرایب بدید تا خودکار اپدیت بشن و نیازی نباشه بهشون بگید چی کار کنن ؛ آموزش اش رو کانال آقاپور و جاهای دیگه هست ببینید خوبه

**Comment by Zaxel-Test** [comment]
تشکر از لطف شما 
v2ray نیست 
ssh هست برای مصارف شخصی 
در کل میخواستم بدونم یوزرام که الان ssh مستقیم هستن بدون انجام کاری میتونم یه tls سر راهش بزارم یا نه 
تشکر از لطف شما
