### ISSUE TITLE
اختلال روی بعضی از پورت ها در روش HalfDuplex Tunnel reverse reality

### ISSUE THREAD

**Issue by aliravaghi** [radkesvat/WaterWall#67]
سلام توی این روش سرور رو تانل کردم و با یک کانفیگ تست کردم اوکی بود ولی وقتی سرور اصلی رو انتقال دادم و کاربر روی سرور اومد چند مورد گفتن که یا قطعه براشون کلا یا سرعت کنده مخصوصا روی اینستاگرام خودمم همون کانفیگ رو چک میکردم مشکل داشت واقعا ولی با یک کانفیگ دیگه روی یک پورت دیگه مشکلی نداشت اصلا

**Comment by Saleh-Mumtaz** [comment]
چند نفر دیگه هم بنده مطلع شدم از HalfDuplex راضی نبودن

**Comment by radkesvat** [comment]
ببینید تونل هرکاری کنه بین ایران و خارج انجام میده ؛ ارتباط کاربر با سرور ایران ربطی به روش تونل نداره به کانفیگی که بهش میدین ربط و کیفیت اش باید مثل هم باشه اگه متفاوت هست یعنی شاید رمزنگاری نداره کانفیگی که به کاربر دادید باید تغییر اونو تست کنید

**Comment by radkesvat** [comment]
الان من reverse halfduplex رو چند جا زدم ترافیک سنگین داره جا به جا میکنه ؛ یه جا مشکل داشتن بهشون گفتم به جای vless tcp ساده vmess tcp یا vless tls بدن به کاربر که مشکلشون هم حل شده و سرورشون رو هم مانیتور میکنم خودم

**Comment by aliravaghi** [comment]
دقیقا این کانفیگی که میگم مشکل داره vless tcp هست یعنی اگر tls فعال کنم یا کانفیگ vmess tcp بدم مشکل حل میشه؟
تست میکنم اطلاع میدم

**Comment by radkesvat** [comment]
حتما تست کنید

**Comment by Saleh-Mumtaz** [comment]
مهندس بنظرت اتصال وبسوکت بهتر از tcp نیست؟  درسته وبسوکت روی اتصال tcp کار میکنه، اما بارها مشاهده کردم، مثلا استفاده از واتساپ در tcp مشکل داره ولی وبسوکت هیچ مشکلی نداره.
تنها علتی که خیلیا از tcp خوششون میاد همون پینگ پایین ترش هست، فکر میکنن هرچه پینگ کمتر بهتر.
در کل نظرت راجب شیوه های اتصال رو میخواستم بدونم.
مثلا در داکیومنت gRpc هم نوشته برای اتصال سرور به سرور بسیار مناسب هست ولی کلاینت سرور خیر. خب اما میبینیم چون پینگ پایینتری داره خوششون میاد.

**Comment by radkesvat** [comment]
وب سوکت خودش روی tcp سوار شده ؛ به نظرم ارتباطی بین این ۲ نیست و کلاینت ها صرفا شاید مشکل داشته باشن البته من روی تروجان که هستم و tcp هست هیچوقت همچین مشکلی نخوردم ولی شنیدم عده ای با vless دارن این مشکلو از قدیم

**Comment by Saleh-Mumtaz** [comment]
> دقیقا این کانفیگی که میگم مشکل داره vless tcp هست یعنی اگر tls فعال کنم یا کانفیگ vmess tcp بدم مشکل حل میشه؟ تست میکنم اطلاع میدم

درود،با vmess tcp مشکل حل شد؟

**Comment by aliravaghi** [comment]
> > دقیقا این کانفیگی که میگم مشکل داره vless tcp هست یعنی اگر tls فعال کنم یا کانفیگ vmess tcp بدم مشکل حل میشه؟ تست میکنم اطلاع میدم
> 
> درود،با vmess tcp مشکل حل شد؟

سلام
ببخشید دیروز ندیدم پیامتون رو
خودم چک کردم روی همون پورت که vless tcp مشکل داشت با vmess tcp مشکل حل میشد ولی بازم همون شخص که مشکل داشت مشکلش حل نشد حالا نمیدونم دیروز و پریروز بخاطر اختلال اینجوری بود یا مشکل از جای دیگه است.
ممنون بخاطر راهنمایی
