### ISSUE TITLE
مشکل اسپید تست bgp4

### ISSUE THREAD

**Issue by Ferixy** [radkesvat/WaterWall#68]
سلام وقت بخیر. تانل bgp4 خیلی چیز خفنیه اما دوتا مشکل داره متاسفانه(که با ریورس ریلیتی ندارم)
اولی اینه که از هر ۵ تا اسپید تست سینگل که میگیرم ۳ تاشون مپقع اپلود ارور میدن.
دومی هم اینه که تو اینستا بعضی وقتا اینطوری میشه که ویدیو گیر میکنه ولی صداش بدون مشکل پخش میشه.

**Comment by radkesvat** [comment]
کانفیگ vmess tcp بسازید و تست کنید با اون ببینید فرقی میکنه یا نه

**Comment by Ferixy** [comment]
> کانفیگ vmess tcp بسازید و تست کنید با اون ببینید فرقی میکنه یا نه

بله وجود داره. همونطور که گفتم با بقیه قابلیت های واتروال مثل پورت به پورت ساده ، tls h2 یا ریلیتی چه‌ ریورس چه غیر ریورس این مشکل رو ندارم که نشون میده یه مشکلی با خود bgp4 هست

**Comment by radkesvat** [comment]
خوب اینکه یه جا مشکل داره دلیلی نمیشه کلا Bgp مشکل داشته باشه ؛ روی خیلی از سرور ها دیدم مستقیم سرعت اوکی گرفتن ؛‌ به نظرم اول با iperf تست کنید اینو بیبنید دقیق چقدر میده ؛ پورت هم چک کنید 179 باشه ؛‌ سپس bgp4 رو با half duplex ترکیب کنید و تست کنید و سپس با ریورس ؛ ببینید رو چه حالتی بهترین نتیجه رو میگیرید

**Comment by lostsoul6** [comment]
@Ferixy 

بنده هم توی تستی که کردم این مشکل رو با اسپید تست دارم . روی اینستا البته مشکلی که فرمودید رو ندیدم . مهندس رادکسوت گفتن که ترکیب کنید با آپشن های دیگه . ممنون میشم اگر تست کردید و اوکی بود با half duplex یا reverse ، کانفیگش رو به اشتراک بزارید بنده هم تست کنم .

**Comment by Ferixy** [comment]
> سلام وقت بخیر. تانل bgp4 خیلی چیز خفنیه اما دوتا مشکل داره متاسفانه(که با ریورس ریلیتی ندارم) اولی اینه که از هر ۵ تا اسپید تست سینگل که میگیرم ۳ تاشون مپقع اپلود ارور میدن. دومی هم اینه که تو اینستا بعضی وقتا اینطوری میشه که ویدیو گیر میکنه ولی صداش بدون مشکل پخش میشه.

سرور توی iperf مشکلی نداره و پهنا باند کافی رو داره. پورت هم ۱۷۹ هست. آپلود توی هیچ چیزی مشکل نداره. فقط توی اسپید تست اینجوری میشه. دیروز یکنفر دیگه هم حرف بنده رو تایید کردن.

**Comment by Ferixy** [comment]
> سپس bgp4 رو با half duplex ترکیب کنید

این کار هم انجام دادن اصلا کار نکرد. مطمئنید این دوتا باهمدیگه سازگار هستند?

**Comment by persian-michael-scott** [comment]
> > سپس bgp4 رو با half duplex ترکیب کنید
> 
> این کار هم انجام دادن اصلا کار نکرد. مطمئنید این دوتا باهمدیگه سازگار هستند?
> 
> امکانش هست یه کانفیگ مثال بفرستید ؟ من دارم طبق داکیومنت پیش میرم ولی این دوتارو نتونستم ترکیب کنم.

من bgp4 + halfduplex مستقیم رو تست کردم کار کرد . واسه من دانلودش عالی بود ولی آپلود خیلی کم .(کانفیگم رو پورت 80 بود ، خواستی عوضش کن واسه خودت)

**iran config.json :** 
```
{
    "name": "bgp_client",
    "nodes": [
        {
            "name": "input",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": 80,
                "nodelay": true
            },
            "next": "bgp_client"
        },
        {
            "name": "bgp_client",
            "type": "Bgp4Client",
            "settings": {},
            "next": "halfc"
        },
        {
            "name": "halfc",
            "type": "HalfDuplexClient",
            "next": "output"
        },
        {
            "name": "output",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address":"kharej_ip",
                "port":179
            }
        }
    ]
}
```
**kharej config.json :** 
```
{
    "name": "bgp_server",
    "nodes": [
        {
            "name": "input",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": 179,
                "nodelay": true
            },
            "next": "halfs"
        },
        {
            "name": "halfs",
            "type": "HalfDuplexServer",
            "settings": {},
            "next": "bgp_server"
        },
        {
            "name":"bgp_server",
            "type":"Bgp4Server",
            "settings":{},
            "next":"output"
        },
        
        {
            "name": "output",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "127.0.0.1",
                "port": 80
            }
        }

    ]
}
```

**Comment by Ferixy** [comment]
> ولی آپلود خیلی کم

ممنونم بابت کانفیگ. کار کرد برام. مشکل اپلود توی اسپیدتست هنوز پابرجاست ولی پینگ هندشیک بهتر شده.
لطفاً از vless tcp tls استفاده و تست کنید. قطعا اپلودتون بهتر میشه.

**Comment by nika1367** [comment]
> bgp4 + halfduplex

میشه حالت مولتی پورت با تانلشم بفرستید ممنون

**Comment by persian-michael-scott** [comment]
> > ولی آپلود خیلی کم
> 
> ممنونم بابت کانفیگ. کار کرد برام. مشکل اپلود توی اسپیدتست هنوز پابرجاست ولی پینگ هندشیک بهتر شده. لطفاً از vless tcp tls استفاده و تست کنید. قطعا اپلودتون بهتر میشه.
فکر نمیکنم ربطی به کانفیگ داشته باشه ارتباط تانل مشکل آپلود داره
آپلود خیلی وابسته به دیتاسنتر هست . با چند تا دیتاسنتر تست کردم آپلود پایین بود ولی رویکیش فیکس بود و آپلود بالا

**Comment by persian-michael-scott** [comment]
> > bgp4 + halfduplex
> 
> میشه حالت مولتی پورت با تانلشم بفرستید ممنون

زیاد کاری نداره هرجا خواستید half duplex کنید توی node های کانفیگ در سرور ایران node یکی به آخر باید 
```
{
            "name": "halfc",
            "type": "HalfDuplexClient",
            "next": "output"
}
```
و در سرور خارج node دوم باید ```

{
            "name": "halfs",
            "type": "HalfDuplexServer",
            "settings": {},
            "next": "change based on next node"
}
```
باشه.
برای مولتی پورت کردن برعکس این یعنی node دوم سرور ایران : 
```
{
            "name": "port_header",
            "type": "HeaderClient",
            "settings": {
                "data": "src_context->port"
            },
            "next": "bgp_client"
}
```
و node یکی به آخر سرور خارج : 
```
{
            "name":"port_header",
            "type": "HeaderServer",
            "settings": {
                "override": "dest_context->port"
            },
            "next": "output"
}
```
حالا کامل شده BGP4+halfduplex+multiport میشه این شکلی : 
**iran config.json :** 
```
{
    "name": "bgp_client",
    "nodes": [
        {
            "name": "input",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": [23,65535],
                "nodelay": true
            },
            "next": "port_header"
        },
        {
            "name": "port_header",
            "type": "HeaderClient",
            "settings": {
                "data": "src_context->port"
            },
            "next": "bgp_client"
        },
        {
            "name": "bgp_client",
            "type": "Bgp4Client",
            "settings": {},
            "next": "halfc"
        },
        {
            "name": "halfc",
            "type": "HalfDuplexClient",
            "next": "output"
        },
        {
            "name": "output",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address":"kharej_ip",
                "port":179
            }
        }
    ]
}
```
**kharej config.json :**
```
{
    "name": "bgp_server",
    "nodes": [
        {
            "name": "input",
            "type": "TcpListener",
            "settings": {
                "address": "0.0.0.0",
                "port": 179,
                "nodelay": true
            },
            "next": "halfs"
        },
        {
            "name": "halfs",
            "type": "HalfDuplexServer",
            "settings": {},
            "next": "bgp_server"
        },
        {
            "name":"bgp_server",
            "type":"Bgp4Server",
            "settings":{},
            "next":"port_header"
        },
        {
            "name":"port_header",
            "type": "HeaderServer",
            "settings": {
                "override": "dest_context->port"
            },
            "next": "output"
        },
        {
            "name": "output",
            "type": "TcpConnector",
            "settings": {
                "nodelay": true,
                "address": "127.0.0.1",
                "port": "dest_context->port"
            }
        }

    ]
}
```
امیدوارم مهندس رادکسوت این همه زحمت کشیده آموزش این کانفیگ نویسی رو هم قرار بدن. من با خوندن کانفیگ ها و حدس و گمان فهمیدم چی به چیه

**Comment by NIKA5050** [comment]
> > > bgp4 + halfduplex
> > 
> > 
> > میشه حالت مولتی پورت با تانلشم بفرستید ممنون
> 
> زیاد کاری نداره هرجا خواستید half duplex کنید توی node های کانفیگ در سرور ایران node یکی به آخر باید
> 
> ```
> {
>             "name": "halfc",
>             "type": "HalfDuplexClient",
>             "next": "change based on next node"
> }
> ```
> 
> و در سرور خارج node دوم باید
> 
> ```
> {
>             "name": "halfs",
>             "type": "HalfDuplexServer",
>             "settings": {},
>             "next": "change based on next node"
> }
> ```
> 
> باشه. برای مولتی پورت کردن برعکس این یعنی node دوم سرور ایران :
> 
> ```
> {
>             "name": "port_header",
>             "type": "HeaderClient",
>             "settings": {
>                 "data": "src_context->port"
>             },
>             "next": "change based on next node"
> }
> ```
> 
> و node یکی به آخر سرور خارج :
> 
> ```
> {
>             "name":"port_header",
>             "type": "HeaderServer",
>             "settings": {
>                 "override": "dest_context->port"
>             },
>             "next": "output"
> }
> ```
> 
> و خب حواستون باشه پارامتر های رنج پورت و dest_context->port رو وارد کنید در کانفیگ حالا کامل شده BGP4+halfduplex+multiport میشه این شکلی :
> 
> **iran config.json :**
> 
> ```
> {
>     "name": "bgp_client",
>     "nodes": [
>         {
>             "name": "input",
>             "type": "TcpListener",
>             "settings": {
>                 "address": "0.0.0.0",
>                 "port": [23,65535],
>                 "nodelay": true
>             },
>             "next": "port_header"
>         },
>         {
>             "name": "port_header",
>             "type": "HeaderClient",
>             "settings": {
>                 "data": "src_context->port"
>             },
>             "next": "bgp_client"
>         },
>         {
>             "name": "bgp_client",
>             "type": "Bgp4Client",
>             "settings": {},
>             "next": "halfc"
>         },
>         {
>             "name": "halfc",
>             "type": "HalfDuplexClient",
>             "next": "output"
>         },
>         {
>             "name": "output",
>             "type": "TcpConnector",
>             "settings": {
>                 "nodelay": true,
>                 "address":"kharej_ip",
>                 "port":179
>             }
>         }
>     ]
> }
> ```
> 
> **kharej config.json :**
> 
> ```
> {
>     "name": "bgp_server",
>     "nodes": [
>         {
>             "name": "input",
>             "type": "TcpListener",
>             "settings": {
>                 "address": "0.0.0.0",
>                 "port": 179,
>                 "nodelay": true
>             },
>             "next": "halfs"
>         },
>         {
>             "name": "halfs",
>             "type": "HalfDuplexServer",
>             "settings": {},
>             "next": "bgp_server"
>         },
>         {
>             "name":"bgp_server",
>             "type":"Bgp4Server",
>             "settings":{},
>             "next":"port_header"
>         },
>         {
>             "name":"port_header",
>             "type": "HeaderServer",
>             "settings": {
>                 "override": "dest_context->port"
>             },
>             "next": "output"
>         },
>         {
>             "name": "output",
>             "type": "TcpConnector",
>             "settings": {
>                 "nodelay": true,
>                 "address": "127.0.0.1",
>                 "port": "dest_context->port"
>             }
>         }
> 
>     ]
> }
> ```
> 
> امیدوارم مهندس رادکسوت این همه زحمت کشیده آموزش این کانفیگ نویسی رو هم قرار بدن. من با خوندن کانفیگ ها و حدس و گمان فهمیدم چی به چیه



> > > bgp4 + halfduplex
> > 
> > 
> > میشه حالت مولتی پورت با تانلشم بفرستید ممنون
> 
> زیاد کاری نداره هرجا خواستید half duplex کنید توی node های کانفیگ در سرور ایران node یکی به آخر باید
> 
> ```
> {
>             "name": "halfc",
>             "type": "HalfDuplexClient",
>             "next": "change based on next node"
> }
> ```
> 
> و در سرور خارج node دوم باید
> 
> ```
> {
>             "name": "halfs",
>             "type": "HalfDuplexServer",
>             "settings": {},
>             "next": "change based on next node"
> }
> ```
> 
> باشه. برای مولتی پورت کردن برعکس این یعنی node دوم سرور ایران :
> 
> ```
> {
>             "name": "port_header",
>             "type": "HeaderClient",
>             "settings": {
>                 "data": "src_context->port"
>             },
>             "next": "change based on next node"
> }
> ```
> 
> و node یکی به آخر سرور خارج :
> 
> ```
> {
>             "name":"port_header",
>             "type": "HeaderServer",
>             "settings": {
>                 "override": "dest_context->port"
>             },
>             "next": "output"
> }
> ```
> 
> و خب حواستون باشه پارامتر های رنج پورت و dest_context->port رو وارد کنید در کانفیگ حالا کامل شده BGP4+halfduplex+multiport میشه این شکلی :
> 
> **iran config.json :**
> 
> ```
> {
>     "name": "bgp_client",
>     "nodes": [
>         {
>             "name": "input",
>             "type": "TcpListener",
>             "settings": {
>                 "address": "0.0.0.0",
>                 "port": [23,65535],
>                 "nodelay": true
>             },
>             "next": "port_header"
>         },
>         {
>             "name": "port_header",
>             "type": "HeaderClient",
>             "settings": {
>                 "data": "src_context->port"
>             },
>             "next": "bgp_client"
>         },
>         {
>             "name": "bgp_client",
>             "type": "Bgp4Client",
>             "settings": {},
>             "next": "halfc"
>         },
>         {
>             "name": "halfc",
>             "type": "HalfDuplexClient",
>             "next": "output"
>         },
>         {
>             "name": "output",
>             "type": "TcpConnector",
>             "settings": {
>                 "nodelay": true,
>                 "address":"kharej_ip",
>                 "port":179
>             }
>         }
>     ]
> }
> ```
> 
> **kharej config.json :**
> 
> ```
> {
>     "name": "bgp_server",
>     "nodes": [
>         {
>             "name": "input",
>             "type": "TcpListener",
>             "settings": {
>                 "address": "0.0.0.0",
>                 "port": 179,
>                 "nodelay": true
>             },
>             "next": "halfs"
>         },
>         {
>             "name": "halfs",
>             "type": "HalfDuplexServer",
>             "settings": {},
>             "next": "bgp_server"
>         },
>         {
>             "name":"bgp_server",
>             "type":"Bgp4Server",
>             "settings":{},
>             "next":"port_header"
>         },
>         {
>             "name":"port_header",
>             "type": "HeaderServer",
>             "settings": {
>                 "override": "dest_context->port"
>             },
>             "next": "output"
>         },
>         {
>             "name": "output",
>             "type": "TcpConnector",
>             "settings": {
>                 "nodelay": true,
>                 "address": "127.0.0.1",
>                 "port": "dest_context->port"
>             }
>         }
> 
>     ]
> }
> ```
> 
> امیدوارم مهندس رادکسوت این همه زحمت کشیده آموزش این کانفیگ نویسی رو هم قرار بدن. من با خوندن کانفیگ ها و حدس و گمان فهمیدم چی به چیه



> > > bgp4 + halfduplex
> > 
> > 
> > میشه حالت مولتی پورت با تانلشم بفرستید ممنون
> 
> زیاد کاری نداره هرجا خواستید half duplex کنید توی node های کانفیگ در سرور ایران node یکی به آخر باید
> 
> ```
> {
>             "name": "halfc",
>             "type": "HalfDuplexClient",
>             "next": "change based on next node"
> }
> ```
> 
> و در سرور خارج node دوم باید
> 
> ```
> {
>             "name": "halfs",
>             "type": "HalfDuplexServer",
>             "settings": {},
>             "next": "change based on next node"
> }
> ```
> 
> باشه. برای مولتی پورت کردن برعکس این یعنی node دوم سرور ایران :
> 
> ```
> {
>             "name": "port_header",
>             "type": "HeaderClient",
>             "settings": {
>                 "data": "src_context->port"
>             },
>             "next": "change based on next node"
> }
> ```
> 
> و node یکی به آخر سرور خارج :
> 
> ```
> {
>             "name":"port_header",
>             "type": "HeaderServer",
>             "settings": {
>                 "override": "dest_context->port"
>             },
>             "next": "output"
> }
> ```
> 
> و خب حواستون باشه پارامتر های رنج پورت و dest_context->port رو وارد کنید در کانفیگ حالا کامل شده BGP4+halfduplex+multiport میشه این شکلی :
> 
> **iran config.json :**
> 
> ```
> {
>     "name": "bgp_client",
>     "nodes": [
>         {
>             "name": "input",
>             "type": "TcpListener",
>             "settings": {
>                 "address": "0.0.0.0",
>                 "port": [23,65535],
>                 "nodelay": true
>             },
>             "next": "port_header"
>         },
>         {
>             "name": "port_header",
>             "type": "HeaderClient",
>             "settings": {
>                 "data": "src_context->port"
>             },
>             "next": "bgp_client"
>         },
>         {
>             "name": "bgp_client",
>             "type": "Bgp4Client",
>             "settings": {},
>             "next": "halfc"
>         },
>         {
>             "name": "halfc",
>             "type": "HalfDuplexClient",
>             "next": "output"
>         },
>         {
>             "name": "output",
>             "type": "TcpConnector",
>             "settings": {
>                 "nodelay": true,
>                 "address":"kharej_ip",
>                 "port":179
>             }
>         }
>     ]
> }
> ```
> 
> **kharej config.json :**
> 
> ```
> {
>     "name": "bgp_server",
>     "nodes": [
>         {
>             "name": "input",
>             "type": "TcpListener",
>             "settings": {
>                 "address": "0.0.0.0",
>                 "port": 179,
>                 "nodelay": true
>             },
>             "next": "halfs"
>         },
>         {
>             "name": "halfs",
>             "type": "HalfDuplexServer",
>             "settings": {},
>             "next": "bgp_server"
>         },
>         {
>             "name":"bgp_server",
>             "type":"Bgp4Server",
>             "settings":{},
>             "next":"port_header"
>         },
>         {
>             "name":"port_header",
>             "type": "HeaderServer",
>             "settings": {
>                 "override": "dest_context->port"
>             },
>             "next": "output"
>         },
>         {
>             "name": "output",
>             "type": "TcpConnector",
>             "settings": {
>                 "nodelay": true,
>                 "address": "127.0.0.1",
>                 "port": "dest_context->port"
>             }
>         }
> 
>     ]
> }
> ```
> 
> امیدوارم مهندس رادکسوت این همه زحمت کشیده آموزش این کانفیگ نویسی رو هم قرار بدن. من با خوندن کانفیگ ها و حدس و گمان فهمیدم چی به چیه

تشکر امکانش هست این حالت رو با ریورس ریلیتی هم ترکیب کنید زحمت بکشید ؟ تست کردم گیج شدم نشد مرسی..

**Comment by Saleh-Mumtaz** [comment]
> سلام وقت بخیر. تانل bgp4 خیلی چیز خفنیه اما دوتا مشکل داره متاسفانه(که با ریورس ریلیتی ندارم) اولی اینه که از هر ۵ تا اسپید تست سینگل که میگیرم ۳ تاشون مپقع اپلود ارور میدن. دومی هم اینه که تو اینستا بعضی وقتا اینطوری میشه که ویدیو گیر میکنه ولی صداش بدون مشکل پخش میشه.

درود بزرگوار،
ایا این مشکل حل شد؟

**Comment by Ferixy** [comment]
> > سلام وقت بخیر. تانل bgp4 خیلی چیز خفنیه اما دوتا مشکل داره متاسفانه(که با ریورس ریلیتی ندارم) اولی اینه که از هر ۵ تا اسپید تست سینگل که میگیرم ۳ تاشون مپقع اپلود ارور میدن. دومی هم اینه که تو اینستا بعضی وقتا اینطوری میشه که ویدیو گیر میکنه ولی صداش بدون مشکل پخش میشه.
> 
> درود بزرگوار،
> ایا این مشکل حل شد؟

سلام عزیز. نه متأسفانه. دوتا از آشنایان هم که بهشون تانل bgp4 واتروال رو معرفی کردم هم متأسفانه با همین مشکل من مواجه هستند.

دم دولوپر گرم واقعاً خیلی زحمت میکشه

**Comment by persian-michael-scott** [comment]
> > > سلام وقت بخیر. تانل bgp4 خیلی چیز خفنیه اما دوتا مشکل داره متاسفانه(که با ریورس ریلیتی ندارم) اولی اینه که از هر ۵ تا اسپید تست سینگل که میگیرم ۳ تاشون مپقع اپلود ارور میدن. دومی هم اینه که تو اینستا بعضی وقتا اینطوری میشه که ویدیو گیر میکنه ولی صداش بدون مشکل پخش میشه.
> > 
> > 
> > درود بزرگوار،
> > ایا این مشکل حل شد؟
> 
> سلام عزیز. نه متأسفانه. دوتا از آشنایان هم که بهشون تانل bgp4 واتروال رو معرفی کردم هم متأسفانه با همین مشکل من مواجه هستند.
> 
> دم دولوپر گرم واقعاً خیلی زحمت میکشه

عزیز مشکل از کد bgp4 نیست . آپلودش رو اکثر دیتاسنتر ها محدوده

**Comment by nika1367** [comment]
> > > > سلام وقت بخیر. تانل bgp4 خیلی چیز خفنیه اما دوتا مشکل داره متاسفانه(که با ریورس ریلیتی ندارم) اولی اینه که از هر ۵ تا اسپید تست سینگل که میگیرم ۳ تاشون مپقع اپلود ارور میدن. دومی هم اینه که تو اینستا بعضی وقتا اینطوری میشه که ویدیو گیر میکنه ولی صداش بدون مشکل پخش میشه.
> > > 
> > > 
> > > درود بزرگوار،
> > > ایا این مشکل حل شد؟
> > 
> > 
> > سلام عزیز. نه متأسفانه. دوتا از آشنایان هم که بهشون تانل bgp4 واتروال رو معرفی کردم هم متأسفانه با همین مشکل من مواجه هستند.
> > دم دولوپر گرم واقعاً خیلی زحمت میکشه
> 
> عزیز مشکل از کد bgp4 نیست . آپلودش رو اکثر دیتاسنتر ها محدوده

امکانش هست این حالت رو با ریورس ریلیتی هم ترکیب کنید زحمت بکشید ؟ تست کردم گیج شدم نشد مرسی..

**Comment by nika1367** [comment]
> > > > سلام وقت بخیر. تانل bgp4 خیلی چیز خفنیه اما دوتا مشکل داره متاسفانه(که با ریورس ریلیتی ندارم) اولی اینه که از هر ۵ تا اسپید تست سینگل که میگیرم ۳ تاشون مپقع اپلود ارور میدن. دومی هم اینه که تو اینستا بعضی وقتا اینطوری میشه که ویدیو گیر میکنه ولی صداش بدون مشکل پخش میشه.
> > > 
> > > 
> > > درود بزرگوار،
> > > ایا این مشکل حل شد؟
> > 
> > 
> > سلام عزیز. نه متأسفانه. دوتا از آشنایان هم که بهشون تانل bgp4 واتروال رو معرفی کردم هم متأسفانه با همین مشکل من مواجه هستند.
> > دم دولوپر گرم واقعاً خیلی زحمت میکشه
> 
> عزیز مشکل از کد bgp4 نیست . آپلودش رو اکثر دیتاسنتر ها محدوده

این حالت رو با متد ریورس هم میشه ترکیب کنید کدشو بزارید قابلیت هالف بزارید کنار bg

**Comment by radkesvat** [comment]
قرار میدم میدم حتما ؛ یکمی تایمی الان محدود هستم
