### ISSUE TITLE
سوال در مورد Waterwall

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#69]
درود جناب @radkesvat 

من کانفیگ مطالعه میکردم بخش wiki رو ،  دیدم گویا خودتون هم از روش ریورس ریلیتی استفاده میکنید . سوالی که داشتم این هست که الان ارتباط سرور با ipv4 هست . این باعث نمیشه سرور خارج فیلتر بشه یا سرور ایران ، ایران اکسس بشه ؟

آیا راهی هست که با ipv6 بشه انجام داد ؟ اگر بله لطفا به wiki اضافه کنید .

سوال آخرم در مورد مصرف ترافیک این تانل هست . توی تانل های عادی مثل پنل به پنل ، به ازای یک گیگ مصرف کاربر ، سرور یک گیگ دانلود میکنه و یک گیگ آپلود میکنه . توی تانل ریورس این مقدار ثابت هست یا تغییر میکنه ؟ من شنیدم میگن به ازای یک گیگ مصرف کاربر ، سرور 2 گیگ دانلود و 2 گیگ آپلود میکنه . یعنی مصرف دو برابر هست . این درسته ؟

**Comment by radkesvat** [comment]
درمورد سوال اول اینکه من هیچوقت ایران اکسس نشدم رو هیچ دیتا سنتری همیشه هم ipv4 استفاده میکنم ولی با ایپی ۶ هم مشکلی نیست میتونید به جای ایپی ۴ توی نود ها از ایپی ۶ استفاده کنید البته شاید مالتی پورت در این نسخه روی ایپی ۶ کار نکنه

مصرف ترافیک مثل همه تانل ها  هست و دوبرابر نیست ؛ همون یک گیگ اپلود و یک گیگ دانلود به اضای یک گیگ مصرف کاربر

بعضی دیتا سنتر ها پول ۱ گیگ اپلود رو هم میگیرن در نتیجه شما پول ۲ گیگ رو پرداخت میکنید ولی بیشتر دیتا سنتر ها در حال حاضر اپلود رایگان هستند

**Comment by lostsoul6** [comment]
ممنون مهندس جان @radkesvat 

آیا مالتی پورت با ipv6 در برنامه هست ؟ و اینکه جسارتا شما چه مدت هست این تانل رو استفاده میکنید و چقدر کاربر و ترافیک رو تست کردید و سرور ایران اکسس نشده ؟ تشکر

**Comment by Saleh-Mumtaz** [comment]
> ممنون مهندس جان @radkesvat
> 
> آیا مالتی پورت با ipv6 در برنامه هست ؟ و اینکه جسارتا شما چه مدت هست این تانل رو استفاده میکنید و چقدر کاربر و ترافیک رو تست کردید و سرور ایران اکسس نشده ؟ تشکر

ایپی ۶ مالتی پورت هنوز کار نمیکنه در یک ایشیو به عنوان درخواست فیچر باز هست، در مورد ایران اکسس شدن هم در ایشیو پین شده نمونه ترکیبی برای جلوگیری از اکسس شدن گذاشته شد.
