### ISSUE TITLE
Http2

### ISSUE THREAD

**Issue by milad84z** [radkesvat/WaterWall#7]
وقتی که میخوام از http2 استفاده کنم،این ارور رو روی سرور خارج میده
![Screenshot_20240413_225628_Termius](https://github.com/radkesvat/WaterWall/assets/147247389/cc555bd6-ba5e-4788-8e11-7352cdf30d10)

**Comment by milad84z** [comment]
اینم لاگ core سرور هست
![Screenshot_20240413_235934_Termius](https://github.com/radkesvat/WaterWall/assets/147247389/8f61bcdc-a2bf-4aaf-978b-81c41ff37dc9)

**Comment by radkesvat** [comment]
عکس دوم پاینی تر چیزی نشون نداده؟ فایل رو میتونم ببینم (ترجیها ایپی هاتون رو چیز متفاوت وارد کنید)

**Comment by milad84z** [comment]
مهندس فایل config منظورتون هست؟من کدهارو عینا از روی شما کپی کردم و فقط پورت خروج رو عوض کردم،چند بار هم چک کردم که مشکلی نباشه،تو حالت tls precon بدون مشکل وصل میشه و همه چیز عالی هست،ولی تو http2 به مشکل خوردم،البته اطلاعات فنی خاصی ندارم،هرچی بلدم از پروژه های شما یاد گرفتم،اول که اجرا میکنه بدون مشکل بالا میاد عکس اول،ولی همین که میخوای یوزر رو متصل کنی برنامه خارج میشه،مثله عکس دوم
![Screenshot_20240414_194927_Termius](https://github.com/radkesvat/WaterWall/assets/147247389/24e9a4d3-3bc5-4102-819b-22fb73036adc)
![Screenshot_20240414_194945_Termius](https://github.com/radkesvat/WaterWall/assets/147247389/c561ef5c-75c6-4135-a06a-d95f4cbdc2fc)

**Comment by milad84z** [comment]
در مورد لاگ core هم که گفتید پایینتر چیزی نشون نمیده،نه فقط همین چرخه تکرار میشه

**Comment by radkesvat** [comment]
چک میکنم حتما، نسخه ۰.۵ هم چند ساعت دیگه منتشر میشه با اونم تست کنید اگه مشکل بازم باقی بود، فایل کانفیگ سرور ایران و خارج رو بفرستین

**Comment by milad84z** [comment]
تو حالت rev http2 تک پورت که میخوام اجرا کنم مشکل داره
[config4kharej.txt](https://github.com/radkesvat/WaterWall/files/15001395/config4kharej.txt)
[config4iran.txt](https://github.com/radkesvat/WaterWall/files/15001397/config4iran.txt)

**Comment by milad84z** [comment]
این هم فایلها،عینا از صفحه کپی شده و پورت ایپی دامنه جایگزین شده،سرت هم بدون مشکل گرفته شده
