### ISSUE TITLE
ارور HTTP request sent, awaiting response...  روی سرور ایران

### ISSUE THREAD

**Issue by ardalanrzn** [radkesvat/WaterWall#70]
سلام

موقع نصب و اجرای دستور wget روی سرور ایران برای دانلود پکیج Waterwall این ارور رو بهم میده و هرچیم صبر میکنم اتفاق جدیدی نمیفته.

HTTP request sent, awaiting response...

چجوری باید حلش کنم؟
اگر لازم هست که بگم، سرور ایران رو هم از زیماتلکام گرفتم، سرور مجازی رسپینا

**Comment by radkesvat** [comment]
این معمولا با Dns حل میشه

```
echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf

```

**Comment by ardalanrzn** [comment]
> این معمولا با Dns حل میشه
> 
> ```
> echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf
> ```

متاسفانه حل نشد و بازم همون جا گیر میکنه

**Comment by nsa14** [comment]
> > این معمولا با Dns حل میشه
> 
> > 
> 
> > ```
> 
> > echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf
> 
> > ```
> 
> 
> 
> متاسفانه حل نشد و بازم همون جا گیر میکنه
> 
> 

برید توی فایل مربوط به dns
خودتون دستی این رکورد رو تو‌بالاش اضافه کنید
nameserver 8.8.8.8
nameserver 8.4.4.8

مشکل باید حل بشه

**Comment by radkesvat** [comment]
واتروال خودش کلا ۳ مگابایته فایل zip اش

اگه نتونستید مشکل رو حل کنید ؛ روی ویندوز فایل زیپ رو دانلود کنید و سپس وارد سایت temp.sh بشید و فایل زیپ رو اونجا اپلود کنید ؛ بهتون یه لینک مستقیم میده که میتونید اونو با wget در سرور لینوکس دانلود کنید
