### ISSUE TITLE
چند سرور ایران به یک سرور خارج

### ISSUE THREAD

**Issue by beta3y** [radkesvat/WaterWall#77]
سلام وقت بخیر بیزحمت آموزش متصل کردن چند سرور ایران به یک سرور خارج رو (بدون نیاز به نصب و کانفیگ مجدد برای هر سرور) قرار بدین
حالت LoadBalancing

**Comment by Saleh-Mumtaz** [comment]
https://radkesvat.github.io/WaterWall-Docs/

**Comment by NIKA5050** [comment]
> https://radkesvat.github.io/WaterWall-Docs/

متوجه نشدیم مثال روی چند خارج یک ایرانه .. دنبال چند ایران یک خارجیم حالت ریورس
