### ISSUE TITLE
سوال در مورد Cdn Tunnel

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#78]
درود وقت بخیر @radkesvat 

در بخش Cdn Tunnel مثال هایی که هست مستقیم هست یا ریورس ؟ بنده الان پنل x-ui رو باید روی خارج نصب کنم درسته ؟ دامنه هم به آی پی ایران پوینت بشه و در سرور ایران ssl بگیرم براش ؟

تشکر

**Comment by Saleh-Mumtaz** [comment]
بله x-ui روی خارج
دامنه به ایپی ایران، ssl در ایران ذخیره بشه

**Comment by Saleh-Mumtaz** [comment]
https://radkesvat.github.io/WaterWall-Docs/
تمام مثال هایی ‌که نیاز دارید تو این صفحه هستند

**Comment by lostsoul6** [comment]
درود @radkesvat 

آیا برای روش cdn مالتی پورت بدون halfduplex میشه mux یا همون concurrency که روی روش reality بود رو فعال کرد ؟ اگر بله کدش چی هست و کجای کانفیگ باید اضافه بشه . به نظرم اگر هزاران کانکشن هم از سمت کلادفلر به سرور ایران بیاد ، بازم امکان اکسس شدن هست . تشکر
