### ISSUE TITLE
ارور در cdn tunnel

### ISSUE THREAD

**Issue by Asfia7** [radkesvat/WaterWall#80]
سلام مهندس خسته نباشید بابت زحماتی که میکشید

من برای اجرای cdn tunnel در سرور ایران به این ارور بر میخورم 
مشکل کجاست؟

bind: Cannot assign requested address

**Comment by radkesvat** [comment]
پورت درگیره توسط یه برنامه دیگه یا اینکه listen address درست نیست ؛ با نسخه آخر تست کنید
