### ISSUE TITLE
نوسان در ریورس cdn

### ISSUE THREAD

**Issue by neon-bartmoss** [radkesvat/WaterWall#81]
سلام 
با تشکر از پروژه خوبتون 

من تونل ریورس cdn  رو راه اندازی کردم 
واقعا نمیشه استفاده کرد 
نوسان شدید سرعت و پینگ داره 
هیچی بالا نمیاره

![bandicam 2024-06-30 17-56-04-068](https://github.com/radkesvat/WaterWall/assets/139677882/d32a8b65-9864-4834-b45f-dd25ceddc21f)

اصلاح:

روش reverse cdn halfduplex کار نکرد برای من
چند بار هم کانفیگ رو چک کردم

**Comment by neon-bartmoss** [comment]
الان تگ invalid  برای چی زدید؟

**Comment by lostsoul6** [comment]
@neon-bartmoss 

من مالتی پورت رو چک کردم با cdn و پینگ و سرعت آپلود اوکی هست اما سرعت دانلود ضعیفه

با halfduplex هنوز چک نکردم . مهندس @radkesvat  شما مشکل سرعت با روش cdn tunnel نداشتید؟ آیا ترکیبش با halfduplex تاثیری خواهد داشت و تست شده که کار کنه ؟

در ضمن ممنون میشم بفرمایید آیا روش cdn tunnel هم میشود با mux و concurrency اوکی کرد که تعداد کانکشنی که از کلادفلر به سرور ایران برمیگرده کمتر بشه ؟ اگر بله چه کدی و در کدام قسمت کانفیگ باید قرار بگیرد ؟ تشکر

**Comment by neon-bartmoss** [comment]
@lostsoul6 
چند وقته استفاده میکنید؟
چون من نوسان میبینم 

جیتر و پینگ و دانلود خیلی بالا پایین میره
میشه کانفیگتون رو اینجا پست کنید؟
تعداد ورکر ها چی بود؟

**Comment by Saleh-Mumtaz** [comment]
این چند روزه دیگه از اکسس کردن سرور ایران گذشتن و دارن دست میذارن رو سرعت
کلا سرعت اینترنت به فنا رفته، کیفیت شبکه افت کرده

**Comment by Saleh-Mumtaz** [comment]
> الان تگ invalid برای چی زدید؟

نه اینکه ایشیو شما بی اعتبار باشه بلکه به این معنا که یک چیزی درست کار نمیکنه
