### ISSUE TITLE
تانل یک سرور ایران به چند خارج

### ISSUE THREAD

**Issue by Alirezamoradi20** [radkesvat/WaterWall#82]
سلام با تشکر فراوان از زحمات شما
اگر امکانش هست بگید که کدوم تانل هارو میشه از یک ایران به چند خارج زد.
به عنوان مثال halfduplex رو میشه؟

**Comment by radkesvat** [comment]
https://radkesvat.github.io/WaterWall-Docs/Load-Balancing.html


بله همه روش هارو میشه به شکل های متخلف بالانس کرد

**Comment by Alirezamoradi20** [comment]
موردی ک اینجا ذکر شده میگه که کاربر هارو پخش میکنه بین دو سرور خارج
نمیشه بجای این مورد مشخص کرد که مثلا کاربر های دامنه x فقط به سرور آلمان و دامنه y فقط به سرور هلند وصل بشن؟

**Comment by radkesvat** [comment]
برای این کار به sniffing node نیاز هست که فعلا پیاده سازی نشده
