### ISSUE TITLE
استفاده همزمان از IPv4 و IPv6

### ISSUE THREAD

**Issue by Alireza78na** [radkesvat/WaterWall#83]
سلام و خسته نباشید 
این امکان وجود داره که سرور همزمان به IPv4 و IPv6 کانکشن بزنه؟

اینجوری احتمال شناسایی سرور خیلی کمتر میشه ، چون مثلا سروری که تمام دیتای ورودیش با IPv4 هست و تمام دیتای خرورجی روی IPv6 هست مشخصه که تانله چون درحالت عادی حداقل در ایران امکان نداره تمام ترافیک عادی خروجی روی فقط IPv6 باشه. مخصوصا وفتی که کاربرایی که بهش وصل میشن همه روی IPv4 باشه.

بنابراین اگه امکانی باشه که به صورت رندوم بخشی از دیتا روی IPv4 بره و بخش دیگش روی IPv6 بره هم ترافیک عادی تر جلوه میکنه و هم احتمالا چون دیتا بین IPv6 و IPv4 پخش میشه تشخیصش خیلی سخت تر میشه واسه فایروال.

**Comment by radkesvat** [comment]
اضافه میشه این قابلیت ولی فعلا چند تا جیز. مثل وایرگارد و تکمیل داکیومنت بخش داکر اولویت بیشتری دارن

**Comment by radkesvat** [comment]
البته همین الانم میشه بالانس کرد به دوتا outbound که یکشون به ۶ وصل بشه یکیشون به ۴

**Comment by Alireza78na** [comment]
ممنون از وقتی که واسه آزاد شدن اینترنت میزارید.
به نظرم اگه بدون لود بالانس باشه و رو هسته باشه خیلی بهتر میشه ، چون مثلا میشه به صورت تصادفی نصف پکت ها با IPv4 بره و نصف  دیگه با IPv6 ، تو این حالت چون شبکه ها متفاوتن و طبق گفته ی خودشون کنترل کمتری روی IPv6 دارن ، حتی اگه DPI بیاد پکنت هارم بررسی کنه به یه چیز ناقص و گاها کامل میرسه ، چون این کار رندوم اتفاق میوفته. اینجوری کلا DPI گیج میشه.

البته من تخصصی ندارم و نظرمم تخصصی نیست ، صرفا فقط خواستم ایده ای که به ذهنم رسید رو بهتون بگم ، امیدوارم کمکی کرده باشم.
