### ISSUE TITLE
mimic other protocols

### ISSUE THREAD

**Issue by Edizam** [radkesvat/WaterWall#84]
سلام، ایده ای که دارم صرفا برای رندوم کردن نوع کانکشن هست و نمی دونم آیا برای فیلترچی مهمه که نوع پروتکل چی هست یا صرفا پهنای باند مهمه.
ضمنا نحوه کار داخلی واتروال رو هم نمی دونم.

1. از نظر تکنیکی بهتر نیست که کانکشن های واتروال قابلیت میمیک کردن بقیه پروتکل ها داشته باشه؟ از scp گرفته تا RTMP و HLS
2. اگر جواب سوال قبل بله هست، اگر بتونی امکانی بزاری که دیگران هم پروتکلی که می خوان رو بتونن به صورت پلاگین موقع کامپایل کردن اضافه کنن خوب میشه.
3. (این آپشن دیگه خیلی توهمیه) ولی اگر لینوکس و واتروال اجازه بده که با هر زبان برنامه نویسی دیگه کانکشن ایجاد بشه و واتروال فقط از اون کانکشن ها استفاده کنه دست توسعه دهنده هایی که مهارت برنامه نویسی C ندارن و یا شما نمی خوای کدهاشون تو ریپازیتوری شما باشه بازتر میشه.
متشکر

**Comment by radkesvat** [comment]
واتروال کلا یه محلیط فلکسیبل هست و تمام روش هایی که الانم روشه به صورت پلاگین نوشته شدن و جدا جدا کامپایل میشن

پورت کردنش به زبان های برنامه نویسی دیگه یکمی دشواره چون باید کل لایبری ww پورت بشه و عملا امکاناتی که زبان های برنامه نویسی دیگه خودشون داره رو ما اینجا از نو نوشتیم برای همین ماژول ها با محیط داخلی خود واتروال مطابق داده شدند؛ برای هرکی که بخواد یه مثلا node جدید پیاده کنه خیلی راحت تره برای خودش که از c استفاده کنه

**Comment by Edizam** [comment]
خیلی خوبه. پس هر موقع که برات امکان داشت یه داکیومنت و راهنمایی براش بنویس لطفا.
چند تا سوال هم تو #63 پرسیدم ممنون میشم جواب بدی.

**Comment by netsupcloud** [comment]
> واتروال کلا یه محلیط فلکسیبل هست و تمام روش هایی که الانم روشه به صورت پلاگین نوشته شدن و جدا جدا کامپایل میشن
> 
> پورت کردنش به زبان های برنامه نویسی دیگه یکمی دشواره چون باید کل لایبری ww پورت بشه و عملا امکاناتی که زبان های برنامه نویسی دیگه خودشون داره رو ما اینجا از نو نوشتیم برای همین ماژول ها با محیط داخلی خود واتروال مطابق داده شدند؛ برای هرکی که بخواد یه مثلا node جدید پیاده کنه خیلی راحت تره برای خودش که از c استفاده کنه

سلام وبسوکت چرا پشتیبانی نمیکنه و quic و kcp و tuic

**Comment by Saleh-Mumtaz** [comment]
> > واتروال کلا یه محلیط فلکسیبل هست و تمام روش هایی که الانم روشه به صورت پلاگین نوشته شدن و جدا جدا کامپایل میشن
> > پورت کردنش به زبان های برنامه نویسی دیگه یکمی دشواره چون باید کل لایبری ww پورت بشه و عملا امکاناتی که زبان های برنامه نویسی دیگه خودشون داره رو ما اینجا از نو نوشتیم برای همین ماژول ها با محیط داخلی خود واتروال مطابق داده شدند؛ برای هرکی که بخواد یه مثلا node جدید پیاده کنه خیلی راحت تره برای خودش که از c استفاده کنه
> 
> سلام وبسوکت چرا پشتیبانی نمیکنه و quic و kcp و tuic و چرا رمزنگاری غیر tls نداره

برای ارتباط بین دو سرور grpc بهترین گزینه هست، در داکیومنت خود گوگل هم اومده که اصلا برای ارتباط دو سرور ساخته شده
