### ISSUE TITLE
پاک شدن ویکی

### ISSUE THREAD

**Issue by H4m3d84** [radkesvat/WaterWall#85]
دروود. چرا ویکی رو پاک کردید؟ به آموزش ها چطوری دسترسی داشته باشیم؟

**Comment by hatinati2** [comment]
> دروود. چرا ویکی رو پاک کردید؟ به آموزش ها چطوری دسترسی داشته باشیم؟

سلام 
بالای قسمت ایشو ها 
بر روی آموزش نصب اولیه بزنید آدرس جدید ویکی موجود هست
