### ISSUE TITLE
تانل یک سرور خارج به چند سرور داخل

### ISSUE THREAD

**Issue by NIKA5050** [radkesvat/WaterWall#86]
سلام داکیومنت رو خوندم ولی تست کردم نشد که چند داخل به یک خارج متصل کنم روی حالت ریلتی و غیره... لطفا مثال یا توضیحی بدهید با تشکر

**Comment by radkesvat** [comment]
تکمیل خواهد شد داکیومنت

**Comment by alimahjoub** [comment]
سلام چی شد من میخام  Half-Duplex بزنم 

من یه سرور ایران دارم

۲ تا خارج

میخام با واتروال Half-Duplex
تانل کنم

مثلا پورت 4030 اومد بره ۴۴۳ یه آیپی خاص

4040 اومد بره  443 یه سرور خاص

**Comment by mtashani** [comment]
سلام برای چند ایران و یک خارج باید برای هر ایران یک فایل کانفیگ درست کنید تو سرور خارج و مقدار configs تو هسته  ویرایش کنید و همه کانفیگ ها رو معرفی کنید

**Comment by mtashani** [comment]
البته من cdn تک پورت تست کردم نشد و همچنین کلا cdn مولتی پورت حتی برای یه دونه هم نشد
