### ISSUE TITLE
udp 

### ISSUE THREAD

**Issue by mah981** [radkesvat/WaterWall#87]
سلام ممنون از زحمتاتون من وی پی انم روی upd هست از این waterwall میشه استفاده کرد ؟

**Comment by radkesvat** [comment]
بله میشه منتهی داکیومنت نشده؛ قرار میدم بعد از اضافه شدن وایرگارد توی همین چند روز؛‌ خلاصه بگم باید tcp listener به جاش udp listener بزارید.

اگه قراره کانکشن udp over tcp باشه باید یک جفت نود protobuf توی chain قرار بدید تا سایز پکت ها حفظ بشه و درست برسه به دست مقصد

**Comment by radkesvat** [comment]
امروز البته وایرگارد تموم نمیشه ؛ تا عصر محل کارم و فکر نکنم اصلا تایم پیدا کنم ادامش بدم...

**Comment by hatinati2** [comment]
> بله میشه منتهی داکیومنت نشده؛ قرار میدم بعد از اضافه شدن وایرگارد توی همین چند روز؛‌ خلاصه بگم باید tcp listener به جاش udp listener بزارید.
> 
> اگه قراره کانکشن udp over tcp باشه باید یک جفت نود protobuf توی chain قرار بدید تا سایز پکت ها حفظ بشه و درست برسه به دست مقصد

سلام مهندس وقت بخیر 
خسته نباشید 
ممنون از زحمات شما
اگر بخواهیم هم tcp  و هم udp عبور بدیم باید "type": "TcpListener", به چه چیزی تغییر بدیم؟
ممنونم

**Comment by lokidv** [comment]
لطفا برای وایرگارد بگین چیکار کنیم

**Comment by lokidv** [comment]
من TcpListnerرو به  UdpListner تغییر دادم نشد TcpConnector هم تغییر دادم به UdpConnector نشد

**Comment by Saleh-Mumtaz** [comment]
بخاطر اینکه هنوز در برنامه قرار داده نشده
کامیت ها رو چک کنید
wireguard روی ۳۵ درصد مونده مهندس چند وقته سرش شلوغه
