### ISSUE TITLE
مصرف  گیگابیتی cdn tunnle

### ISSUE THREAD

**Issue by esmaeilgh** [radkesvat/WaterWall#88]
سلام خسته ناشید ممنون از زحماتتون 
ببخشید از تانل cdn که استفاده میکنم  هنگام اسپید تست توسط کانفیگ سرعت دانلود سرور به چند گیگابیت در ثانیه میرسه و بعد از اون حدود 500 مگابیت میشود 
![Screenshot 2024-07-02 114727](https://github.com/radkesvat/WaterWall/assets/174425077/ac0c7a5e-75d2-417e-b680-c78101b0971d)
 تعداد ورکر ها رو هم تغییر دادم تاثیری نداشت روی این موضوع ممنون میشم چک کنید

**Comment by radkesvat** [comment]
این فقط روی اسپید تست ایجاد میشه و به خاطر اینه که کلود فلیر buffer کرده کل دیتای اسپید تست رو و تا تهش رو میفرسته ؛ در اپدیت های بعدی یه راهی براش پیدا میکنم
