### ISSUE TITLE
مشکل اکسس شدن دامنه در tls تانل 

### ISSUE THREAD

**Issue by imsnayder** [radkesvat/WaterWall#89]
سلام وقت بخیر
تانل  tls سرعت خوبی داشت اما یک مشکلی که هست این بود که هر 2 روز دامنه برای من اکسس میکرد 
راهکاری براش هست؟

**Comment by radkesvat** [comment]
با mux , halfduplex ترکیب کنید احتمالش خیلی خیلی کم میشه
