### ISSUE TITLE
فیدبک استفاده از واتروال و اکانتینگ دایرکت تروجان

### ISSUE THREAD

**Issue by m2tts2001** [radkesvat/WaterWall#9]
سلام و خداقوت
من بلاخره تونستم ریورس با tls رو تست کنم اما چیزی که هست کیفیتش مثل اوایل پروژه RTT بود و بعد از مدت کوتاهی در حد نیم تا یک ساعت یا قطع میشد یا بشدت کند میشد که نیاز بود مجدد راه اندازی بشه.
روش direct trojan هم تست کردم که به مراتب کیفیت و سرعت بهتری داشت.
هر دو روش تنها کاربر خودم بودم 
دوتا سوال داشتم
اول اینکه اگر بخوایم direct trojan استفاده کنیم برای مدیریت اکانتینگ چه روشی پیشنهاد میشه و آیا شدنی هست؟
دوم در رابطه با direct trojan آیا میشه routing هم بهش اضافه کرد مثل xray که مثلا بعضی از سایت ها از warp یا wireguard رد بشوند؟

**Comment by milad84z** [comment]
منم ریورس tls h2 رو چک کردم،ارتباط برقرار میشه ولی دایما قطع و وصل میشه،اینم لاگ سرور
![Screenshot_20240417_182755_Termius](https://github.com/radkesvat/WaterWall/assets/147247389/2ef93dd8-4ecd-4897-80d2-6737d3392bfc)
![Screenshot_20240417_182814_Termius](https://github.com/radkesvat/WaterWall/assets/147247389/b7d0b2db-73f3-4830-a473-108d4ecdabd1)

**Comment by radkesvat** [comment]
دایرکت تروجان فعلا امکان روتینگ نداره ؛ درمورد reverse h2 نمیدونم چرا قطعی وصلی هست روی تست های که من زدم و چند نفر دیگه اصلا چنین چیزی نبود بازم خیلی عوامل دخیل میتونه باشه
