### ISSUE TITLE
ERROR SocketManager: could not find consumer for Tcp socket

### ISSUE THREAD

**Issue by mahbod1996** [radkesvat/WaterWall#91]
توی حالت Reality Tunnel Reverse، تانل رو بعنوان یه سرویس توی systemd اجرا میکنم. half duplex فعاله و worker هم 4 به 32 هست (که البته فکر نمیکنم ربطی داشته باشه).

سرویس رو که روی هر دو سرور استارت میکنم
روی سرور خارح مشکلی نیست و  لاگ که میگیرم دریافت میکنم: INFO  ReverseClient: connected.

کانفیگ ها روی سرور خارج هستن و با IP سرور ایران کار میکنن که این نشون میده تانل برقرار هست.
ولی توی لاگ روی سرور ایران پیامی مبنی بر اینکه فهمیده سرور خارج بهش وصل شده نمیبینم و مدام دریافت میکنم: **ERROR SocketManager: could not find consumer for Tcp socket FD:1c**.
جتی توی همون لاگ ip کلاینتی که به VPN وصل هستن رو هم میبینم که نوشته: TcpListener: Accepted FD:81.

دلیل خاصی داره؟ جایی رو اشتباه رفتم؟ این ارور دقیقا سعی داره بهم چی بگه؟
میشه راهنمایی کنید؟ اگر اطلاعات بیشتری هم نیازه بهم بگید.

**Comment by radkesvat** [comment]
این ارور نیگه مثلا بخش whitelist رنج ایپی ای که هست اشتباهه، اونو چک کنید حتما

**Comment by mahbod1996** [comment]
آقا دم شما گرم اشتباها اسلش 32 زده بودم 🥰
