### ISSUE TITLE
سوال در مورد تانل cdn

### ISSUE THREAD

**Issue by lostsoul6** [radkesvat/WaterWall#93]
درود @radkesvat 

در تانل cdn ما از دامنه استفاده میکنیم . آیا این دامنه امکان دارد فیلتر شود ؟ اگر بله ، چطور میشه این فیلتری را به تاخیر انداخت ؟ امکانش هست یک کانفیگ نمونه از ترکیب cdn با halfduplex و mux ارائه بدید ؟ آیا تاثیری در فیلتر نشدن یا دیر تر شدن دامنه دارد؟ تشکر

**Comment by mtashani** [comment]
توی کانفیگ سرور ایران من فقط 
"cert-file": "/etc/letsencrypt/live/sub.mydomin.ir/fullchain.pem",
 "key-file": "/etc/letsencrypt/live/sub.mydomin.ir/privkey.pem",
 و کانفیگ خارج هم هر سه تا دامین رو تغییر دادم
 اما وصل نشد چیو باید چک کنم؟
 ایا با کانفیگ vmess + header مشکل داره؟
 از هر دو سرور میتونم به دامین پینگ بگیرم
 چطوری میتونم پیدا کنم مشکل از کجاست؟

**Comment by radkesvat** [comment]
من هیچوقت ندیدم روش ریورس سی دی ان دامنه فیلتر کنه، مثال هاشم توی گیت هاب قرار داده شده

**Comment by mtashani** [comment]
@radkesvat 
ممکنه رو پنل هدیفای بخاطر haproxy کار نکنه؟
من RRT زدم جواب میده مولتی پورت ولی این cdn هر کاری کردم جواب نداد

**Comment by mtashani** [comment]
@radkesvat 
لاگ روی ارور تنظیم کردم اما چیزی ثبت نکرد تک پورت تونستم وصل بشم ولی مولتی پورت نه
