### ISSUE TITLE
ایا روی سرور با ip کثیف کار میکنه؟

### ISSUE THREAD

**Issue by nsa14** [radkesvat/WaterWall#94]
سلام ممنون میشم اگه دوستان جواب گرفته راهنمایی کنه
روی سرور کثیف تست کردم جواب نداد تانلش

**Comment by Saleh-Mumtaz** [comment]
چه نوع تانلی استفاده کردید؟

**Comment by radkesvat** [comment]
روش های ریورس کار میدن، با روش ریورس سی دی ان دیگه اصلا ایپی سرور خارج مهم نیست
