### ISSUE TITLE
مشکل عدم اتصال مجددبعد از دیسکانت  شدن 

### ISSUE THREAD

**Issue by MD1373** [radkesvat/WaterWall#96]
سلام وقتتون بخیر ، ممنون از شما بابت پروژه بسیار عالی waterwall

بنده دارم از روش reverse reality + half dublex  استفاده میکنم ، همه چی اوکیه فقط بعد از دیسکانکت شدن مجدد وصل نمیشه باید چند بار قطع و وصل کنی تا دوباره کانکت بشه ، ایراد از چی میتونه باشه؟

**Comment by radkesvat** [comment]
در صفحه شروع توضیح دادم اخرش، میتونید از nohup استفاده کنید تا ران بمونه، با زدن این دستور

'''sh
 nohup./Waterwall &
'''

با اینکار دیگه ران میمونه، اگه بعدا خواستید ری استارتش کنید، باید اول استوپش کنید و دوباره همین دستورو بزنید.

برای بستنش این دستور کاربرد دارد

'''sh
pkill Waterwall
'''

**Comment by MD1373** [comment]
بله دقیقا ازین دستور استفاده کردم ، منطورم موقع کانکت یا دیسکانکت شدن کانفیگ بود که وقتی اینکارو میکنم باید هردفعه چندبار خاموش روشن کنم از v2ray تا وصل بشه و پینگ بده

**Comment by ariadarkkkis** [comment]
منم همین مشکل رو دارم روی تانل reverse hd reality که یهو کانکشن تانل قطع میشه و حدود ۱ دقیقه اینا طول میکشه تا دوباره وصل شه. سرویس هم نوشتم براش ولی ریستارت نمیشه تو سرویس چون exit نمیکن (نباید هم بکنه منطقا). ممکنه مشکل در تایم retry های بین قطعی ها باشه. چون دوباره وصل میشه ولی طول میکشه تا وصل شه.
