### ISSUE TITLE
مشکل تانل ریورس ریلیتی

### ISSUE THREAD

**Issue by mmdkevin** [radkesvat/WaterWall#98]
وقتی تانل میزنم کار میکنه ولی ارور زیر رو تو سرور خارج همش نشون میده 

WARN  connfd=26 connect error: Transport endpoint is not connected:107

**Comment by radkesvat** [comment]
این لاگ یعنی یه پورتی اشتباهه ؛ مثلا توی سرور خارج پورت xray اشتباه باشه یا پورت سرور ایران ؛ برسی کنید ادرس و پورت هارو

**Comment by mmdkevin** [comment]
مالتی پورت رو استفاده کردم

**Comment by Alireza78na** [comment]
> مالتی پورت رو استفاده کردم

من طبق صحبت مهندس چندتا چیزو میگم چک کنید:
1. پورت رو سرور ایران توسط چیز دیگه ای اشغال نشده باشه
2. پورت اتصال واتروال رو هردو سرور درست ست شده باشه
3. پورتای مدنظرت روی فایروال آزاد باشه
4. تنظیمات کانفیگ درست باشه

**Comment by netsupcloud** [comment]
> وقتی تانل میزنم کار میکنه ولی ارور زیر رو تو سرور خارج همش نشون میده
> 
> WARN connfd=26 connect error: Transport endpoint is not connected:107

@radkesvat 

این ارور حتی وقتی تانل درست کار میکنه و کانکشن برقرار میشه هم هست ممکنه مربوط به سیستم پکت فیلترینگ باشه که مشکل ریستارت سر 1 دقیقه هم بخاطر همون باشه
